### ISSUE TITLE
Audio playlist

### ISSUE THREAD

**Issue by joesepi** [Selz/plyr#10]
It would be great to have playlist functionality. If I get a chance, I will dig in and see if I can PR a working version.

**Comment by SamPotts** [comment]
No worries. I was going to take a look at this tomorrow but feel free.

**Comment by SamPotts** [comment]
Hey Joe, going to merge this with #3 and take a look in one hit.

**Comment by joesepi** [comment]
My bad. I misread your comment in #3 to mean that you wanted me to open a new issue. Thanks, regardless.
