### ISSUE TITLE
Remove duplicated code

### ISSUE THREAD

**Issue by calvintam236** [Selz/plyr#100]
When I looking at the source code, I notice some code can be removed.

https://github.com/Selz/plyr/blob/master/src/js/plyr.js#L574 is unnecessary while there is a default case and it works exactly the same.

A question, is there any coding standard for this project?

**Comment by SamPotts** [comment]
It's not duplicate code:

`mozFullScreenElement` is not the same as `mozFullscreenElement`

You're on fire raising non issues to suit your own requirements without really thinking things through. You can always do some contributing and a pull request :) 

If you don't like the coding or the player, feel free to try another player and bug them.
