### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by lionel-m** [Selz/plyr#101]
Hi,

Could we have an option to translate the buttons in other languages?

Thanks

**Comment by SamPotts** [comment]
Sure. We do this on Selz using a hogan template and then injecting the correct language into placeholders but I'm sure I could come up with something for the default controls to make life easier.

**Comment by lionel-m** [comment]
:+1:

**Comment by SamPotts** [comment]
Hey Lionel, I've added in `i18n` as an option. See [controls.md](https://github.com/selz/plyr/blob/master/controls.md) for more info. :+1:

**Comment by lionel-m** [comment]
:+1: Thanks !

**Comment by filips123** [comment]
There should be some central translation "repository" for translations. See #1261.

**Comment by sampotts** [comment]
Good idea. Feel free to open a pull request!
