### ISSUE TITLE
Mute icon disappears

### ISSUE THREAD

**Issue by calvintam236** [Selz/plyr#109]
I updated my script to v1.3.2. The mute icon does not show when volume is greater than 0, and it will show super big when muted.

![muted](https://cloud.githubusercontent.com/assets/6436149/9191470/853fb60c-3fb6-11e5-9d11-7579d990d923.png)

**Comment by SamPotts** [comment]
Did you update the LESS also? Does the same happen on http://plyr.io

**Comment by SamPotts** [comment]
The control markup changed as a result of #103 which would cause this. You need to upgrade your LESS or SCSS me thinks.

**Comment by calvintam236** [comment]
I am using the CSS file from the dist folder. I looked into the code, and plyr does not generate the button. Live demo at http://calvintam236.github.io/media-plyr/

**Comment by SamPotts** [comment]
OK so it's probably the captions markup that you've not changed. I did add a note to the change log:
https://github.com/Selz/plyr/blob/master/changelog.md#v130

More info here:
https://github.com/Selz/plyr/blob/master/controls.md

A pretty small change really (`<input>` + `<label>` to `<button>`) which made more sense accessibility wise and it cleaned up the CSS and JS a bit also.

**Comment by calvintam236** [comment]
Thanks. Fixed.. :+1:

**Comment by SamPotts** [comment]
Awesome :+1:
