### ISSUE TITLE
Fullscreen and non HTTPS on WebKit

### ISSUE THREAD

**Issue by SamPotts** [Selz/plyr#110]
Update docs to include information about using HTTPS with fullscreen to prevent the console warning:

> requestFullscreen() is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

The fullscreen helper should detect support once the functionality is removed but you never know.

**Comment by nahtnam** [comment]
For anyone having this issue, I would recommend using cloudflare. They provide free ssl. It's not 100% secure, but its better than nothing.
