### ISSUE TITLE
Multiple Youtube videos

### ISSUE THREAD

**Issue by OGPoyraz** [Selz/plyr#114]
Hey,
First of all thank you for great plugin.
I just wanna ask is it possible to add multiple youtube videos on the same page ?
When I try to initialize plyr, there isnt any error but second player doesnt pop up. Sorry for it's a noob question. 
Thanks in any advice
<img width="776" alt="screen shot 2015-08-21 at 15 59 16" src="https://cloud.githubusercontent.com/assets/7644512/9408739/e5f7a2b0-481d-11e5-85de-c7d3b8a76215.png">

**Comment by SamPotts** [comment]
Hey mate, I'll check this out and let you know. Thanks for raising it :+1:

**Comment by SamPotts** [comment]
Hey, this should now be fixed! Sorry about that. Cheers :+1:
