### ISSUE TITLE
Issues when dynamically initialising/destroying players

### ISSUE THREAD

**Issue by daveystruijk** [Selz/plyr#116]
Example: http://jsfiddle.net/6Evrq/672/

I'm trying to use plyr as an Ember component that dynamically gets inserted/removed whenever the user navigates to a certain route. What happens is:

1) If I navigate away from the video route too quickly (while a player is still loading/initialising), the page breaks and plyr's YouTube player raises on plyr.destroy(): `Uncaught TypeError: Cannot read property 'parentNode' of undefined`. Without the youtube player, switching routes rapidly works fine, except for the next issue:

2) Regardless of how quickly I navigate, exactly after 4 times of switching to the video route, plyr's mp4 player breaks and won't load the video until I refresh the page again.

**Comment by SamPotts** [comment]
I'll take a look. Thanks for reporting it...

**Comment by SamPotts** [comment]
Hi, could you give this another go with the latest version?

**Comment by SamPotts** [comment]
This should be fixed in v1.9.0 - could you give it a go? Bear in mind there were also several breaking changes so check the [changelog](https://github.com/Selz/plyr/blob/master/changelog.md)
