### ISSUE TITLE
No "Full Screen" Option When Playing Audio

### ISSUE THREAD

**Issue by martindale** [Selz/plyr#119]
This may seem counter-intuitive, but the full-screen menu item disappears when changing to an audio source.  Ideally, the interface is consistent no matter what the media type.

Maybe always use a `<video>` element (which should play mp3s just fine)?

**Comment by SamPotts** [comment]
I can look into this but feel it would be strange behaviour, what would the fullscreen version show? It would just be a stretched player. I could probably consider this if support for audio covers was added I guess?

**Comment by martindale** [comment]
Long-term plans include rendering the audio cover (or Soundcloud track image, which we use [in production today](https://coding.soundtrack.io)!), or potentially later, a Javascript-powered audio visualization.  I'd ignore the latter case  for now and just focus on keeping the interface the same.

I think my crazy visualization dream case will require a `<canvas>` anyway, unless I can figure out how to render to `<video>` from JS...

**Comment by SamPotts** [comment]
OK, I'll look at this when adding the cover photo in somehow but don't feel it's worthwhile with the current audio player. It'd be fullscreen and using 5% of the screen real estate which negates the UI consistency for me.

**Comment by martindale** [comment]
If I can control the fullscreen setting externally, that'd solve the problem, as long as fullscreen isn't eliminated when rotating from a video to an audio track (or vice versa).

**Comment by SamPotts** [comment]
Fixed in [v1.5.0](https://github.com/Selz/plyr/releases/tag/v1.5.0)
