### ISSUE TITLE
Support browserify and webpack

### ISSUE THREAD

**Issue by Riim** [Selz/plyr#121]
> `this.plyr = this.plyr || {}`

`this` in the browserify/webpack module refers not to `window`.

UMD would be ideal.

**Comment by SamPotts** [comment]
Hey @Riim , I'll take a look and add this into the next release. :+1:

**Comment by SamPotts** [comment]
Fixed in [v1.5.0](https://github.com/Selz/plyr/releases/tag/v1.5.0)

Could you please check as I'm new to UMD.
