### ISSUE TITLE
Title tag iframe - Youtube

### ISSUE THREAD

**Issue by robkluytmans** [Selz/plyr#124]
W3 says we have to give an iframe a title attribute (http://www.w3.org/TR/2015/NOTE-WCAG20-TECHS-20150226/H64). I see that happening in the Youtube example: **title="YouTube video player"** 

Is it possible to define the title of an Youtube iframe?

**Comment by SamPotts** [comment]
I'll add this into the next release :+1:

**Comment by robkluytmans** [comment]
Great. Thanks!

**Comment by SamPotts** [comment]
Fixed in [v1.5.0](https://github.com/Selz/plyr/releases/tag/v1.5.0)

It now uses the `title` option.
