### ISSUE TITLE
Not working in IOS9 safari

### ISSUE THREAD

**Issue by ForeverPx** [Selz/plyr#125]
When i open http://plyr.io in safari with my iphone , the video is not setup , it use the html5 default player.
But the audio is setup by code.

Chrome in ios also has the problem.

Why is it?

**Comment by SamPotts** [comment]
iOS doesn't allow custom HTML5 video players. You'll notice all videos (on other sites too) will open the native player. Just one of those things unfortunately.

**Comment by ForeverPx** [comment]
Why the buttons didn't display in iOS ?  i saw the source code is SVG.

**Comment by SamPotts** [comment]
As I say, it's something Apple doesn't support. The native player is *forced* and videos play in full screen no matter what. Native apps have more control. 

https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html

**Comment by ForeverPx** [comment]
Oh, I see. Thanks~

**Comment by ForeverPx** [comment]
is you judge the browser and find if it is safari in ios , you do not setup the video ?

**Comment by SamPotts** [comment]
Yep. Not point adding the custom controls since the video always opens up in the native player anyway.

**Comment by thelamborghinistory** [comment]
Is this a thing to work around (without html5) maybe? So we could use plyr in (iOS) apps as well, like https://github.com/videogular/videogular for Angular / Ionic?

**Comment by thelamborghinistory** [comment]
Another bump: It is actually possible to use plyr on iOS. Basically just adding "webkit-playsinline" to the video tag will do it. If in some weird case it doesn't, you can use https://github.com/bfred-it/iphone-inline-video on the video tag as well and that one will do it for sure.
However, at least for me, plyr will be hugely distorted on iOS for me, as the video element is much bigger than the screen, although I have max-width: 100% on it. Can we have another look on this at some point?

**Comment by hardcorenik** [comment]
Hello, I have a problem with playing video in iOS too.
I have a video with text vtt subtitles in mp4 format. My problem is that if tap the play button, the video doesn't start. If I reload the page containing the video, the play button works flawlessly.

I bet there is something related to the preloading of the video or something else.. anyone had this issue?
thanks,
