### ISSUE TITLE
Error: templates is not defined when using docs.js unminified file

### ISSUE THREAD

**Issue by themoflow** [Selz/plyr#128]
When i try using the <i>unminified docs.js</i> file located in the download zip folder at: <i>/docs/src/js/docs.js</i>, I get a js error stating: "templates is not defined". Can i get a version of the <i>unminified docs.js</i> file that doesnt break?

**Comment by SamPotts** [comment]
Sorry about this. You need to run Gulp to build the templates but I've removed that dependency now so grab the latest version and you should be good.

**Comment by themoflow** [comment]
i just downloaded the latest version and put the plyr and docs js files into place but i get two errors:

ERROR: shr is not defined
ERROR: templates is not defined

**Comment by SamPotts** [comment]
Are you seeing these errors on https://plyr.io? The docs code is specific to the docs setup so don't use that for your setup. Take a look through the docs https://github.com/Selz/plyr

**Comment by themoflow** [comment]
I noticed in your vtt that you also mark the time for the moments that do
not have text. Does this work better than just marking the times when there
is text?

**Comment by SamPotts** [comment]
It seems to be the only way to "clear" the previous text in one of the major browsers. I tested in quite a few when I first did the project. It might no longer be a bug now. I'll check it out.

**Comment by themoflow** [comment]
I am having issues with my vtt in some browsers and yours has non so i
think it is def the way to go. I just wanted to double check and see if toy
were also having the same issues. Thanks

**Comment by themoflow** [comment]
Do you use a special text editor to create your vtt file? Maybe one that
doesnt add hidden characters that mess up the vtt read in or something like
that?

**Comment by themoflow** [comment]
Oh also, on mobile (or atleast on ipad), after i hit the restart video
button the subtitles stop showing?

**Comment by themoflow** [comment]
So it sounds like you are saying that docs.js is not a needed js file to
make the player work. but when i take it out i get an error saying:

"templates is not defined".

Is docs js a required file or no? (The docs.js file is not located in the
dist directory also)

**Comment by SamPotts** [comment]
You need to call `plyr.setup()` which is all mentioned in the docs. I'd really suggest reading that first? 

I'll look at your potential iPad bug.
