### ISSUE TITLE
Can't seek on iOS

### ISSUE THREAD

**Issue by JosephSilber** [Selz/plyr#130]
In iOS (at least on the iPhone), tapping anywhere in the progress bar does not seek to that position.

**Comment by SamPotts** [comment]
Is this an issue on plyr.io? Or just an issue on the develop branch? The controls should not even show on iOS due to support issues.

Sam

**Comment by JosephSilber** [comment]
It's there too. Yes.

Talking about the audio player.

**Comment by SamPotts** [comment]
Ah, well that's again an iOS quirk where you have to drag the handle of a progress element. However, as its not really visible on the current design, it's not obvious. I was planning on making the controls a little more like the YouTube and new Facebook video controls so I guess I'll do that in v1.5. 

Sam

**Comment by SamPotts** [comment]
Partially fixed in [v1.5.0](https://github.com/Selz/plyr/releases/tag/v1.5.0), I've made the handle larger but will work on a better fix shortly.

**Comment by yippibrian** [comment]
This still seems to be a problem with the latest code.

**Comment by sampotts** [comment]
Use rangetouch. It works fine on https://plyr.io. I've also mentioned it in the docs.

**Comment by kakulukia** [comment]
@sampotts can you explain what you mean by "use rangetouch"? I have searched the plr.io html contents and searched for rangetouch in the docs. No luck.

Can you please explain how this rangetouch fix works?
I have a customer probably affected by this on iPhone Xr.
