### ISSUE TITLE
Does not work in iOS Safari private mode

### ISSUE THREAD

**Issue by JosephSilber** [Selz/plyr#131]
In Safari's private mode, you can't use localstorage. Any attempt to set an item to local storage will throw a quota exceeded limit, which breaks the whole player.

The only remedy currently is to disable it altogether by setting `storage.enabled` to `false`.

**Comment by SamPotts** [comment]
Good catch. This an easy fix - need to actually store a test object in storage (in a try/catch) and check it actually stored. I'll make a fix.

**Comment by SamPotts** [comment]
Fixed in [v1.5.0](https://github.com/Selz/plyr/releases/tag/v1.5.0)
