### ISSUE TITLE
how to setup controls?

### ISSUE THREAD

**Issue by puppetMaster3** [Selz/plyr#132]
plyr.setup({'controls:["restart"]'})

this produces error unexpected token }

Is there an example of how to setup controls?

**Comment by SamPotts** [comment]
Yes because you're passing a JSON `string` as opposed to an `object`. Try this:

```
plyr.setup({ controls: ["restart"] });
```

**Comment by puppetMaster3** [comment]
tried it just now. now it says setAttributed of undefined. 

Maybe because I have multiple players?

**Comment by SamPotts** [comment]
I've not tried such a bare bones UI so I'll have to get back to you on that.

**Comment by SamPotts** [comment]
Fixed in [v1.5.0](https://github.com/Selz/plyr/releases/tag/v1.5.0)
