### ISSUE TITLE
Is there anything wrong in my code thanks for your help

### ISSUE THREAD

**Issue by liuronghuan** [Selz/plyr#145]
who can help to check the listed codes thanks Please forgiving my poor english
<script>
  plyr.setup({
    enabled: true,
    captions: {
      defaultActive: false
    },
    controls: ["play", "current-time", "duration", "mute", "volume", "captions", "fullscreen"],
    html:["<div class='player-controls'>",
    "<div class='player-progress'>",
        "<label for='seek{id}' class='sr-only'>Seek</label>",
        "<input id='seek{id}' class='player-progress-seek' type='range' min='0' max='100' step='0.5' value='0' data-player='seek'>",
        "<progress class='player-progress-played' max='100' value='0'>",
            "<span>0</span>% played",
        "</progress>",
        "<progress class='player-progress-buffer' max='100' value='0'>",
            "<span>0</span>% buffered",
        "</progress>",
    "</div>",
    "<span class='player-controls-left'>",
        "<button type='button' data-player='restart'>",
            "<svg><use xlink:href='#icon-restart'></use></svg>",
            "<span class='sr-only'>Restart</span>",
        "</button>",
        "<button type='button' data-player='rewind'>",
            "<svg><use xlink:href='#icon-rewind'></use></svg>",
            "<span class='sr-only'>Rewind {seektime} secs</span>",
        "</button>",
        "<button type='button' data-player='play'>",
            "<svg><use xlink:href='#icon-play'></use></svg>",
            "<span class='sr-only'>Play</span>",
        "</button>",
        "<button type='button' data-player='pause'>",
            "<svg><use xlink:href='#icon-pause'></use></svg>",
            "<span class='sr-only'>Pause</span>",
        "</button>",
        "<button type='button' data-player='fast-forward'>",
            "<svg><use xlink:href='#icon-fast-forward'></use></svg>",
            "<span class='sr-only'>Forward {seektime} secs</span>",
        "</button>",
        "<span class='player-time'>",
            "<span class='sr-only'>Current time</span>",
            "<span class='player-current-time'>00:00</span>",
        "</span>",
        "<span class='player-time'>",
            "<span class='sr-only'>Duration</span>",
            "<span class='player-duration'>00:00</span>",
        "</span>",
    "</span>",
    "<span class='player-controls-right'>",
        "<button type='button' data-player='mute'>",
            "<svg class='icon-muted'><use xlink:href='#icon-muted'></use></svg>",
            "<svg><use xlink:href='#icon-volume'></use></svg>",
            "<span class='sr-only'>Toggle Mute</span>",
        "</button>",
        "<label for='volume{id}' class='sr-only'>Volume</label>",
        "<input id='volume{id}' class='player-volume' type='range' min='0' max='10' value='5' data-player='volume'>",
        "<button type='button' data-player='captions'>",
            "<svg class='icon-captions-on'><use xlink:href='#icon-captions-on'></use></svg>",
            "<svg><use xlink:href='#icon-captions-off'></use></svg>",
            "<span class='sr-only'>Toggle Captions</span>",
        "</button>",
        "<button type='button' data-player='fullscreen'>",
            "<svg class='icon-exit-fullscreen'><use xlink:href='#icon-exit-fullscreen'></use></svg>",
            "<svg><use xlink:href='#icon-enter-fullscreen'></use></svg>",
            "<span class='sr-only'>Toggle Fullscreen</span>",
        "</button>",
    "</span>",
"</div>"]
  });
</script>

**Comment by liuronghuan** [comment]
<script>
      plyr.setup({
        enabled: true,
        captions: {
          defaultActive: false
        },
        controls: ["play", "current-time", "duration", "mute", "volume", "captions", "fullscreen"],
        html:["<div class='player-controls'>",
        "<div class='player-progress'>",
            "<label for='seek{id}' class='sr-only'>Seek</label>",
            "<input id='seek{id}' class='player-progress-seek' type='range' min='0' max='100' step='0.5' value='0' data-player='seek'>",
            "<progress class='player-progress-played' max='100' value='0'>",
                "<span>0</span>% played",
            "</progress>",
            "<progress class='player-progress-buffer' max='100' value='0'>",
                "<span>0</span>% buffered",
            "</progress>",
        "</div>",
        "<span class='player-controls-left'>",
            "<button type='button' data-player='restart'>",
                "<svg><use xlink:href='#icon-restart'></use></svg>",
                "<span class='sr-only'>Restart</span>",
            "</button>",
            "<button type='button' data-player='rewind'>",
                "<svg><use xlink:href='#icon-rewind'></use></svg>",
                "<span class='sr-only'>Rewind {seektime} secs</span>",
            "</button>",
            "<button type='button' data-player='play'>",
                "<svg><use xlink:href='#icon-play'></use></svg>",
                "<span class='sr-only'>Play</span>",
            "</button>",
            "<button type='button' data-player='pause'>",
                "<svg><use xlink:href='#icon-pause'></use></svg>",
                "<span class='sr-only'>Pause</span>",
            "</button>",
            "<button type='button' data-player='fast-forward'>",
                "<svg><use xlink:href='#icon-fast-forward'></use></svg>",
                "<span class='sr-only'>Forward {seektime} secs</span>",
            "</button>",
            "<span class='player-time'>",
                "<span class='sr-only'>Current time</span>",
                "<span class='player-current-time'>00:00</span>",
            "</span>",
            "<span class='player-time'>",
                "<span class='sr-only'>Duration</span>",
                "<span class='player-duration'>00:00</span>",
            "</span>",
        "</span>",
        "<span class='player-controls-right'>",
            "<button type='button' data-player='mute'>",
                "<svg class='icon-muted'><use xlink:href='#icon-muted'></use></svg>",
                "<svg><use xlink:href='#icon-volume'></use></svg>",
                "<span class='sr-only'>Toggle Mute</span>",
            "</button>",
            "<label for='volume{id}' class='sr-only'>Volume</label>",
            "<input id='volume{id}' class='player-volume' type='range' min='0' max='10' value='5' data-player='volume'>",
            "<button type='button' data-player='captions'>",
                "<svg class='icon-captions-on'><use xlink:href='#icon-captions-on'></use></svg>",
                "<svg><use xlink:href='#icon-captions-off'></use></svg>",
                "<span class='sr-only'>Toggle Captions</span>",
            "</button>",
            "<button type='button' data-player='fullscreen'>",
                "<svg class='icon-exit-fullscreen'><use xlink:href='#icon-exit-fullscreen'></use></svg>",
                "<svg><use xlink:href='#icon-enter-fullscreen'></use></svg>",
                "<span class='sr-only'>Toggle Fullscreen</span>",
            "</button>",
        "</span>",
    "</div>"]
      });
    </script>

**Comment by SamPotts** [comment]
You only need to specify options if they are different from the default. In the case of the `html` option, you could omit that and just use the `controls` option like you have.

```
plyr.setup({
    controls: ["play", "current-time", "duration", "mute", "volume", "captions", "fullscreen"],
});
```

What's your HTML markup?

**Comment by liuronghuan** [comment]
i want to make the html different from the default ,but it make an error 
```
    <script>
      plyr.setup({
        controls: ["play", "current-time", "duration", "mute", "volume", "captions", "fullscreen"],
        html:string,
      });
    </script>
```
the string i take place with the code https://github.com/Selz/plyr/blob/master/controls.md#example-1

Finally the code is

```
    <script>
      plyr.setup({
        controls: ["play", "current-time", "duration", "mute", "volume", "captions", "fullscreen"],
        
        
        html:["<div class='player-controls'>",
    "<div class='player-progress'>",
        "<label for='seek{id}' class='sr-only'>Seek</label>",
        "<input id='seek{id}' class='player-progress-seek' type='range' min='0' max='100' step='0.5' value='0' data-player='seek'>",
        "<progress class='player-progress-played' max='100' value='0'>",
            "<span>0</span>% played",
        "</progress>",
        "<progress class='player-progress-buffer' max='100' value='0'>",
            "<span>0</span>% buffered",
        "</progress>",
    "</div>",
    "<span class='player-controls-left'>",
        "<button type='button' data-player='restart'>",
            "<svg><use xlink:href='#icon-restart'></use></svg>",
            "<span class='sr-only'>Restart</span>",
        "</button>",
        "<button type='button' data-player='rewind'>",
            "<svg><use xlink:href='#icon-rewind'></use></svg>",
            "<span class='sr-only'>Rewind {seektime} secs</span>",
        "</button>",
        "<button type='button' data-player='play'>",
            "<svg><use xlink:href='#icon-play'></use></svg>",
            "<span class='sr-only'>Play</span>",
        "</button>",
        "<button type='button' data-player='pause'>",
            "<svg><use xlink:href='#icon-pause'></use></svg>",
            "<span class='sr-only'>Pause</span>",
        "</button>",
        "<button type='button' data-player='fast-forward'>",
            "<svg><use xlink:href='#icon-fast-forward'></use></svg>",
            "<span class='sr-only'>Forward {seektime} secs</span>",
        "</button>",
        "<span class='player-time'>",
            "<span class='sr-only'>Current time</span>",
            "<span class='player-current-time'>00:00</span>",
        "</span>",
        "<span class='player-time'>",
            "<span class='sr-only'>Duration</span>",
            "<span class='player-duration'>00:00</span>",
        "</span>",
    "</span>",
    "<span class='player-controls-right'>",
        "<button type='button' data-player='mute'>",
            "<svg class='icon-muted'><use xlink:href='#icon-muted'></use></svg>",
            "<svg><use xlink:href='#icon-volume'></use></svg>",
            "<span class='sr-only'>Toggle Mute</span>",
        "</button>",
        "<label for='volume{id}' class='sr-only'>Volume</label>",
        "<input id='volume{id}' class='player-volume' type='range' min='0' max='10' value='5' data-player='volume'>",
        "<button type='button' data-player='captions'>",
            "<svg class='icon-captions-on'><use xlink:href='#icon-captions-on'></use></svg>",
            "<svg><use xlink:href='#icon-captions-off'></use></svg>",
            "<span class='sr-only'>Toggle Captions</span>",
        "</button>",
        "<button type='button' data-player='fullscreen'>",
            "<svg class='icon-exit-fullscreen'><use xlink:href='#icon-exit-fullscreen'></use></svg>",
            "<svg><use xlink:href='#icon-enter-fullscreen'></use></svg>",
            "<span class='sr-only'>Toggle Fullscreen</span>",
        "</button>",
    "</span>",
"</div>"].join("\n");,
      
      
      });
    </script>
```

**Comment by SamPotts** [comment]
You don't need to use the `controls` option if you're specifying `html`, they are mutually exclusive. What have you changed in the HTML and what is the error?

**Comment by SamPotts** [comment]
Sorry, the controls docs were out of date. I've just updated. Try the updated code.

**Comment by partageux** [comment]
The same for me : I try to change the disposition of the html tags in my présentation by using a script "plyr.setup" in my template, but your explanations have no clarity. In fact I want to insert carriage returns before "plyr__controls--left" and "plyr__controls--right" for separate in 3 lines : 1-the progress, 2-the controls and 3-the timing with the sound. Have you a solution ? thanks (from France…)

**Comment by SamPotts** [comment]
You don't need line breaks. It's simple HTML. A line break (unless you mean `<br>`) means absolutely nothing. Basically it just needs to be a string.

You could use something like this:
[http://www.accessify.com/tools-and-wizards/developer-tools/html-javascript-convertor/](http://www.accessify.com/tools-and-wizards/developer-tools/html-javascript-convertor/)

and select `Build up a string variable that you can use later` then use that in your configuration. I could add more information but this is basic JavaScript and HTML knowledge. 

If you want, you could use a Hogan template instead.

**Comment by partageux** [comment]
I think you don't understand the question. :)

1 •
In my template I start with : 
<script>
plyr.setup({
    html: **my controls**
});
</script>

2 •
And then I exactly paste your code (I will modify this later on) :
    html: ["<div class='player-controls'>",
    "<div class='player-progress'>",
...etc

But your code doesn't work. What to do ?

…/

**Comment by SamPotts** [comment]
There were three class names that wrong but they didn't throw an error, just made the controls look weird. I've fixed that now in the example: 
https://github.com/Selz/plyr/blob/master/controls.md

I've used those exact controls here:
https://jsfiddle.net/587x93rd/

Seems to work fine for me?
