### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by calvinl** [Selz/plyr#146]
Any plans to make plyr available via npm?

**Comment by SamPotts** [comment]
Sounds good. Will take a look :+1:

**Comment by ablipan** [comment]
+1

**Comment by marvinhagemeister** [comment]
+1 hit this today at work when a colleague wanted to install it via npm

**Comment by SamPotts** [comment]
The latest version is now included in npm. Let me know if you run into any problems. 

```
npm install plyr 
```
