### ISSUE TITLE
SCSS compile errors

### ISSUE THREAD

**Issue by ivanvermeyen** [Selz/plyr#148]
Hi,

Your player looks absolutely awesome!

I was trying to compile your SCSS with Gulp and got some errors.
It seems there are 2 issues in "plyr.scss":

On [line 49](https://github.com/Selz/plyr/blob/master/src/sass/plyr.scss#L49) "@gray-dark" is not recognized. I changed this to "$plyr-gray-dark".

On [line 62](https://github.com/Selz/plyr/blob/master/src/sass/plyr.scss#L62), there is a semicolon before "!default'. I removed this.

Now it compiles without errors.

**Comment by ivanvermeyen** [comment]
On [line 390](https://github.com/Selz/plyr/blob/master/src/sass/plyr.scss#L390) the reference to "plyr__progress" is faulty: "&--progress" should be "&__progress".

**Comment by SamPotts** [comment]
Thanks mate, I'll fix these up. :+1:  

Oddly I do test by running the `gulp sass` task but it didn't throw any errors.

**Comment by ivanvermeyen** [comment]
Thanks! :+1: 

Also, in relation to #149, if I use the SASS compiled CSS, the controls don't hide at all. If I find out why, I'll let you know. What I described in #149 is tested with the dist/css version.

**Comment by SamPotts** [comment]
Cool mate. Looking at #149 now.

**Comment by ivanvermeyen** [comment]
Oops wrong button :)

**Comment by SamPotts** [comment]
No worries, just pushed the fixes :+1:
