### ISSUE TITLE
Autohide controls after mouseleave

### ISSUE THREAD

**Issue by ivanvermeyen** [Selz/plyr#149]
Hi,

When I open a YouTube or Vimeo video in fullscreen, the controls hide as intended. When I move the mouse over the progress bar at the bottom, the controls slide up, but when I move the mouse back up, they don't hide again. I'm having this issue with the latest Chrome and Firefox on OSX.

After doing some console.logs, it seems that "mousemove" on the ".plyr" container isn't triggered when you move over the video itself. So "_showControls()" is never called unless you are actually moving over the controls. Therefor "isMouseOver" is always true when "_showControls()" is fired.

https://github.com/Selz/plyr/blob/master/src/js/plyr.js#L1755-L1768

It seems to be fixed when I change [line 1783](https://github.com/Selz/plyr/blob/master/src/js/plyr.js#L1783):

```
_toggleListener(plyr.container, 'mousemove', _showControls, plyr.isFullscreen);
```

into

```
_toggleListener(plyr.controls, 'mouseenter mouseleave', _showControls, plyr.isFullscreen);
```

But I'm not entirely sure if this would impact other parts of the code.

**Comment by SamPotts** [comment]
I ended up re-writing this as the new source stuff meant after source change, the events weren't bound properly. Could you give the latest version a check?

**Comment by ivanvermeyen** [comment]
Thanks for the fast response! With the dist/css it works like a charm! :)

When I use the compiled SCSS the controls never hide though. Probably still a typo somewhere in the SCSS.

**Comment by ivanvermeyen** [comment]
I think I found it, on [line 643](https://github.com/Selz/plyr/blob/master/src/sass/plyr.scss#L643) in the SCSS file I changed:

```
&.plyr--fullscreen.plyr--fullscreen--hide-controls.plyr--playing
```

into:

```
&.plyr--fullscreen-enabled.plyr--fullscreen--hide-controls.plyr--playing
```

(added "-enabled" to the first selector).

Seems to compile and work now.

**Comment by SamPotts** [comment]
You're right - it needed to be outside that block (which it is in the LESS, hence that working). All sorted :+1:
