### ISSUE TITLE
Requiring plyr with webpack

### ISSUE THREAD

**Issue by marvinhagemeister** [Selz/plyr#153]
One last issue I've hit with using plyr as an npm module is the way it's loaded. I'm using webpack as a module bundler which should (according to the docs) support both AMD and CommonJS style modules. Unfortunately it does not work for me, whereas exporting plyr as a CommonJS module first works perfectly. PR #152  swaps the checks for AMD/CommonJS and puts CommonJS in front.

I'm not sure if this is the most elegant way or the correct solution. I have no experience with AMD modules, perhaps someone else can chime in on this.

**Comment by SamPotts** [comment]
Merged this previously. Can I close this or should we keep it open just incase anyone has input?

**Comment by marvinhagemeister** [comment]
Ah sorry I forgot to close this issue. Thanks for merging!
