### ISSUE TITLE
Set default colors only if they are null (SASS)

### ISSUE THREAD

**Issue by ivanvermeyen** [Selz/plyr#158]
Hi

I was trying to set some colors for the controls, but it seems you are overwriting the vars `$plyr-control-color` and `$plyr-control-color-hover`, based on the lightness of `$plyr-controls-bg` and `$plyr-control-bg-hover`.

https://github.com/Selz/plyr/blob/master/src/sass/plyr.scss#L26-L45

I could change the 'gray' vars, but `$gray: red;` doesn't feel that good :)

Maybe you could add a check to see if `$plyr-control-color` and `$plyr-control-color-hover` are null before overwriting them?

Still loving this plugin! :+1:

**Comment by SamPotts** [comment]
I think using `!default` would solve this? Sorry, I've always been a LESS person and have been meaning to move over to SASS but just haven't found the time. I'll check it out and get back to you.

Cheers :+1:

**Comment by ivanvermeyen** [comment]
Thanks.

Based on this answer: http://stackoverflow.com/questions/12521197/sass-how-to-set-a-variable-to-equal-nothing the following seems to work for me:

```
// Contrast
@if lightness($plyr-controls-bg) >= 65% && not $plyr-control-color {
    $plyr-control-color: $plyr-gray-light;
}
@elseif not $plyr-control-color {
    $plyr-control-color: $plyr-gray-lighter;
}
@if lightness($plyr-control-bg-hover) >= 65% && not $plyr-control-color-hover {
    $plyr-control-color-hover: $plyr-gray;
}
@elseif not $plyr-control-color-hover {
    $plyr-control-color-hover: #fff;
}
```
