### ISSUE TITLE
Seeking issues

### ISSUE THREAD

**Issue by franceer** [Selz/plyr#161]
Hi,

I tried seeking a youtube video before hitting play button and it never shows the frame of the video (at the seek position) as the player does using HTML5 video tag. We can see the youtube loader for ever.

Another issue by using MS Edge when seeking a youtube video : When you seek forward the progress bar is visually correctly updated but if you try to seek backward(dragging),the bar is not visually updated and not reflecting the current position in the video.

The same behavior can be reproduced in FF when seeking backward when the video is paused.

Finally another small issue is when using the HTML5 video tag, FF is showing randomly white frames on seeking when video is paused.

I wasn't able to test on chrome since I currently have an issue to run the demo page on it. Need to figure it out.

I don't know if it's easily fixable but hope it helps to improve this wonderful player !!

FF v 43.0.1
MS EDGE v 20.10240.16384.0

**Comment by franceer** [comment]
I checked on chrome, pausing a youtube video and seeking forward or backward cause the progress bar not being refreshed (as same as FF). When hit play again the progress bar is resfreshed and is accurately positionned at the current video time.

**Comment by SamPotts** [comment]
Sorry about the issues. I'll take a look. :+1:

**Comment by franceer** [comment]
Hey no problem Sam !! I'm just trying to help by testing the player and pushing it in a corner. This player is very great and you are doing a great job ;) Thank you !!

**Comment by SamPotts** [comment]
Thanks man :+1: :-)

**Comment by SamPotts** [comment]
Hey - could you give this a check in v1.6.0? I made some changes to the seeking UI which may help this.

**Comment by franceer** [comment]
I checked with a delay sorry. Yeah it seems so much better ! I like the new interface of the player btw. Good jobs and thank you.

**Comment by SamPotts** [comment]
Awesome - thanks for getting back to me 👍
