### ISSUE TITLE
Custom duration when option: html

### ISSUE THREAD

**Issue by k-zakhariy** [Selz/plyr#169]
When i set 'html' parameter, then duration sets to  --:--
`var player =  plyr.setup(playerSelector, {
                                html: controls,
})[0];`

How i can set duration when i use custom controlls  ?

**Comment by SamPotts** [comment]
The controls don't effect the duration - the duration comes from the media itself. If you want to display duration, set `duration` to `true` in the config.

**Comment by SamPotts** [comment]
You can specify a custom duration if you need to over ride the one coming from the media file now if you need to using the `duration` option:
https://github.com/Selz/plyr/blob/master/readme.md#options
