### ISSUE TITLE
player.media.currentTime and the likes are not updated

### ISSUE THREAD

**Issue by phanan** [Selz/plyr#170]
I've upgraded from 1.3.x bower to the latest 1.5.x npm version. After the upgrade, I had to make some changes to make things work (naturally), but the biggest problem is, apparently `player.media.xProperty` doesn't get updated during playback anymore. 

```javascript
        this.player = plyr.setup({
            type: 'audio',
            controls: [],
        })[0];
```

```javascript
    playPrev() {
        // If the song's duration is greater than 5 seconds and we've passed 5 seconds into it
        // restart playing instead.
        if (this.player.media.currentTime > 5 && this.player.media.duration > 5) {
```
In the second code block, I would expect `currentTime` and `duration`, being the properties of the underlying `audio` element, get updated and reflect the correct values, but to my surprise they don't. Specifically, `currentTime` is always `0`, and `duration` is `undefined`. Somehow the `media` object of `player`, albeit being an `audio` still, isn't the same element that's playing the track. Is it a bug, or just some version change I'm not aware of?

**Comment by SamPotts** [comment]
Hey @phanan , sorry about this. Is this after calling `.source()`? If so I did just find a bug with that, the media object is not reset so accessing it like that would still give you info about the old media object. Your example shows a new setup though, which should work. 

This is with a basic example.

![image](https://cloud.githubusercontent.com/assets/719092/13200084/b3685366-d88d-11e5-98f9-3e403102e323.png)

Remember duration won't be available until after either a `durationchange` `loadedmetadata` event has occurred. You can check for these events using plyr:
https://github.com/Selz/plyr#events

**Comment by phanan** [comment]
@SamPotts Yes, it's after `.source()`, good catch ;)
And yes, your example is exactly what I'm using as a workaround now. Still, it's not optimized, isn't it? Imagine having to query the selector with every `timeupdate` event…

**Comment by SamPotts** [comment]
If you need the duration, you'll probably want to listen for the `loadedmetadata` as well. Unfortunately you have to wait for this to load - there's no way to predict how long the media is without this occurring. It's usually pretty fast though. 

I've fixed the `.source()` API to reset the media object on change so potentially your original issue is resolved.

**Comment by phanan** [comment]
Great! Thanks!

**Comment by phanan** [comment]
Hmm... Actually, does that imply the media object is "reset" with every call to source? This would destroy any custom uses on the orginal object, for example if you have audio effects set up on it, they will be gone.

**Comment by phanan** [comment]
I can confirm the issue above. In my app, I have a 10-band equalizer connected to an `<audio>` element. If I set the source with `player.source()`, the bands are disonnected (since the `audio` element is reset) and thus the effects are gone. If I manually set the source directly on `player.media.src` instead, the effects are kep.

**Comment by SamPotts** [comment]
Yeah you can do that if you need to retain the same element. Sounds like the `.source()` api method is probably no use to you unless you want to re-set the binding in your call to `.source()`. I could maybe look at not changing the element unless it's a different type.

**Comment by phanan** [comment]
Just curious, and sorry for my ignorance, but why does the element need to be changed? I have a feeling doing so is prone to even more problems than what I've just mentioned.

**Comment by SamPotts** [comment]
It was requested that the source method should allow changes of type (e.g. audio to video). To allow for this, I remove the element and replace it. Like I say, I can look into retaining it if it's the same as the new type. It shouldn't be too hard.
