### ISSUE TITLE
Force aspect ratio?

### ISSUE THREAD

**Issue by ronag** [Selz/plyr#173]
Is there a way to force the aspect ratio of the container?

I could make the plyr container force an aspect ratio however the controls mess things up...

**Comment by SamPotts** [comment]
Hey @ronag, this is certainly possible but using CSS would probably be the best approach - much like the responsive iframe embed method (height: 0, padding-bottom: 56.5% and absolute positioned iframe to give you 16:9). What happens with the controls when you try to do it?

**Comment by ronag** [comment]
Well, if I do it externally then the controls are included in the aspect ratio calculation, which then is wrong...

**Comment by SamPotts** [comment]
There's a video container div which may be useful. I've been meaning to make an option for auto hiding controls so they can be included in the aspect ratio and sit on top of the video like most other players but it's on the back burner at the moment.

**Comment by SamPotts** [comment]
Hey @ronag , with the new theme you should be able to use the 56.25% padding, 0 height trick to force 16:9 or another method as the controls are overlaid.

**Comment by codebucketdev** [comment]
It is still not possible, I tried using the embed-responsive classes in Bootstrap 3, but the controls are still messed up. Here an example: http://rly.li/6rcm/3iiw32
