### ISSUE TITLE
Old request continues to download

### ISSUE THREAD

**Issue by ronag** [Selz/plyr#174]
I don't think old requests are properly cleaned up when changing sources, i.e. I can see in the Chrome Dev Tools that they continue downloading...

In `_updateSource`, instead of just doing:

```javascript
// Remove the old media
_remove(plyr.media);
```

I think the following is required:

```javascript
plyr.media.pause();
plyr.media.src = '';
plyr.media.load();
// Remove the old media
_remove(plyr.media);
```

**Comment by ronag** [comment]
Likewise in destroy

**Comment by SamPotts** [comment]
I've fixed this for the source api but with destroy the intention there is to return the player to it's "default" state, e.g. back to a native UI'd player. In my mind that would mean you wouldn't want to remove the sources there? I could make it an option of course though?
