### ISSUE TITLE
Expose the YouTube API player object

### ISSUE THREAD

**Issue by shakeelmohamed** [Selz/plyr#176]
We want to use Plyr for @zen-audio-player because of the great work you've done on the UI. However, we need to access the YouTube API player object directly and we don't see how that's possible without some changes to Plyr (please correct me if I'm wrong).

We are open to sending a PR if that will help speed things up. The methods we currently access directly on the player object are:

* `getCurrentTime()`
* `getDuration()`
* `getVideoData()`
* `getVideoUrl()`
* `getVolume()`
* `pauseVideo()`
* `playVideo()`
* `seekTo()`
* `setVolume()`

Of these, I believe the one we can't workaround is `getVideoData()` to access the video's title and author for our custom display. We've started the work of integrating Plyr in this PR https://github.com/zen-audio-player/zen-audio-player.github.io/pull/153.

Do you think this is a reasonable change to bring in, or does is break the spirit of the project?
Happy to chat about our project if you need some additional context, the code is pretty simple if you want to take a look.

Thanks, looking forward to hearing from you!

cc @BlinkBP

**Comment by SamPotts** [comment]
Hey @shakeelmohamed, this is definitely possible and should be a small change, I'll try and do it this weekend. :+1:

**Comment by shakeelmohamed** [comment]
:tada:

**Comment by SamPotts** [comment]
Just pushed a change for this. You can access the API through `element.plyr.embed.getVideoData()` for YouTube and Vimeo through `element.plyr.embed.api('play')` :+1: 

https://github.com/Selz/plyr/releases/tag/v1.5.17

**Comment by shakeelmohamed** [comment]
Awesome! Thank you so much for doing this quickly @SamPotts

**Comment by SamPotts** [comment]
Sorry if I was unclear, basically the `embed` property is a direct mapping to the respective api's. So all the methods for YouTube, such as `.getVideoData()` are available on that property. Vimeo uses `.api('method')` and is exposed in a similar way. 

Don't forget a lot of these methods are available in the standardised API methods built into Plyr.

**Comment by BlinkBP** [comment]
@SamPotts  I can't get the `embed` property after changing the source with element's `.source()`. I see that `embed` is nullified in `_updateSource()` in Plyr's code but is it re-referenced somewhere later on?
