### ISSUE TITLE
Bug with duration bubble if the audio duration can't be determined

### ISSUE THREAD

**Issue by phanan** [Selz/plyr#177]
I've noticed today that if the audio duration can't be determined (for example, when playing from a transcoded source), the duration label is messed up:

![image](https://cloud.githubusercontent.com/assets/8056274/13553154/f5f9a518-e3b9-11e5-92a5-d093547947ba.png)

In this example, I have the song served directly from a ffmpeg transcoding stream.

Version: 1.5.13 npm.

**Comment by SamPotts** [comment]
I should probably check if duration has been set. Thanks for this. I guess the progress bar is probably redundant as well then.

**Comment by phanan** [comment]
I'd sugges then to add something like a `plyr-unavailable` (for the lack of a better name) class instead of hiding/removing it entirely, so that users can style as they deem fit.

**Comment by phanan** [comment]
Which can, by default, hide the bar away of course.

**Comment by SamPotts** [comment]
Sounds good. I'm going to be looking at some UI improvements soon so I'll add this to the list.

**Comment by SamPotts** [comment]
Hey, there's a bug fix for this in [v1.6.2](https://github.com/Selz/plyr/releases/tag/v1.6.2)

**Comment by phanan** [comment]
You're the man!
