### ISSUE TITLE
how can create a Multiple language captions (with selection)

### ISSUE THREAD

**Issue by ruhong65** [Selz/plyr#182]
<track kind="captions" label="English" srclang="en" src="http://hsbc.splashinteractive.com.cn/testp/View_From_A_Blue_Moon_Trailer-HD.en.vtt" default>

                        <track kind="captions" label="Chinese" srclang="cn" src="http://hsbc.splashinteractive.com.cn/testp/View_From_A_Blue_Moon_Trailer-HD.cn.vtt" default>

it's not work , can anybody help me on this?

**Comment by SamPotts** [comment]
Hey @ruhong65 , sorry this isn't currently support but is on my to-do list.

**Comment by SamPotts** [comment]
Merging this with #143
