### ISSUE TITLE
Can't get vimeo working + how to have controls like demo

### ISSUE THREAD

**Issue by cinghaman** [Selz/plyr#187]
http://amancingh.com/tether/vimeo.html  demo test
And if you will see the player in bottom have controls dont have cursor: pointer how can i change that?

**Comment by SamPotts** [comment]
Sorry, just going through issues and I can't see your demo page. Did you get this fixed?

**Comment by AnthyG** [comment]
This could be the solution to the answer, though it should be like that already:
```
.plyr__controls button:hover {
    cursor: pointer;
}
```

**Comment by cinghaman** [comment]
Hey, no couldnt do it the way it was in demo, had to manually download the videos from vimeo and add it as mp4

**Comment by AnthyG** [comment]
@cinghaman well I don't think it should be like that! :?

**Comment by SamPotts** [comment]
Closing this as I can't seem to view your example or really understand the issue. Maybe give the latest version a go?

**Comment by cinghaman** [comment]
Sure no problem, if i need to use it again and have same problem i will post with updated link
