### ISSUE TITLE
Add support for YouTube player's onError event

### ISSUE THREAD

**Issue by shakeelmohamed** [Selz/plyr#189]
Hi @SamPotts,

We're really close to having Plyr integrated to Zen Audio Player! One of the few things remaining is error handling. Currently we're able to display the error to the user, which is usually helpful.
To me, it makes sense to expose this with the `error` event - but I could imagine a special `youtubeError` event as well. What do you think?

![capturfiles_1](https://cloud.githubusercontent.com/assets/1480063/14201713/85816110-f7a8-11e5-9ab9-53a3d09de10b.png)

**Comment by SamPotts** [comment]
I'll create an error callback, yeah. Will get to this on the weekend all going well.

**Comment by shakeelmohamed** [comment]
Thank you! :+1:

**Comment by shakeelmohamed** [comment]
@SamPotts sorry to nag, will you be able to get this in the same release as #194? Happy to help out if needed

**Comment by SamPotts** [comment]
Sure. Will have a crack this weekend. 

Sam

**Comment by SamPotts** [comment]
Sorry just been flat out with work etc

Sam

**Comment by shakeelmohamed** [comment]
No worries, thanks for the update!

**Comment by SamPotts** [comment]
Hey, this is in [v1.6.2](https://github.com/Selz/plyr/releases/tag/v1.6.2)

**Comment by shakeelmohamed** [comment]
@SamPotts Excellent, the code change looks usable!
I just updated to v1.6.3, and I'm seeing these issues:

1. `plyr.js:2222 Uncaught TypeError: Cannot read property 'bar' of undefined` is breaking the whole thing, I think changing the `else {` on line 2221 in `src/js/plyr.js` to `else if (progress) {` should take care of that.
2. The CSS redesign for audio players 100% broke our usage 😅 , see the screenshot below. Can you provide us with a workaround? Maybe add a bool setting like `retroPlayer` to use the old UI?

![capturfiles_6](https://cloud.githubusercontent.com/assets/1480063/14940126/ff2cf896-0f1b-11e6-8c12-07bed62acda8.png)

**Comment by SamPotts** [comment]
I've already raised an issue to create the older theme for anyone that wants to use it. Styling should be kept separated from the JS so this will be a CSS change. In terms of a workaround, you'd have to hack around the LESS to get it presentable. Sorry, it was a improvement for most but I can understand the frustration of the UI change. I'll make a start on it now and maybe finish it today.

**Comment by SamPotts** [comment]
Pushed v1.6.4 with a fix for the progress issue

**Comment by SamPotts** [comment]
Are you using like YouTube and hiding the video? Hmm I've not thought about that but I guess that could be a use case for others too.

**Comment by shakeelmohamed** [comment]
> Are you using like YouTube and hiding the video?

Yeah, that's the whole premise of Zen Audio Player 😆  I actually hacked over some of the CSS (for now) from the `.plyr__audio .plyr__controls` rule and made them all `!important` under  `.plyr__controls` to get something working. In that case, we actually don't need a different theme, just way to render a video player as if it's an audio player

**Comment by SamPotts** [comment]
OK well a couple of others have asked for the old theme so I'll just make that and it'll be two birds with one stone as it were...
