### ISSUE TITLE
Different behavior for control bar playing YouTube/Vimeo in fullscreen mode 

### ISSUE THREAD

**Issue by calvintam236** [Selz/plyr#191]
Once user makes the player fullscreen and plays the YouTube/Vimeo video, the player control bar disappears like it supposed to. Moving cursor to the bottom of the screen do not trigger the control bar to reappear like what it does in the standard video type. Plyr.io demo shows the same behavior.

**Comment by SamPotts** [comment]
Thanks for reporting this, I'll take a look this weekend :+1:

**Comment by SamPotts** [comment]
This should be fixed in v1.6.0
