### ISSUE TITLE
How to embed YouTube video with auto play video poster

### ISSUE THREAD

**Issue by vaibhav-jain** [Selz/plyr#192]
I want to embed a YouTube video for more details have a look at [this ](http://stackoverflow.com/questions/36496007/how-to-embed-youtube-video-with-auto-play-thumbnail)

I was looking out for a solution and found this repo but wondering how to implement this.

**Comment by AnthyG** [comment]
If I understand the question correctly, you want to have one Video autoplaying, and onclick, you want another Video played?
If so, hav'a look at this [http://codepen.io/anthyG/pen/WwJojB].
I tried my best ;)

**Comment by vaibhav-jain** [comment]
Thanks @AnthyG  its exactly what I was looking for . . . . .

**Comment by AnthyG** [comment]
This may be off-topic, but it would be nice, if you would mark [my answer on stackoverflow](http://stackoverflow.com/a/36664465/5712160) as the solution, or whatever it's called, because it actually is my first on there :+1: 

Great I could help!! :smiley:
