### ISSUE TITLE
Support for Soundcloud

### ISSUE THREAD

**Issue by monicacheung** [Selz/plyr#194]
Hi! We are currently in the process of adding support for Soundcloud to Zen Audio Player. One of the things we would need is Plyr to play Soundcloud tracks. We made some changes to plyr.js to play Soundcloud tracks by trackid which we have been using in our PR (zen-audio-player/zen-audio-player.github.io#186). It would be cool if we could get this added to Plyr. :)

**Comment by shakeelmohamed** [comment]
PR is #196

**Comment by SamPotts** [comment]
Thanks for this. I just need to merge with my new UI changes in v1.6.0 and we're set 👍

**Comment by shakeelmohamed** [comment]
Great new @SamPotts 🎉

**Comment by SamPotts** [comment]
Hey, this is in [v1.6.2](https://github.com/Selz/plyr/releases/tag/v1.6.2)

**Comment by shakeelmohamed** [comment]
Awesome, thanks a ton @SamPotts! @monicacheung you've got work to do 😀

**Comment by SamPotts** [comment]
I didn't play around with it too much. I noticed in the SoundCloud API docs, to play "direct" without using their player would require an API key. Something to look at later on I think.
