### ISSUE TITLE
Warning in firefox when using vimeo

### ISSUE THREAD

**Issue by magicspon** [Selz/plyr#197]
Hello,

When using vimeo I'm getting the following warning in Firefox.

> mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

Cheers

**Comment by SamPotts** [comment]
OK will take a look thanks for the report 👍

**Comment by SamPotts** [comment]
Ah, just taken a look and this is an error with Vimeo's code in `https://f.vimeocdn.com/p/2.24.3/js/player.js` - Might be worth raising it with them
