### ISSUE TITLE
CSS duplicate selectors

### ISSUE THREAD

**Issue by robinpoort** [Selz/plyr#201]
I found two duplicate selectors in both the less and scss files:

The first one:
https://github.com/Selz/plyr/blob/master/src/scss/plyr.scss#L79-L81
and
https://github.com/Selz/plyr/blob/master/src/scss/plyr.scss#L110-L112

Second one:
https://github.com/Selz/plyr/blob/master/src/scss/plyr.scss#L449-L456
and
https://github.com/Selz/plyr/blob/master/src/scss/plyr.scss#L458-L464

Same goes for .less files. Want me to do a PR for this? Or is this something you rather do yourself real quick?

**Comment by robinpoort** [comment]
I went ahead and created a PR :)

**Comment by SamPotts** [comment]
Merged this 👍
