### ISSUE TITLE
Video: tooltips hidden on IE11

### ISSUE THREAD

**Issue by emmanuelclement** [Selz/plyr#210]
On Internet Explorer 11, buttons are natively overflow:hidden (see user-agent CSS on http://www.iecss.com/ ).
(No overflow specified on IE Edge so you can see the tootips.)

Buttons are overflow:visible on others browsers.

note: normalize.css set overflow visible on button and input.

I'll make a pull request soon today to fix it.

**Comment by SamPotts** [comment]
Merged this, cheers!
