### ISSUE TITLE
Cannot change source in iPhone

### ISSUE THREAD

**Issue by calvintam236** [Selz/plyr#213]
While I am testing using iPhone screen size, I got this error when I try to click on "Audio" or other tabs.

Chrome:
```plyr.js:1 Uncaught TypeError: Cannot read property 'buffer' of undefined```

Safari:
```ke — plyr.js:685
TypeError: undefined is not an object (evaluating 'Se.progress.buffer')```

![screen shot 2016-05-12 at 11 18 20 pm](https://cloud.githubusercontent.com/assets/6436149/15258730/09bdb026-1902-11e6-87b2-a38df4cdc4a1.png)

**Comment by SamPotts** [comment]
Fixed in latest version - thanks for reporting 👍
