### ISSUE TITLE
Vimeo videos in fullscreen is not align to the center

### ISSUE THREAD

**Issue by calvintam236** [Selz/plyr#214]
It is currently align to the top of the screen. Found on Chrome, Firefox with v.1.6.8.

![screen shot 2016-05-14 at 3 51 33 am](https://cloud.githubusercontent.com/assets/6436149/15268036/b1ed9056-1987-11e6-80a4-11b22ce357b3.png)
![screen shot 2016-05-14 at 3 51 59 am](https://cloud.githubusercontent.com/assets/6436149/15268037/b209927e-1987-11e6-843c-a914f0791db1.png)

**Comment by SamPotts** [comment]
Yeah I noticed this recently. It's because we have to do something funky to hide the Vimeo controls as they have no option like YouTube. Will investigate with the track API issue. 

Sam

**Comment by colinduet** [comment]
@sampotts - we also have this issue. is there a fix for this? thank you!
