### ISSUE TITLE
Video player will not auto resize after changing source on iPhone

### ISSUE THREAD

**Issue by koyin** [Selz/plyr#215]
While playing video loaded from `src` of the `<video>` tag, it's fine and the player will resize according to screen resolution.

![img_1820](https://cloud.githubusercontent.com/assets/6348675/15270202/4f2af608-1a49-11e6-9607-5c8ac0674f0d.PNG)
![img_1821](https://cloud.githubusercontent.com/assets/6348675/15270205/5c999f24-1a49-11e6-9132-31677e4da94e.PNG)

But after I load a new source using `plyr.source`, the player will no longer auto resize, instead display the video in full size.

![img_1822](https://cloud.githubusercontent.com/assets/6348675/15270213/8a4c2c5c-1a49-11e6-9e55-1709582b09cd.PNG)

**Comment by SamPotts** [comment]
This isn't really a bug with Plyr as such. As custom UIs for HTML5 video are not fully supported on iOS, no styles are added for it in Plyr. I'd recommend adding the following standard CSS for images, videos and audio to your build if you don't have it already:

```css
img,
video,
audio {
    max-width: 100%;
    vertical-align: middle;
}
```

You'll see the docs have something similar.
