### ISSUE TITLE
Thumbnail video preview

### ISSUE THREAD

**Issue by hookro** [Selz/plyr#219]
Could you make a thumbnail video preview?

**Comment by hookro** [comment]
?????????????

**Comment by hookro** [comment]
...

**Comment by SamPotts** [comment]
Sorry, could you be a little more impatient? There's plenty of other issues to attend to as I'm sure you can see. You're not the only one around here... 

If you're going to raise an issue, at least put some effort into an explanation. A thumbnail where? There's poster image functionality baked right into the HTML5 elements. If you mean in the seek tooltip like YouTube does, then you'd need to do something custom. It might be possible using canvas to load the buffered video and use that to display. Another option would be generating them server side. It's on my to-do along with a load of other features. This is an **open source** project that I maintain in my spare time.
