### ISSUE TITLE
Quality option for html videos?

### ISSUE THREAD

**Issue by thelamborghinistory** [Selz/plyr#220]
First of all I just want to say I came here from PH and I instantly fell in love with this player (not only I have a crush on it but it also came up at the perfect time on my screen ;)). So big kudos to you guys.

However, I am curious if it's possible to integrate an option to switch quality of a video like YouTube has (I think half of the functionality for such a feature is already done with the plyr.source() method, so there might just remain a nice dropup menu for the resolution options). What do you think?

**Comment by SamPotts** [comment]
For sure - I will look into how this can be done. 👍

**Comment by SamPotts** [comment]
Merging to #218
