### ISSUE TITLE
If we right click on video player then 'Show controls' option is visible, if we select that then basic HTML5 player controls along with custom player controls are visible

### ISSUE THREAD

**Issue by dineshb-qa** [Selz/plyr#225]
**Steps to Reproduce**

1. Hit the URL : https://plyr.io/#video 
2. Right click on the player 
3. Observe that options like : 'Loop', 'Show controls' etc are visible on player
4. Now select the 'Show controls' option
5. Observe that : Basic HTML5 player controls along with custom player controls are visible for video player

**Expected Results** : 

1. 'Show controls' option should not be visible when we right click on player
2. Only custom player controls should be visible on video player

**Actual Results** :  
If we right click on video player then 'Show controls' option is visible, if we select that then basic HTML5 player controls along with custom player controls are visible

**Notes** :
See the attached screen shot : 
![two_player_controls_18may](https://cloud.githubusercontent.com/assets/6957604/15364082/bbca0aaa-1d38-11e6-8998-71dc794c1d05.png)

**Comment by johnyeye** [comment]
add this to your video tag , oncontextmenu="return false;"

**Comment by SamPotts** [comment]
There's something about killing the context menu that doesn't feel good to me. There are other options in there that user may find useful. I'll look into using shadow DOM selectors to hide the default controls.

**Comment by SamPotts** [comment]
I added an option to hide the context menu using @johnyeye 's code. Thanks for that 👍

**Comment by accunity-arpit** [comment]
That worked for me too, Thanks @johnyeye

**Comment by SamPotts** [comment]
@accunity-arpit It's built in as an option now - see my comment above yours from last year 👍
