### ISSUE TITLE
Styling issues when using less

### ISSUE THREAD

**Issue by Morganjackson** [Selz/plyr#228]
I keep seeing what appears to be two styles for the progress inputs:

<img width="1377" alt="screen shot 2016-05-19 at 12 43 56 pm" src="https://cloud.githubusercontent.com/assets/833805/15381061/6adc743e-1dbf-11e6-9717-85ce14740179.png">

(same player with some margin added to make it easier to see)

<img width="1383" alt="screen shot 2016-05-19 at 12 31 11 pm" src="https://cloud.githubusercontent.com/assets/833805/15380957/802bc1ce-1dbe-11e6-9557-0339100bb623.png">

Using https://cdn.plyr.io/1.6.12/plyr.css works perfectly.

**Comment by SamPotts** [comment]
Hey Morgan, 

That's very odd given that CSS is just the LESS files built and deployed. What are you using to build the LESS? I had this issue when I wasn't using Autoprefixer (which I'd recommend using if you're not already) so it could be and probably is, that. If you can't use the Autoprefixer lib, then anywhere you see `appearance: none` you'll need to add prefixed versions manually - this would also apply to other spots too. I only write the unprefixed versions of properties to keep things lean and let Autoprefixer do it's thang.

**Comment by Morganjackson** [comment]
Wow thanks for the fast reply!  

Adding Autoprefixer fixed the issue.

**Comment by SamPotts** [comment]
Awesome 👍
