### ISSUE TITLE
[Video][YouTube][Vimeo] In full screen mode the 'Toggle Fullscreen' tooltip text get slighted cut

### ISSUE THREAD

**Issue by dineshb-qa** [Selz/plyr#230]
**Steps to Reproduce**

1. Hit the URL : https://plyr.io/
2. Go to Video / YouTube / Vimeo player tab
3. Click on 'full screen' option in order to move to full screen
4. Now mouse hover on 'full screen' option
5. Observe that : In full screen mode the 'Toggle Fullscreen' tooltip text get slighted cut

**Expected Results** : 
In full screen mode the 'Toggle Fullscreen' tooltip text should get displayed properly

**Actual Results** :  
In full screen mode the 'Toggle Fullscreen' tooltip text get slighted cut

**Notes** :
See the attached screen shot : 
![exit_full_screen_tooltip_not_visible_19may](https://cloud.githubusercontent.com/assets/6957604/15398109/07962eec-1e00-11e6-954f-c53321f5b6aa.png)

**Comment by SamPotts** [comment]
Someone had raised this previously - I'll take a look 👍
