### ISSUE TITLE
Fullscreen option takes time to load for YouTube and Vimeo player as compare to Video player

### ISSUE THREAD

**Issue by dineshb-qa** [Selz/plyr#231]
**Steps to Reproduce**

1. Hit the URL : https://plyr.io/
2. Go to Video player and observe that 'fullscreen' control is loaded along with other player controls
3. Now, go to YouTube player and observe that 'fullscreen' control is not loading/displayed along with other player controls. It takes few seconds to load
4. Now, go to Vimeo player and observe that 'fullscreen' control is not loading/displayed along with other player controls. It takes few seconds to load

**Expected Results** : 
Fullscreen option should load/appear along with other player controls

**Actual Results** :  
Fullscreen option takes time to load for YouTube and Vimeo player as compare to Video player

**Notes** :
See the attached screen shot : 
![full-screen_option_takes_time_to_load_19may](https://cloud.githubusercontent.com/assets/6957604/15398856/f5e8ee0c-1e02-11e6-8d5f-0a73477b75f8.png)

**Comment by SamPotts** [comment]
The time to load is the Vimeo or YouTube API's loading. There's no point showing the fullscreen action unless it can be used?

**Comment by dineshb-qa** [comment]
@SamPotts : As per your above comment, not sure if its possible to hide the all the player controls and show only when full-screen option is available for Vimeo and YouTube player for better user experience?
