### ISSUE TITLE
Not work fullscreen

### ISSUE THREAD

**Issue by extensionsapp** [Selz/plyr#232]
Hello.

Play -> Fullscreen -> :(

https://jsfiddle.net/57sv2k09/

**Comment by SamPotts** [comment]
It appears the `<iframe>` that jsfiddle uses doesn't have the required `allowfullscreen` attribute. If you add this in the dev tools it works. As far as I can tell there's no real failsafe way to detect that the parent iframe has this attribute set.

**Comment by extensionsapp** [comment]
Why does not the player takes all the space without a horizontal scrollbar?

test.html
```
<!DOCTYPE html>
<head>
    <title>Video</title>
    <link rel="stylesheet" href="https://cdn.plyr.io/1.6.13/plyr.css">
    <script src="https://cdn.plyr.io/1.6.13/plyr.js"></script>
    <style>
    body {
        margin:0;
        padding:0;
    }
    </style>
</head>
<body>

<div class="plyr">
    <div data-video-id="bTqVqk7FSmY" data-type="youtube"></div>
</div>

<script>
(function(d, p){
    var a = new XMLHttpRequest(),
        b = d.body;
    a.open('GET', p, true);
    a.send();
    a.onload = function() {
        var c = d.createElement('div');
        c.setAttribute('hidden', '');
        c.innerHTML = a.responseText;
        b.insertBefore(c, b.childNodes[0]);
    };
})(document, 'https://cdn.plyr.io/1.6.13/plyr.svg');
</script>

<script>plyr.setup();</script>

</body>
```

![Scr](http://s017.radikal.ru/i434/1605/61/ec85d48ccbb2.png)

**Comment by SamPotts** [comment]
A bug has already been raised for the above. I'm working on it:
https://github.com/Selz/plyr/issues/222
