### ISSUE TITLE
hls.js is working!

### ISSUE THREAD

**Issue by russitto** [Selz/plyr#235]
Steps:
1. setup hls.js video
2. with this video working, setup plyr with video div container

Example:
http://codepen.io/russitto/pen/oxrKjQ

**Comment by russitto** [comment]
Idem Shaka Player:
http://codepen.io/russitto/pen/LNKwyq

**Comment by AnthyG** [comment]
Well this isn't a Issue,.. or is it? :thought_balloon:

**Comment by russitto** [comment]
It is not a bug. Add this info on readme or wiki ;-)

**Comment by SamPotts** [comment]
Issue or not it's awesome! I'll add this example to the readme

**Comment by wrightpt** [comment]
i love how this example shows .mpd being played.

**Comment by servermeta** [comment]
cool!

**Comment by russitto** [comment]
plyr + dash.js
http://codepen.io/russitto/pen/jqgZgd

**Comment by SamPotts** [comment]
Dude, you're awesome. I'll add these to the docs very shortly...

**Comment by SamPotts** [comment]
Thanks again for this - I've added it to the docs here:
https://github.com/Selz/plyr#streaming
