### ISSUE TITLE
Wordpress Plugin

### ISSUE THREAD

**Issue by iamryandrake** [Selz/plyr#239]
Any chance someone would turn this into a Wordpress plugin?

**Comment by drrobotnik** [comment]
Ask and ye shall receive. https://github.com/drrobotnik/plyr-wp

Keep an eye out for it on the public repo, it's currently in review: https://wordpress.org/plugins/plyr/

**Comment by SamPotts** [comment]
Awesome 👍

**Comment by SamPotts** [comment]
I'll add this to the docs but could you update it to v1.8.0 possibly? It might make setup easier as the wrapper `<div>` is no long required.

**Comment by drrobotnik** [comment]
Updated dist/js to what looks like 1.8.2.
