### ISSUE TITLE
[YouTube Player] On start screen a black button (like youtube) is visible behind the 'blue' play button

### ISSUE THREAD

**Issue by dineshb-qa** [Selz/plyr#240]
**Steps to Reproduce**

1. Hit the URL : https://plyr.io/
2. Click on 'YouTube' option in order to see youtube player
3. Observe that : On start screen a black button (like youtube) is visible behind the 'blue' play button

**Expected Results** : 
On start screen only the customize 'blue' play button should be visible

**Actual Results** : 
On start screen a black button (like youtube) is visible behind the 'blue' play button

**Configuration Manifesting** :
Windows 8, Chrome 50

**Content Manifesting** : https://plyr.io/#youtube

**Notes** :
See the attached screen shot : two_buttons_visible_24may.png
![two_buttons_visible_24may](https://cloud.githubusercontent.com/assets/6957604/15508092/c2c86aba-21eb-11e6-9a48-f0a526a12f47.png)

**Comment by SamPotts** [comment]
Thanks for the thorough report but unfortunately there's no way to hide this with the current YouTube API.
