### ISSUE TITLE
Seek precision

### ISSUE THREAD

**Issue by MariasStory** [Selz/plyr#242]
I set a "prayer.addEventListener('pause'," event and use "player.seek(player.media.currentTime)".

As a result, the video currentTime is rounded and the video position jumps to some offset.

What's wrong with this example?

Is there a way to get and set exact frame?

**Comment by SamPotts** [comment]
I'll take a look at this

**Comment by SamPotts** [comment]
I *think* that you can only see in whole seconds. Are you trying to seek to something more granular? https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/currentTime 

Seeking to currentTime would be a little strange as you're effectively setting the currentTime to currentTime :)

**Comment by MariasStory** [comment]
Hi @SamPotts, the point is that player.media.currentTime is quite precise ~4 digits after comma, but the player.seek is rounded to 1 digit after comma.
I use this method to synchronize video playback in two different players.

Do you know a way to get a current frame from one video player and set that frame in another?

**Comment by SamPotts** [comment]
Ah yeah sure. I'm not sure why I rounded to 1 decimal place. Will take another look at it. 

Sam

**Comment by SamPotts** [comment]
Pushed a change in the latest version to round to 4 decimal places instead 👍

**Comment by MariasStory** [comment]
Thanks for promt reaction :+1:
