### ISSUE TITLE
How can i hide the fullscreen option in controls?

### ISSUE THREAD

**Issue by DerBeni** [Selz/plyr#247]
...i want to **disable the fullscreen option in the control bar** (cause my video is in an uikit modal window, opening in fullscreen from there doesn't seem to work on the ipad). 

I don't know the exact syntax i have to use. The setup looks like this:
```
jQuery(document).ready(function($){
myplayer = plyr.setup('#myplayer')[0];
});
```
...or do i simply have to hide it with css?

**Comment by SamPotts** [comment]
Specify the controls you want. It's an option; checkout the docs/readme.
