### ISSUE TITLE
Basic obfuscation of video download functions

### ISSUE THREAD

**Issue by ashdelacroix** [Selz/plyr#248]
A suggestion to assist video creators and distributors by preventing casual downloading of HTML5 video content by replacing the right-click contextual menu with one that removes any "download video" or "copy video URL" menu items or through some other form of obfuscation, possibly by preventing the right-click contextual menu in entirety. Any other ideas are very welcome to prevent casual content downloading and redistribution or hot linking.

**Comment by SamPotts** [comment]
Hey @ashdelacroix , I just added an option to hide the context menu. Last time I look at custom context menus, only Firefox supported them.
