### ISSUE TITLE
data-plyr not work

### ISSUE THREAD

**Issue by heinhoang** [Selz/plyr#249]
I want to change icon sprite url and hide hide all controls but t's not work:
Structure:
```
Root
- Images
-- Icons
--- plyr.svg
- index.html
```
HTML:
```
        <div class="plyr">
          <div data-video-id="143418951" data-type="vimeo" 
                data-plyr='{ iconUrl: "/images/icons/plyr.svg", controls: [] }'>
           </div>
        </div>
```
JS:
`plyr.setup();`

If I pass options as an object to the setup() method (in JS), it works, but as JSON in data-plyr attribute (in HTML), it's not work???

**Comment by SamPotts** [comment]
Add it on the element with the`plyr` class. 👍

**Comment by heinhoang** [comment]
when I do that the video not showing up.
In the browser console, it prints out:
```
VM32869:1 Uncaught SyntaxError: Unexpected token i in JSON at position 2api.setup @ plyr.js:3217(anonymous function) @ main.js:349fire @ jquery.js:3099self.fireWith @ jquery.js:3211jQuery.extend.ready @ jquery.js:3417completed @ jquery.js:3433
browser.js:42Opera has modified script or content on player.vimeo.com (PATCH-1166, vimeo.com - make click-to-play and turbo mode work). See browser.js for details
```

**Comment by SamPotts** [comment]
The keys need to be wrapped in double quotes like this: 
http://codepen.io/sampotts/pen/yJBdaw

e.g. 

```html 
data-plyr='{ "tooltips": { "controls": true, "seek": true } }'
```

**Comment by heinhoang** [comment]
Thanks, it works now but you need to update your home page (https://github.com/selz/plyr), it says (e.g. data-plyr='{ title: "testing" }')
but it should be (e.g. data-plyr='{ "title": "testing" }')

**Comment by SamPotts** [comment]
Cheers - will do 👍
