### ISSUE TITLE
iconUrl option does not play nicely with custom inline SVG sprite

### ISSUE THREAD

**Issue by qikkeronline** [Selz/plyr#251]
I'd like to refer to an SVG symbol ID (generated locally into a custom SVG sprite) like this:

```
    plyr.setup({

        hideControls: true,
        iconUrl: '#icon--car'

    });
```

Currently; this results in the following  markup:

```
<button type="button" data-plyr="play" class="plyr__play-large" aria-label="Play">
    
    <svg>
    
        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon--car#plyr-play"></use>
    
    </svg>
    
<span class="plyr__sr-only">Play</span></button>
```

The expected `xlink:href` value should be `#icon--car`. Would also be great if we could inject viewBox attributes there (it is required for a good cross-browser result).

Thanks for considering it 👍

**Comment by qikkeronline** [comment]
Worked around it like this:

```
    plyr.setup({

        iconUrl: '#icon-' // see https://github.com/Selz/plyr/issues/251

    });
```

Changed line 676 of plyr.js:

`iconPath    = (!iconUrl.external ? iconUrl.url : '');`

And then I included the original SVG files but removed the plyr- prefix in the filenames.

**Comment by SamPotts** [comment]
Could you not have used the `iconPrefix` option for this? The `iconUrl` option is really for if you want plyr to load the sprite for you. `iconPrefix` would allow you to specify the `#plyr-` part and change it to something like `#icon-plyr-` and it would render:

```html
<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-plyr-play"></use>
```

**Comment by qikkeronline** [comment]
Ah, i totally overlooked that option, thanks :-) 

Regarding the viewBox; do you see any possiblities there? I guess it could be difficult as each icon requires their own. But as far as my understanding goes; the inline viewBox attribute on the <use> element is required for older browsers (e.g. IE10 and 11..) to display the svgs in their correct proportions.

**Comment by qikkeronline** [comment]
perhaps it is an idea to be able to pass a templates array so people can hook their <use> elements into the svg controls of the player. e.g.:

    plyr.setup({

        templates: {

            playLarge: '<use>... </use>',

        }

    });

Where each seperate control ui element would have their own value in the array or so.

Thanks again for considering 👍

**Comment by qikkeronline** [comment]
For the time being; I guess the best tactic would be to write a bit of JS that goes through all of the `<use>` elements inside the player after it's finished loading; and then simlpy grab the viewBox values based on their ID and insert them 👍

**Comment by SamPotts** [comment]
The viewBox is set on each icon in the sprite though. Check the examples and you'll see them. They aren't rendered by the JavaScript.  

I think adding the templates option wouldn't really add anything? It's just a link to the SVG def after all.

**Comment by qikkeronline** [comment]
Yup, the viewBox attributes are set inside the SVG sprite (that is also the case for my own custom sprites). I might be wrong here; but at the time I built this system it was still required for IE in certain situations to also have the viewBox attribute on the `<use>` element itself. (I believe when using display: inline-block or so from the top of my head). For now I'll hook into the `ready ` event and loop through it myself as it seems it might be specific to my situation. Let me know if you'd appreciate some more info on this; I'll then make sure I look into it at the end of this project.

**Comment by SamPotts** [comment]
If that were the case, the demo on plyr.io would be broken in IE10 and 11 but it's not. Plyr is not supported on IE9 anyway. From experience, it's only needed on the nested SVG itself. Let me know.

**Comment by qikkeronline** [comment]
I'll check it out when I'm done with the bulk of the work and report back here then (expect in +- 2 weeks). Thanks for the fast replies!

**Comment by SamPotts** [comment]
Closing this one for now - no news is good news 👍

**Comment by qikkeronline** [comment]
sorry totally forgot about this @SamPotts :) during our testing we didnt find any inconsistencies on IE :)

**Comment by Gofack** [comment]
I'm still don't get it. How can I change, for example, only one icon?

**Comment by pravinweb** [comment]
Could you please add example here, how to change only one icon - example "play-large" without changing any other icons

**Comment by josipRajkovicFlowout** [comment]
I am also interested in changing a single icon, any news?
