### ISSUE TITLE
Wasn't able to get working, Docs?

### ISSUE THREAD

**Issue by skookie000** [Selz/plyr#253]
I wasn't able to get a hello world version working, for me it was just audio.  Page was blank.  The demo page is difficult to understand where the minimal amount of code needed is, and doesn't help the script assets are compressed.  The docs page isn't clear if the html5 audio markup is enough or if the files are specified over the options variable (or both?).  Where does the sprite go?  Maybe try posting the minimal amount of code needed to make this work.

This is what I was able to guess should have been the hello world example:
```
<link rel="stylesheet" href="https://cdn.plyr.io/1.6.17/plyr.css">
<script src="https://cdn.plyr.io/1.6.17/plyr.js"></script>
<script>plyr.setup();</script>

<div class="plyr">
    <audio controls>
        <source src="file.m4a" type="audio/mp4">
    </audio>
</div>

```

**Comment by SamPotts** [comment]
Did you read the quick start section? The docs are comprehensive and assume an understanding of front end technologies. There's quick start sections for HTML, JavaScript and CSS  and original files are included in the 'src' folder. 

Sam

**Comment by SamPotts** [comment]
I'll dumb down the examples a little more then. My concern is making the docs even more complex but perhaps an examples.md or something would suffice. 

Sam

**Comment by christ0ph3r** [comment]
Is "Quick Start" "Quick setup" ?  If not, where is quick start? 

I feel right now the docs are very confusing.  I have spent a few hours and had no luck setting things up.  I feel pretty stumped.  The docs appear that the HTML markup is enough but that doesn't seem like the case.  Is plyr.js the only js needed to get this working?  I see the example has extra js in docs.js it appears.  If someone just wanted to add youtube what would they do?

Thanks very much for the nice script.  It looks great, I really hope to be able to use it.

**Comment by christ0ph3r** [comment]
I figured it out.  Okay so quick start is quick setup it looks like.  This is how I got it working.  Load the main css and js file.

Then in javascript you can do this ( Make sure it loads after the main js file otherwise plyr will be undefined )

```js
plyr.setup('.js-media-player', {
  debug: 				true,
  title: 				'Video demo',
  iconUrl: 			'../dist/plyr.svg',
  tooltips: 	{
    controls: 		true
  },
  captions: {
    defaultActive: 	true
  }
});
```

Then in the HTML markup

```html
<div class="plyr js-media-player">
  <div data-video-id="bTqVqk7FSmY" data-type="youtube"></div>
</div>
```

Hope that helps someone!

**Comment by SamPotts** [comment]
I'll rename it then if you think that's what it needs - to me quick start = quick setup? Clearly a couple of you are struggling though so perhaps it needs more thought. Do feel free to suggest amends. It's a free, open source project that I maintain in my *spare time* after all :-)

**Comment by SamPotts** [comment]
Made some improvements in v1.7.0

**Comment by christ0ph3r** [comment]
Thank you very much.
