### ISSUE TITLE
Multiple videos loading SVG's multiple times

### ISSUE THREAD

**Issue by thiagupct** [Selz/plyr#259]
If 10 videos were loaded in a single page and plyr was initiated using _plyr.setup()_ 10 times svg was loaded. Can't we limit the same to a single request as a single file is enough to serve the controls for 10 videos.

**Comment by SamPotts** [comment]
Cheers for this. Just pushed an updated version. Could you give it a try? 👍

**Comment by rootion** [comment]
This is issue is still persistent.
I made a new test: 4 videos loaded in a single page, plyr initiated using plyr.setup() and 4 times the svg was loaded. Please see: https://s.codepen.io/rootion/debug/rLoLOa

**Comment by SamPotts** [comment]
Sorry - I've been working on a refactor of multiple issues and this is included. Hoping to get a fix for this out in the next few days.

**Comment by SamPotts** [comment]
This should be fixed in v1.9.0 - could you give it a go? Bear in mind there were also several breaking changes so check the [changelog](https://github.com/Selz/plyr/blob/master/changelog.md)
