### ISSUE TITLE
soundcloud not working

### ISSUE THREAD

**Issue by heinhoang** [Selz/plyr#263]
I want to show this sound https://soundcloud.com/liluzivert/money-longer-radio-rip
but it's not working?
```
<div class="plyr" data-plyr='{ "iconUrl": "/images/icons/plyr.svg" }'>
    <div data-track-id="245673410" data-type="soundcloud"></div>
</div>
```
Does Plyr support soundcloud?

**Comment by SamPotts** [comment]
It's currently undocumented as it's a hidden feature. I will look into it more at a later date.

**Comment by SamPotts** [comment]
Closing this for now until I get stuck into finalising SoundCloud.
