### ISSUE TITLE
Ready event

### ISSUE THREAD

**Issue by smachi** [Selz/plyr#267]

**Comment by SamPotts** [comment]
Any more info?

**Comment by enda-zoo** [comment]
The ready event has stopped firing for my Vimeo videos in the last few days also - I haven't made any changes to my code so i'm guessing Vimeo has updated something on their end... I'm just setting up a codepen now to test out YouTube and HTML5 videos.

**Comment by SamPotts** [comment]
Hmm OK let me know how you go. There's a `ready` event also fired on the containing element of the player (which now bubbles up the DOM as of v1.8.2).

**Comment by enda-zoo** [comment]
Yup, using 1.8.2 fixed the issue alright - thanks !!

Here is the gist I was about to send over using 1.8.1...
https://gist.github.com/enda-zoo/8d5b1839fd10e488b88c133d40000903

Just out of interest, why does the quick start guide not include the "plyr" or "js-plyr" classes around the media element anymore? I guess the less boilerplate the better but it looks like they are needed to attach DOM events - may trip people up.

**Comment by SamPotts** [comment]
Awesome. Good to hear it's sorted. I'm not sure why I didn't bubble those events previously. 

Good point about the divs. I just decided to remove the requirement for the container div to make setup easier for the less technically inclined users. I'll add a note about listening for events and using the API requiring a container to catch events and access the plyr instance. I'm not very good at documentation. 

Thanks for the feedback :-)

**Comment by enda-zoo** [comment]
No problem, happy to help - thanks for sorting out that issue so quickly...
The documentation is great tbh, especially as you're dealing with 4 different APIs :)

Keep up the good work!
