### ISSUE TITLE
YouTube video won't loading when tab isn't open

### ISSUE THREAD

**Issue by itdevroman** [Selz/plyr#268]
YouTube video won't loading until tab would be focused.

**Comment by SamPotts** [comment]
Hmm. What browser? I suspect this is a browser thing. Can you replicate on https://plyr.io ?

**Comment by itdevroman** [comment]
My script is loading playlist with AJAX in real time. When Chrome is minimized and my script recieved and new track to load:

https://gist.github.com/itdevroman/7880a556993f8b762f10882e468c57e0

Plyr will not load track in minimized Chrome. But When I'm opening tab it will instantly play it.

**Comment by itdevroman** [comment]
So script do all the things. But event is not fired.

**Comment by itdevroman** [comment]
So, I will try to fix it in Plyr source code.

**Comment by itdevroman** [comment]
Issue example:
https://jsfiddle.net/itdevroman/9jfobq8a/3/

Run this script and choose another tab in your browser or just minimize browser window.
Playback will not start if this tab is not selected.

**Comment by SamPotts** [comment]
I'm 99.9% sure this is the default YouTube behaviour. If you open a new tab for a YouTube video, it won't play until the tab is focused.

**Comment by itdevroman** [comment]
So I need to create a new plyr player with autoplay for each playlist track? If you are 100% sure about it, we can close this issue.

**Comment by SamPotts** [comment]
I mean that this is something driven by YouTube rather than Plyr. We can't really change this behavior. The same thing happens on YouTube.com; if I open a video in a new background tab, it won't play until I focus that tab.

**Comment by itdevroman** [comment]
Thanks! Do you have any recommendations how can I avoid this?

**Comment by AnthyG** [comment]
But actually the youtube video loads, if it is in a playlist..
So maybe there could be a way to bypass that :thought_balloon:

**Comment by itdevroman** [comment]
Can I use playlist with plyr?

**Comment by AnthyG** [comment]
Not that I know of, but anyways, it was just a though :)

**Comment by SamPotts** [comment]
Closing this as it's really a YouTube issue and nothing can be done within Plyr to get around it currently (until I get to playlists).
