### ISSUE TITLE
 IE11 does'nt seem to like relative iconUrl's in plyr.setup

### ISSUE THREAD

**Issue by Joolyan** [Selz/plyr#269]
After reviewing many other media players, I'm really enjoying playing with Plyr. Thanks for sharing.
 
I'm not a developer, so I'm not sure if the following is an issue limited to novice users like myself.

If iconUrl (in plyr.setup) is given a relative URL (such as dist/plyr.svg) the icons don't render correctly in IE11. However, using a full URL (such as https://cdn.plyr.io/1.6.19/plyr.svg) seems to resolve the issue.
 
I see you've just updated to version 1.7.0 which I believe still shares the same issue.
 
Thanks again.

**Comment by Joolyan** [comment]
Wow...
Fixed using a relative URL for iconUrl in IE (fixes #269) 

I've not had time to test, but just wanted to say 'Thanks'.

**Comment by SamPotts** [comment]
No worries - sorry, I forgot to actually reply to the issue. 👍

**Comment by Joolyan** [comment]
Unfortunately I can still reproduce this issue...

Download
https://plyr.io/index.html
https://cdn.plyr.io/1.8.2/demo.js
https://cdn.plyr.io/1.8.2/demo.svg
https://cdn.plyr.io/1.8.2/plyr.svg

Edit index.html to use downloaded version of demo.js
replace "<script src="https://cdn.plyr.io/1.8.2/demo.js"></script>"
with "<script src="demo.js"></script>"

Edit demo.js to use downloaded versions of plyr.svg and demo.svg (using full URLs)
replace "https://cdn.plyr.io/1.8.2/plyr.svg" with "http://plyr.192.168.1.11.xip.io/test/plyr.svg"
replace "https://cdn.plyr.io/1.8.2/demo.svg" with "http://plyr.192.168.1.11.xip.io/test/demo.svg"

NB. Testing using a MacBook with vmWare Fusion, pow.cx and xip.io

IE11 renders Plyr controls correctly. No issues


Now edit demo.js to local relative URLs
replace "http://plyr.192.168.1.11.xip.io/test/plyr.svg" with "plyr.svg"
replace "http://plyr.192.168.1.11.xip.io/test/demo.svg" with "demo.svg"

The demo.svg renders correctly, but the Plyr controls don't.

Hope this helps?
Please let me know if I should have open a new issue?

**Comment by SamPotts** [comment]
OK I'll take another look

**Comment by SamPotts** [comment]
Think I've nailed it now 👍

**Comment by Joolyan** [comment]
You've nailed it. Just tested v1.8.7 and the issue with IE11 is fixed.
Thanks.
