### ISSUE TITLE
Hiding controls & auto play are not working on 1.7.0

### ISSUE THREAD

**Issue by heinhoang** [Selz/plyr#270]
After update to plyr 1.7.0, hiding controls & auto play are not working any more:
HTML:
```
<div class="plyr" data-plyr='{ "iconUrl": "/images/icons/plyr.svg", "controls": [], "autoplay": true }'>
     <div data-video-id="..." data-type="vimeo"></div>
</div>
```
JS
`plyr.setup();`

**Comment by dungphanxuan** [comment]
me too!

**Comment by SamPotts** [comment]
It's probably worth reading the [changelog](https://github.com/Selz/plyr/blob/master/changelog.md) before upgrading. There was a change to simplify the setup for newer users and also remove the dependency between JS and CSS. 

Use this for your HTML instead:

```html
<div data-video-id="..." data-type="vimeo"  data-plyr='{ "iconUrl": "/images/icons/plyr.svg", "controls": [], "autoplay": true }'></div>
```

**Comment by SamPotts** [comment]
Closing this one - let me know if you still have issues.
