### ISSUE TITLE
Destroy/Restore YouTube not working?

### ISSUE THREAD

**Issue by danielsarin** [Selz/plyr#272]
Hi,

I'm trying to destroy a YouTube instance and then restore it, but it doesn't seem to work. The docs do not mention that these methods wouldn't work for YouTube as well.

My HTML is

`<div data-type="youtube" data-video-id="12345"></div>`

and js

```
videos = plyr.setup({});
```

In the docs it says

> Destroys the plyr UI and any media event listeners, effectively restoring to the previous state before setup() was called.

When I call `videos[0].plyr.destroy()`it doesn't restore the original HTML, though I don't know if it should.

But when I call `videos[0].plyr.restore()` it gives me an error:

_Uncaught TypeError: Cannot set property 'buffered' of undefined_

I made a fiddle: https://jsfiddle.net/f1hc53cq/2/

Is there something I'm doing wrong?

Thanks for any help,
Daniel

**Comment by SamPotts** [comment]
This should be fixed in v1.9.0 - could you give it a go? Bear in mind there were also several breaking changes so check the [changelog](https://github.com/Selz/plyr/blob/master/changelog.md)

**Comment by danielsarin** [comment]
It seems to work now, thanks!
