### ISSUE TITLE
Cannot playing video on iPhone

### ISSUE THREAD

**Issue by ErikPham** [Selz/plyr#277]
When I using plyr for my project on iPhone then do not play video. It has an error "Uncaught TypeError: Cannot read property 'display' of undefined". iPad and all other device work. Thanks for the great work.

**Comment by SamPotts** [comment]
Are you also getting this error on plyr.io by any chance? What is your config?

**Comment by sohrabzia** [comment]
hi, I have having same issue, on iphone video player size is getting exaggerated and i dont want to / cant add css only for iphones.
i am just using 
```plyr.setup();
```
can you please guide me. Thanks,
