### ISSUE TITLE
you can't use lift or right keys to forward the video

### ISSUE THREAD

**Issue by mohmedsalem19** [Selz/plyr#279]
you can't use lift or right keys to forward the video 
as in all players you can use right or left keys to back or move in video you watch so i think it will be a nice touch if you make it possible in the next version of the player

**Comment by SamPotts** [comment]
Hey, I'll make this an option. Currently if you're focused on the seek bar then the left/right arrows will seek (as is default browser behaviour when focusing an `<input type="range">` element.

**Comment by mohmedsalem19** [comment]
yeah i know but it will be more flexible if you add this feature it will be nice rather than focus on the seek bar

**Comment by SamPotts** [comment]
But what I mean is; when should left and right arrows trigger the seek? It needs some more thought around the interactions. Like mouse over the player but no control focused? It's not simple. I don't want to break standard keyboard interactions for accessibility reasons.

**Comment by SamPotts** [comment]
Maybe we could do if focus is "inside" the player and the option is set to true then left / right would seek and up / down would adjust volume?

**Comment by MichielioZ** [comment]
Another suggestion would be to allow shortcut keys only in fullscreen mode, as it can not interfere with normal browser behaviour...

**Comment by SamPotts** [comment]
Merging this with #309
