### ISSUE TITLE
Fullscreen icon displayed in the image file in Readme file and the one in actual player are different

### ISSUE THREAD

**Issue by dineshb-qa** [Selz/plyr#281]
**Steps to Reproduce**

1. Check the readme file = https://github.com/Selz/plyr
2. Check the full-screen icon displayed in the image file = https://cdn.selz.com/plyr/1.5/plyr_v1.6.6.png
3. Go to the URL : https://plyr.io/
4. Observe that : The full-screen icon displayed in the player is different that the 1 displayed in readme 
file

**Expected Results** : 
Fullscreen icon should be consistent across all places

**Actual Results** :
Fullscreen icon displayed in the image file in Readme file and the one in actual player are different

**Comment by SamPotts** [comment]
Thanks. Will update the docs.
