### ISSUE TITLE
Use Plyr with AngularJS

### ISSUE THREAD

**Issue by jechazelle** [Selz/plyr#282]
Hi,

I would like to use [Plyr][1] with AngularJS, but when I install plyr with AngularJS, Plyr doesn't work

I must include :

    <html>
    <head>
    <link rel="stylesheet" href="https://cdn.plyr.io/1.7.0/plyr.css">
    
    </head>
    <body>
    
    <script src="https://cdn.plyr.io/1.7.0/plyr.js"></script>
            
    <div id="plyr" data-type="youtube" data-video-id="bTqVqk7FSmY"></div>
    
    <script>
    var player = plyr.setup(document.querySelector('#plyr'), {
    	debug: true
    });
    
    </script>
    
    
    </body>
    </html>

I tried to create a directive :

    (function (){
        'use strict';
    
        angular.module('ngPlyr', []);
    
        angular.module('ngPlyr').directive('plyr', function () {
            return {
                template: '<div id="plyr" data-type="youtube" data-video-id="bTqVqk7FSmY"></div>'
            };
        })
    
    })();

and

    <div plyr></div>

But it doesn't work, the player with plyr doesn't show

  [1]: https://github.com/Selz/plyr

**Comment by SamPotts** [comment]
Try using the latest version. It looks like you are using new markup with old JS and CSS.

**Comment by kaleem-elahi** [comment]
is it working in angularjs ?

**Comment by kaleem-elahi** [comment]
@jechazelle did it worked in AngularJs then?
