### ISSUE TITLE
YouTube play button behind Plyr play button.

### ISSUE THREAD

**Issue by r3oath** [Selz/plyr#285]
I've noticed recently that the YouTube play button is now sitting behind the Plyr play button. Seems to be that the query parameter 'controls' passed you YouTube isn't working as expected. Any plans/ideas on how to remove it within Plyr? You can see an example below (which occurs on the Plyr demo page):

<img width="154" alt="screen shot 2016-06-23 at 10 59 15 am" src="https://cloud.githubusercontent.com/assets/2805249/16288755/a14065e2-3932-11e6-9e14-6937626663e3.png">

**Comment by r3oath** [comment]
Take it due to the iframe same-domain policy this will currently be impossible to remove (YouTube will have to fix/allow it to be hidden). For the time being I've just made Plyr's play button slightly bigger to cover it up.

**Comment by SamPotts** [comment]
This has been raised before (worth checking closed issues). Nothing can be done to hide that button. Changing the size of the plyr large play button with CSS is your only option.

**Comment by r3oath** [comment]
Gotcha, I did mention the outcome in my second follow up comment. I'll close the issue.
