### ISSUE TITLE
Overflow:hidden on .plyr class causes issues

### ISSUE THREAD

**Issue by EnigmaSolved** [Selz/plyr#286]
I'm on 1.8.3. the `overflow:hidden` setting for the base `.plyr` class is problematic (https://github.com/Selz/plyr/blob/095d100ba44e828f82fb432c5d47fb89a6eaaaf4/src/scss/plyr.scss#L22):

- The time tooltip can't be seen (it's clipped).

- And effects like box shadow get clipped.

`overflow:hidden` was not in 1.8.0, so I don't know the implications of removing it.

**Comment by SamPotts** [comment]
Fixed! I was experimenting with something and left that in there. 👍

**Comment by EnigmaSolved** [comment]
Awesome, thanks man!

**Comment by SamPotts** [comment]
No worries. Sorry about the brief issue.
