### ISSUE TITLE
vimeo incorrect url, youtube "an error occurred, please try again later"

### ISSUE THREAD

**Issue by frumbert** [Selz/plyr#291]
Load plyr via cdn: https://cdn.plyr.io/1.8.7/plyr.js, testing in Chrome Version 51.0.2704.103 (64-bit, OSX)

I'm writing my youtube tag like this:

    <article class="media-surface"><div data-track-id="GguF5lui57U" data-type="youtube"></div></article>

and (in a seperate page) vimeo tag like this:

    <article class="media-surface"><div data-track-id="160978792" data-type="vimeo"></div></article>

and then initialising plyr like this:

    plyr.setup();

Vimeo is trying to load this url:

    https://player.vimeo.com/video/null?player_id=vimeo-5938&api=1&badge=0&byline=0&portrait=0&title=0

Youtube is giving me the "an error occurred, please try again later" without logging any traffic on the network timeline.

**Comment by frumbert** [comment]
Crap, I'm such an idiot.

**Comment by SamPotts** [comment]
No worries 👍  Out of interest, what was it :)

**Comment by frumbert** [comment]
I'd been following somebody's notes where the user had used the markup `<div data-track-id="GguF5lui57U" data-type="youtube">`, but of course the *actual* data attribute name is `<div data-video-id="GguF5lui57U" data-type="youtube">`. Having a `data-type` but no proper source attribute was confusing the code.
