### ISSUE TITLE
How to get Current time of a playing custom video

### ISSUE THREAD

**Issue by nikitpatel24** [Selz/plyr#292]
Is there any method to get the current playback time of the video

**Comment by SamPotts** [comment]
I'll write a wrapper for this - HTML5 is easy but it'd be good to wrap them all into one API method.

**Comment by amilajack** [comment]
Currently, is there a way to get the progress in seconds?

**Comment by SamPotts** [comment]
Just push version 1.8.8 with a new API method `getCurrentTime` which will return the currentTime in seconds (as a float). This works with all media types.

**Comment by amilajack** [comment]
Real developers code on weekends. Thanks a bunch!

**Comment by a-barbieri** [comment]
Is there any documentation about it?
