### ISSUE TITLE
Fancybox issue with controls

### ISSUE THREAD

**Issue by ptraceur** [Selz/plyr#293]
Hi,
the project I'm working on has a plyr instance video from youtube. When I click a button it shows a hidden popup with the plyr video and it plays normally. If I close the fancybox popup, the video stops and thats what it is suposed to do. But when I open it again the video starts from the beginning(not a problem to me) and when I play it the range input doesn't move at all and the play button svg is always visible. 
When I click it pauses and resumes normally but the progress is always zero. 

This might be a fancybox problem, I'm thinking on "beforeClose" event of fancybox destroy all plyr instances and setup them again when popup opens. Is there a way to achieve this?

Thanks

**Comment by SamPotts** [comment]
There is a destroy method but someone has raised a bug with it with YouTube so I will take a look. 👍

**Comment by SamPotts** [comment]
The `destroy()` method is fixed in v1.9.0 - could you give it a go? Bear in mind there were also several breaking changes so check the [changelog](https://github.com/Selz/plyr/blob/master/changelog.md)
