### ISSUE TITLE
issues with multiple audio players in the playlist

### ISSUE THREAD

**Issue by adrian-preda** [Selz/plyr#297]
I've added custom styles for the progress bar, for both audio and video players in my project.
I have multiple audio/video players in my page. The custom styles apply to all the players in the page, except the audio players in my playlist.

This is the html code for the playlist
```
<ol class="album-songs">
  <li class="epic-song">
    <span class="item-song">V (intro)</span>
    <span class="song-duration pull-right"><span class="plyr-play play-status"></span> 01:26</span>
    <div class="clearfix"></div>
    <audio controls id="song1" class="playlist-song">
      <source src="audio/track01.mp3" type="audio/mp3">
    </audio>
  </li>
  <li class="epic-song">
    <span class="item-song">No Way Out</span>
    <span class="song-duration pull-right"><span class="plyr-play play-status"></span> 02:35</span>
    <div class="clearfix"></div>
    <audio controls id="song2" class="playlist-song">
      <source src="audio/track02.mp3" type="audio/mp3">
    </audio>
  </li>
</ol>
```
I have 9 elements in my list.

This is my js code
```
$('.epic-playlist li').each(function(){
    var audio_element = $(this).find('.playlist-song');
    if (audio_element.length==1) {
      playlist_players.push(
        {
          player: plyr.setup('#' + audio_element.attr('id'), {controls: ['progress'], loadSprite: false })[0].plyr,
          current_song: $(this)
        }
      );
    }
  })

  $('.epic-song').on('click',function(event){
    event.preventDefault();
    var player = playlist_players[$(this).index()];
    var current_song = $(this);
    $.each(playlist_players, function(index, item){
      item.player.pause();
      item.current_song.removeClass('playing');
    })
    player.player.play();
    current_song.addClass('playing');
  })
```

This is how the playlist looks
![Alt text](https://monosnap.com/file/C8SDcDqoFecsRf6L854vk7g7EUaUFl.png)

This is how the progress bar should look
![Alt text](https://monosnap.com/file/sDahaWap2usbHpjIiD55ORm3rUgFJH.png)

I also discovered a strange thing: if I open the developer tools to inspect the list, when I hover over the  elements the default blue progress bar disappears.

**Comment by SamPotts** [comment]
Are you using a SASS or LESS build system and incorporating the source files into this? You'll need to run [autoprefixer](https://www.npmjs.com/package/gulp-autoprefixer) if so. It looks like the `appearance: none` declaration is not prefixed:
https://github.com/Selz/plyr#less--sassscss

**Comment by adrian-preda** [comment]
Hi, Sam
Thank you for the tip, it was very helpful.
My playlist is working just fine now.
Here's what I've done:
![Alt text](https://monosnap.com/file/pUI4UxYJ3ZZDYyU1eqDLP8xsqE7XXk.png)
Thank you again for your help.

**Comment by SamPotts** [comment]
Awesome! 👍
