### ISSUE TITLE
Advertisements showing for youtube video

### ISSUE THREAD

**Issue by knoxcard** [Selz/plyr#299]
How do I add the Youtube ads? Is it possible?  Also, the Youtube logo in the right hand bottom corner?

**Comment by SamPotts** [comment]
Maybe have a look at the YouTube embed docs re: ads. Plyr doesn't do anything special to the embeds themselves, it just provides custom controls and a unified API wrapper over the top. The YouTube logo is already visible at the start of playback. Do you mean add a logo to the controls? We could certainly do that for YouTube and Vimeo and link to the page like they do themselves on their own embeds.
