### ISSUE TITLE
Sometimes not adding <button> and <div class="plyr__controls"> on a modal

### ISSUE THREAD

**Issue by DangerMantis** [Selz/plyr#301]
Any ideas on why this happens?

**Comment by SamPotts** [comment]
Without seeing the whole implementation it's going to be hard to work that one out.

**Comment by DangerMantis** [comment]
It is using vex modal to pop up, do i need to re call the setup onclick into a modal? Its seems sometimes it doesn't fully load those elements to the dom.

**Comment by SamPotts** [comment]
You'd want to call setup once all the markup you want to call the plugin on, is rendered to the page, yeah.  In this case probably a `shown` type callback.
