### ISSUE TITLE
New Vimeo API

### ISSUE THREAD

**Issue by KennedyTedesco** [Selz/plyr#302]
Any plans to take out Froogaloop and start to use the new Vimeo API?

Looks quite consistent to me:

https://github.com/vimeo/player.js

Migration guide:

https://github.com/vimeo/player.js/blob/master/docs/migrate-from-froogaloop.md

Just a thought. 😄

**Comment by SamPotts** [comment]
Oh definitely. I made a custom version of froogaloop (with all the PR bug fixes included) which is loaded when required as part of plyr but this looks even better. 

Will get onto it. 👍

**Comment by luruke** [comment]
Yeah, will be great to use the new API.
I've several problems where using Vimeo, it doesn't fire the ready event.

It seems an old bug of froogaloop, it should be solved with the new API.

**Comment by SamPotts** [comment]
Hey, I just added this in v1.8.11 - could you take a look :)

**Comment by KennedyTedesco** [comment]
That's awesome! Thanks for your time.

**Comment by SamPotts** [comment]
Grab v1.8.12 as I just fixed a couple of other Vimeo issues
