### ISSUE TITLE
Pause on touch in cellphone not work

### ISSUE THREAD

**Issue by ebadgh** [Selz/plyr#303]
I try to pause video by touch on video but i cant do that , so pause video just work when touch on pause button.
In window browser by click on video frame, video paused.

**Comment by SamPotts** [comment]
This is intended. Tapping in the video on a touch device will show the controls. Much like other players do.

**Comment by ebadgh** [comment]
I set options visible (hideControls: false), but touch not work for pause video.

**Comment by SamPotts** [comment]
Sorry, you're right. That is a bug then. I'll check it out.

**Comment by SamPotts** [comment]
Just pushed a fix for this in the latest version 👍
