### ISSUE TITLE
controls not displayed properly on Android 4 (on samsung tablet)

### ISSUE THREAD

**Issue by philhenri** [Selz/plyr#304]
Hi
There seems to be a problem with the "control bar", controls are not displayed properly on Android 4 (on samsung tablet) - see attached screen capture

thanks
regards
philippe
![android-2000-04-19-04-42-41](https://cloud.githubusercontent.com/assets/1751518/16696181/1db92196-4544-11e6-8f82-5ba1736d9c9a.png)

**Comment by SamPotts** [comment]
Probably needs a config change for autoprefixer for it to work. I've restored my test Nexus 5 to 4.4.4 but it comes with Chrome and I presume you're using "Dolphin" (?) or something there?

**Comment by philhenri** [comment]
Hi Sam, thanks for your quick answer. 
I 
![android screen](https://cloud.githubusercontent.com/assets/1751518/16713038/17092dca-469b-11e6-8dd8-d37d47568277.png)
was using the default browser - see screen capture to see the icon as i don't see which one it is in params.
I have now also installed Dolphin and Google Chrome and I see no problem with these browsers. Only on the default one...?
System is android 4.0.4, so " Ice Cream Sandwich" i believe (although i dont see this displayed)... running on a samsung tablet GT P6810,
thanks !
regards
philippe
