### ISSUE TITLE
Help please: IOS: Can somebody tell me how to activate automatic display of captions from youtube video

### ISSUE THREAD

**Issue by philhenri** [Selz/plyr#305]
Hi

Can somebody tell me how to activate automatic display of captions from youtube video (CC)  on IPhone/Ipad
ex: french subtitles from this one (or any other) https://www.youtube.com/watch?v=Ks-_Mh1QhMc

Even with cc_load_policy=1, on Ipad for example, i have to go fullscreen, then click the bottom right icon to activate captions :( not cool
thanks !
philippe

**Comment by SamPotts** [comment]
I'm honestly not sure it's possible. I tried a variety of ways and couldn't get it to work hence hiding the caption option.

**Comment by philhenri** [comment]
Hi Sam
I think it is possible, if you go to youtube.com using safari (not the youtube app) on an iphone, it works just fine...

Also I did some tests with other players and managed with a small modification in your demo source (plyr.io) to get subtitles working on iphone with a mp4 video (see attached screen cap - the screen with black header is iphone fullscreen, on iphone simulator from xcode). With this code (its mixing a mp4 and some subtitles from a yt video): 

<video height="200" width="480" poster="//s3.amazonaws.com/demo.jwplayer.com/html5-report/sintel.jpg" crossorigin="anonymous" controls>
<source src="//s3.amazonaws.com/demo.jwplayer.com/html5-report/sintel.mp4" type="video/mp4">
<track src="http://video.google.com/timedtext?lang=fr&v=apbSsILLh28&name&kind&fmt=vtt" kind="captions" label="Closed Captions" default>
</track>
</video>

however i cannot get this to work with the youtube video?

any idea?
thanks :)
philippe
![screen shot 2016-07-10 at 13 44 07](https://cloud.githubusercontent.com/assets/1751518/16713353/60261b26-46a5-11e6-944a-447d4cedde40.png)
![screen shot 2016-07-10 at 13 45 15](https://cloud.githubusercontent.com/assets/1751518/16713354/626295ae-46a5-11e6-87e1-13cdbc9d64b8.png)

**Comment by SamPotts** [comment]
YouTube.com != YouTube Embed 

They don't expose the same functionality in the embeds as they do in their own players. That's the problem. You can't (or couldn't when I last looked) toggle the captions. You can either set them to be on at the start with `cc_load_policy` but even that seems to yield mixed results. I can take another look but it wasn't possible with YouTube was added initially.

**Comment by philhenri** [comment]
hmm, crazy isnt it, because with a mp4 vid as shown above, it works just fine... :(
