### ISSUE TITLE
Enable keyboard shortcuts

### ISSUE THREAD

**Issue by amilajack** [Selz/plyr#309]
An implementation of standard video shortcuts would be a very nice addition to this project.

I think the most common ones are:

```
'Spacebar' = toggle pause
'F' = fullscreen
```

Is this a welcome addition?

**Comment by SamPotts** [comment]
Yeah for sure, I think someone's requested this before so I'll add it to my list. Should be a quick win 👍

**Comment by SamPotts** [comment]
I've added these in v1.9.0 - could you give it a go? More info here: [shortcuts](https://github.com/Selz/plyr#shortcuts)

Bear in mind there were also several breaking changes so check the [changelog](https://github.com/Selz/plyr/blob/master/changelog.md)

**Comment by amilajack** [comment]
Thanks!

**Comment by amilajack** [comment]
I've just updated and I'm experiencing an issue in my environment: it seems that I need to press `f` twice for it to work. But this could be an issue only on my machine. I'll look into this further and let you know what I find.

**Comment by SamPotts** [comment]
Hmm, which browser? Do you get the same thing on [plyr.io](https://plyr.io) ?

**Comment by amilajack** [comment]
Btw the image for `plyr.io` isnt working:

```
Access to Image at 'https://cdn.selz.com/plyr/1.5/View_From_A_Blue_Moon_Trailer-HD.jpg' from origin 'https://cdn.selz.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://plyr.io' is therefore not allowed access.
```

**Comment by amilajack** [comment]
It works on `plyr.io`. But it only works when the video is focused (when I click on it). If I click on the white background (which unfocuses the video element), and the press `f`, it wont work. Youtube, however, works regardless of where I click. This probably has to do with where the keyPress eventListener is attached?

**Comment by SamPotts** [comment]
Right but how about I have an input on the page and I click "F" while typing something and the video goes full screen?

**Comment by amilajack** [comment]
Ahh right. Maybe something like this:

```
function attachEventListeners() {
  window.addEventListener(() => {
    if ($('input:focus').exists()) {
      return
    }
    plyr.fullscreen()
  })
}
```
?

**Comment by SamPotts** [comment]
Yeah, it would be something like that but I think it'd need to worry about:

- `<input>`
-`<textarea>`
- `[contenteditable]`

basically:

```javacript
if (document.activeElement.matches(/* list of selectors */) { 
    return; 
}
```

I can't think of any other elements that capture input but this would only apply to the`0`-`9`,  `K`, `F`, `C`, `M` shortcuts, the others (space, arrows) would stay focus only as they are used for page navigation.

**Comment by amilajack** [comment]
That's much more elegant. Will this be implement in a near patch release?

**Comment by SamPotts** [comment]
Yeah I'll have a go at this later today and see how I go. I'm just conscious of other events that may capture keyboard input that we need to worry about.

**Comment by amilajack** [comment]
Great, thanks!

**Comment by SamPotts** [comment]
I've just pushed v2.0.2 which has a `global` option for keyboard shortcuts. Check the docs for a small change in the config (it's an object rather than boolean now). It should also fix the issue with having to press `F` twice.

**Comment by amilajack** [comment]
Thanks! Does this also fix the active element issue?

**Comment by SamPotts** [comment]
For now it'll just ignore any global key presses when the active element is an `<input>`, `<select>` or `[contenteditable]` but thinking about it - it needs to do `<textarea>` too. Will add this now.
