### ISSUE TITLE
Save captions state

### ISSUE THREAD

**Issue by alethea** [Selz/plyr#311]
I noticed plyr stores the video volume in local storage to stay consistent between videos/plays of videos. I think the captions on/off state could also benefit from being preserved at the user's preference. I'm happy to make a PR if you think this is worthwhile.

**Comment by SamPotts** [comment]
Yeah that would be a good idea! 👍

**Comment by SamPotts** [comment]
Merged in v1.9.0 - thanks again for this 👍

**Comment by alethea** [comment]
No problem! Thank you!
