### ISSUE TITLE
Multi-line captions

### ISSUE THREAD

**Issue by jvlahos** [Selz/plyr#314]
By using `line-height` and `box-decoration-break: clone`, captions can look better when they break to multiple lines (on small screens, for example). [Box-decoration-break](https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break) ensures the same padding is applied to each broken line (limited support, other approaches [here](https://css-tricks.com/multi-line-padded-text/)).

Happy to contribute a fix for this when I have time but figured I would document it for now.

**Code:**
```css
.plyr__captions span {
  box-decoration-break: clone;
  line-height: 150%;
}
```

### Before
![screen shot 2016-07-18 at 7 21 55 pm](https://cloud.githubusercontent.com/assets/945960/16933603/f66894e2-4d1c-11e6-9bff-6e93683a6fb9.png)

### After
![screen shot 2016-07-18 at 7 22 45 pm](https://cloud.githubusercontent.com/assets/945960/16933629/4cb2306a-4d1d-11e6-810b-aa9678c3744b.png)

**Comment by SamPotts** [comment]
Awesome. Thanks for this. I can add it in the next release and give you the credit for it of course or a PR (remember LESS + SCSS versions), whichever. 👍
