### ISSUE TITLE
restart() and togglePlay not recognized

### ISSUE THREAD

**Issue by framakers** [Selz/plyr#315]
i'm using version v1.8.8 but have problems with using some funtions.
play() and pause() are working wll. But i need the functions restart() and togglePlay()
When using them i recieve the message "Function not found"

**WORKING**
```
var slide = $(".cycle-slide-active");
var plyrDiv = slide.find('.sourceVideo');

if (typeof plyrDiv != 'undefined') {
  plyrDiv[0].play();
}

```
**NOT WORKING**
```
var slide = $(".cycle-slide-active");
var plyrDiv = slide.find('.sourceVideo');

if (typeof plyrDiv != 'undefined') {
  plyrDiv[0].restart();
}

```
Could someone advice me?

**Comment by SamPotts** [comment]
What's the content of `.sourceVideo` ? Is that the `<video>` element? All calls to the API must be using the plyr object/instance. See https://github.com/Selz/plyr#getting-the-plyr-instance

**Comment by framakers** [comment]
**Change sourceVideo to js-player**

`<div class="js-player" data-video-id="{{ youtube }}" data-type="youtube"></div>`

`Setup`
```
                    plyr.setup(document.querySelectorAll('.js-player'), {
                        hideControls: true,
                        autoplay: true,
                        loop: true,
                        fullscreen: {
                            enabled: true,
                            fallback: false
                        }
                    });
```

**workin situation with play**
```
                        var slide = $(".cycle-slide-active");
                        var plyrDiv = slide.find('.js-player');

                        if (typeof plyrDiv != 'undefined') {
                            plyrDiv[0].play();
                        }
```

**not working situation with restart**
```
                        var slide = $(".cycle-slide-active");
                        var plyrDiv = slide.find('.js-player');

                        if (typeof plyrDiv != 'undefined') {
                            plyrDiv[0].restart();
                        }
```

**Comment by SamPotts** [comment]
You're right. There seems to be a bug with restart. Will look into it 👍

**Comment by stitpragya22** [comment]
This is still there I think 
Uncaught TypeError: player.restart is not a function

**Comment by stitpragya22** [comment]
and same for stop() function
using cdn with https://cdn.plyr.io/3.7.3/plyr.polyfilled.js
