### ISSUE TITLE
Keyboard focus on Vimeo video.

### ISSUE THREAD

**Issue by makshh** [Selz/plyr#317]
When you focus on the play button using keyboard, Vimeo controls appears on the player (MacOS, Chrome 51.0.2704.106 (64-bit)). After that, I can press play button, but I can't see video.

![plyr-vimeo](https://cloud.githubusercontent.com/assets/5025950/17041667/e4783142-4fa7-11e6-87e3-c2906b54ee77.jpg)

**Comment by SamPotts** [comment]
Fixed 👍
