### ISSUE TITLE
Vimeo postmessage issue after destroying player

### ISSUE THREAD

**Issue by frumbert** [Selz/plyr#318]
I have a vimeo player which I'm needing to destroy - but vimeo throws an error after the destroy.

`VM289 plyr.froogaloop.js:1 Uncaught TypeError: Cannot read property 'postMessage' of null`

Example:
https://jsfiddle.net/6okm62pf/1/

It consistently throws AFTER the destoy() since the vimeo video is still on the page.

If you remove the `.plyr` node itself right afterwards it seems ok. e.g.

    player_reference.destroy();
    var p = document.querySelector(".plyr");
    p.parentNode.removeChild(p);

but then the function isn't returning the node back to its original state (my case that's ok, but it's not what it says on the tin). :)

**Comment by SamPotts** [comment]
Will take a look at this. I've just upgraded the Vimeo API to their new `player.js` which may help but I need to look at the `destroy()` method anyhow. Thanks for reporting 👍

**Comment by frumbert** [comment]
On 1.8.12 I still have to destroy the actual plyr instance in order to make the video dissapear. If I then create a new instance, I get an uncaught typeerror - cannot set property 'embed' of undefined.

Example:
https://jsfiddle.net/6okm62pf/4/

1. Just run it and click destroy - the video temporarily goes away then comes back (Vimeo video seems to be calling back and recreating itself).
2. Click Destroy & RemoveChild - everything looks fine, no errors
3. Now click Create - you get the set property error, and plyr ins't properly set up.

I realise that if i'm changing source then I should be using `player.source` and giving it its new sources - but I can't make that work once/if the existing player is destroyed - https://jsfiddle.net/6okm62pf/7/ (clicking Create without first destroying the player still works)

**Comment by SamPotts** [comment]
I'm looking at this now along with trying to clean up the object references a little more. Will be re-writing `.destroy()` as I think it's been forgotten a long the way and should be used by `.source()` anyway as a lot of the code is replicated.

**Comment by Slgoetz** [comment]
Any solutions here?  I am having the exact same problem.  I am unloading the element on an Ajax page load then re-load in a video element only to get that same error. 
`cannot set property 'embed' of undefined.`

**Comment by SamPotts** [comment]
Really sorry - I am working on it. Hoping I can get a fix out for this, plus a load of other issues this weekend. Have you tried the `.source()` method for updating instead of destroying and starting over?

**Comment by SamPotts** [comment]
This should be fixed in v1.9.0 - could you give it a go? Bear in mind there were also several breaking changes so check the [changelog](https://github.com/Selz/plyr/blob/master/changelog.md)
