### ISSUE TITLE
Support for Array as selector in .setup()

### ISSUE THREAD

**Issue by electerious** [Selz/plyr#319]
`plyr.setup()` currently supports NodeList, HTMLElement and a string selector, but sometimes it's easier to work with Arrays instead of NodeLists. Especially when performing a lot of filtering using `.map`, `.filter`, ….

Passing an array to `plyr.setup()` doesn't throw an error and simply uses the default values: `<video>`, `<audio>` and `[data-type]`.

Supporting Arrays like `[HTMLElement, HTMLElement]` would be a nice addition.

**Comment by SamPotts** [comment]
Just added this - could you give it a test? 👍

**Comment by electerious** [comment]
Thanks a lot for the implementation! Made a [small documentation for it](https://github.com/Selz/plyr/pull/321) and will try it out next week.

**Comment by electerious** [comment]
Tested. Works perfectly!

**Comment by SamPotts** [comment]
Awesome 👍  Cheers for the docs update too.
