### ISSUE TITLE
YT not defined error

### ISSUE THREAD

**Issue by dlewand691** [Selz/plyr#320]
Just upgraded to the newest version and in the console getting this error:

```app-min.js:2435 Uncaught ReferenceError: YT is not defined```

Looks like it might be in this section of the code:
```
L.object(YT)?Z(r,n):(a(k.urls.youtube.api),e.onYouTubeReadyCallbacks=e.onYouTubeReadyCallbacks||[],
```

Thoughts on how to fix? Will have to downgrade until it's resolved. Rolled back to 1.8.8.

Running a Mac and processing code with Codekit.

**Comment by SamPotts** [comment]
Sorry about that - it was my new type checking method at fault. All good in v1.8.11
