### ISSUE TITLE
Closed caption text is not visible in Firefox browser

### ISSUE THREAD

**Issue by dineshb-qa** [Selz/plyr#323]
**Steps to Reproduce**

1. Hit the URL : https://plyr.io/ in Firefox & Chrome browser
2. Play the video
3. Observe that : In Firefox browser the closed caption text is not visible even when the option is on. But in the Chrome browser closed caption text is visible

**Expected Results** : 
Closed caption text should be visible in Firefox browser

**Actual Results** :
Closed caption text is not visible in Firefox browser

**Configuration Manifesting** :
- Win 8, FF 47
- Win 7, FF 47 

**Notes** :
See the attached screen shot : 
![cc_text_not_visible_for_ff_browser](https://cloud.githubusercontent.com/assets/6957604/17296890/ee31c622-5820-11e6-8caf-a3345d746d56.png)

**Comment by SamPotts** [comment]
This should be fixed in v1.9.0 - could you give it a go? Bear in mind there were also several breaking changes so check the [changelog](https://github.com/Selz/plyr/blob/master/changelog.md)

**Comment by dineshb-qa** [comment]
Hi @SamPotts ,

Yes, I checked the issue is no longer reproducible now. The cc text is now visible during video playback in Firefox browser

**Configuration Tested** :
- Win 8, FF 47
- Win 7, FF 47

**Content Tested** : https://plyr.io/

**Notes** :
See the attached screen shot : cc_text_visible_for_ff_browser_22aug.png
![cc_text_visible_for_ff_browser_22aug](https://cloud.githubusercontent.com/assets/6957604/17857673/4f23ff2e-68a0-11e6-8e42-999fafa936c6.png)
