### ISSUE TITLE
How do I pause all active players on a page? 

### ISSUE THREAD

**Issue by joshuapease** [Selz/plyr#324]
I'm trying to access all Plyr instances on a page. 

When I call `plyr.setup('.js-player')` for the first time, I have access to a list of elements that have the `plyr` object assigned to them. 

However, if I call `plyr.setup('.js-player')` again (New players & content are being added via AJAX), the `plyr` object is set to `false`

See example screencap below. 

Is there a better way to access all plyr instances on a page? 

![image](https://cloud.githubusercontent.com/assets/2145998/17376387/2d771a5e-596a-11e6-8fa8-386ed47f1961.png)

**Comment by SamPotts** [comment]
Hey @joshuapease , I've just pushed v1.9.0 which has a new global method to get all instances on a page. You can now do `plyr.get()` and it will return an array of all instances on that page as an array that you can look though and call .pause() on each one. 

Bear in mind there were also several breaking changes so check the [changelog](https://github.com/Selz/plyr/blob/master/changelog.md)

**Comment by Extracreative** [comment]
plyr.get().forEach(function(instance) {
    instance.pause();
  });

**Comment by chovy** [comment]
window.plyr is undefined for me.
