### ISSUE TITLE
How do you wire correctly the events after changing .source? (sources:)

### ISSUE THREAD

**Issue by AlGantori** [Selz/plyr#327]
Hi Sam, day2....
here is the plunker https://plnkr.co/edit/mS0C4C6njYHTurQcij8i?p=preview

you can verify in the console output (Windows/Chrome) the wired events like PLAYING / PAUSED are working when you press on the "Toggle Play" button.  However, this is working only for the inline/html specified youtube VideoID, **the moment I change the video via .source{ } the listeners are LOST** :)
The .play(), .pause(), togglePlay() methods continue to operate correctly, just the events don't fire anymore.
You may use the provided "Play Video 1" and "Play Video 2" buttons to change .source().

Can anyone help, I am tired beating my head on what should be an obvious API sample code.

My current reasoning and logical steps about this player are:
1) subscribe for 'setup' event on the plyr HTML element
2) call the plyr.setup(...) according to the API
3) get notified the plyr is indeed "setup", then wire the desired events
4) set .source() for a single video or a playlist
5) get notified player is "ready" to play, then play the son of gun video!

Where am I erring?

Thank you.
BTW. event 'setup' is not listed in the table [(https://github.com/selz/plyr#events)] but it's working in my testing and 'ready' does not seem to fire for me???

**Comment by SamPotts** [comment]
Please see v1.9.0 - I've added an `.on()` API method which should help you. 

Bear in mind there were also several breaking changes so check the [changelog](https://github.com/Selz/plyr/blob/master/changelog.md)
