### ISSUE TITLE
Plyr does not react to "native" events

### ISSUE THREAD

**Issue by mkrogh** [Selz/plyr#34]
In chrome when right-clicking on the video you can use the native html5 player controls to pause, mute. This is a good ting, but plyr does not reflect the changes. 

If you pause the player via native plyr will still show the video as playing (Pause icon). When you click the plyr pause icon the video remains paused, and you have to click one more time to trigger playback again.

Observed in Chrome and Firefox on OSX.

**Comment by SamPotts** [comment]
Thanks for this. I'll fix this tomorrow.

**Comment by mkrogh** [comment]
Nice, thanks it looks nice otherwise :+1:

**Comment by SamPotts** [comment]
Let me know if you run into any more issues :+1: 

Cheers!
