### ISSUE TITLE
Introducing breaking changes from 1.8 to 1.9?

### ISSUE THREAD

**Issue by r3oath** [Selz/plyr#342]
http://semver.org/

> In systems with many dependencies, releasing new package versions can quickly become a nightmare. If the dependency specifications are too tight, you are in danger of version lock (the inability to upgrade a package without having to release new versions of every dependent package). If dependencies are specified too loosely, you will inevitably be bitten by version promiscuity (assuming compatibility with more future versions than is reasonable). Dependency hell is where you are when version lock and/or version promiscuity prevent you from easily and safely moving your project forward.

**Comment by SamPotts** [comment]
I'm aware of semver, thanks. I did consider a v2.0.0 but as they are *potentially* breaking changes and didn't think it warranted a "major" release. Sorry if it tripped you up. Always check the changelog.

**Comment by r3oath** [comment]
I don't necessarily think "major" is necessarily considered major in the common use of the word. If you've got potentially breaking changes, then those are still BC's, which should warrant a major version increment. Otherwise it will trip people up, for instance as part of a deployment script you may automatically update you NPM dependencies, and if everyone followed semver that could be done with reasonable confidence you're not going to hose your release.

**Comment by SamPotts** [comment]
Right, will bump to v2.0.0

**Comment by r3oath** [comment]
Awesome 👍 
Just keep in mind it'll still trip people up who automatically get bumped to 1.9 though.

**Comment by SamPotts** [comment]
Aware of that - if you blindly update without testing then you've got bigger problems :)

**Comment by r3oath** [comment]
Completely agree! - Hence this issue thread, which started as a result of tests failing.

**Comment by SamPotts** [comment]
Ah sorry for the extra work. Annoyingly NPM doesn't allow me to remove a version.

**Comment by r3oath** [comment]
Yeah it's a bit annoying, I've made the mistake in the past of pushing an unwanted tag and they just force you to live with it. These days I just triple check everything before an `npm publish`.

**Comment by SamPotts** [comment]
Will do in future - sorry for the inconvenience 👍
