### ISSUE TITLE
The player does not takes the entire screen when we go to full screen mode in Firefox browser

### ISSUE THREAD

**Issue by dineshb-qa** [Selz/plyr#343]
**Steps to Reproduce**

1. Hit the URL : https://plyr.io/ in Firefox & Chrome browser
2. Click on the 'Full Screen' icon
3. Observe that : The player does not takes the entire screen when we go to full screen mode in Firefox browser as compare to Chrome browser
4. This behavior is observed for all 3 players (Video, YoutTube, Vimeo) in Firefox browser  

**Expected Results** : 
The player should take the entire screen when we go to full screen mode in Firefox browser same like Chrome browser

**Actual Results** :
The player does not takes the entire screen when we go to full screen mode in Firefox browser

**Content Manifesting** : https://plyr.io/#vimeo

**Configuration Manifesting** :
- Win 8, FF 47
- Win 8, Chrome 52
- Win 7, FF 47 

**Notes** :
See the attached screen shot : video_does_not_goes_to_full_screen_mode_in_ff_22aug.png
![video_does_not_goes_to_full_screen_mode_in_ff_22aug](https://cloud.githubusercontent.com/assets/6957604/17858054/cd1820bc-68a1-11e6-9abc-4756b7475277.png)

**Comment by SamPotts** [comment]
Just pushed a fix 👍
