### ISSUE TITLE
Support all embed URLs dynamically

### ISSUE THREAD

**Issue by lastmjs** [Selz/plyr#345]
This idea would work well especially if this library were a web component, like mentioned [here](https://github.com/Selz/plyr/issues/344). I'm trying to support a video player where I don't know until runtime which type of URL is going to be inserted into the player. I'm going to have to do all of the logic myself, parsing the URLs to see if they are from YouTube, Vimeo, or just a plain file, and then I'll have to extract the ids. It would be great if the player supported any URL, for example:

```
<plyr-element src="https://vimeo.com/179671273"></plyr-element>
```

or 

```
<plyr-element src="https://www.youtube.com/watch?v=S1ql2eNo2BY"></plyr-element>
```

Both of the above would work, and all of the logic would be contained inside of the component.

**Comment by SamPotts** [comment]
Good idea and should be pretty straight forward with a bit of Regex. I think even the Vimeo new API will parse a URL anyway. I'll give it a go. Cheers 👍

**Comment by lastmjs** [comment]
In the mean time, I'm actually using this: https://github.com/Zod-/jsVideoUrlParser
Might help if you don't want to deal with all of the work yourself.

**Comment by SamPotts** [comment]
@gurupras has done a PR for this and I've just modified it slightly to support Vimeo also. Will be pushing to master shortly and deploy 2.0.10 👍

**Comment by SamPotts** [comment]
Added in v2.0.10:
https://github.com/Selz/plyr/releases/tag/v2.0.10 👍
