### ISSUE TITLE
Standard way to access the volume and muted

### ISSUE THREAD

**Issue by lastmjs** [Selz/plyr#346]
Just like `getCurrentTime()`, it would be nice to have something like `getCurrentVolume()`, and also `getMuted()`, these are both things that I have a use case for.

**Comment by SamPotts** [comment]
Cool. Will add this in, cheers 👍

**Comment by SamPotts** [comment]
Hey @lastmjs - I've added in `getVolume()` and `isMuted()` API methods 👍
