### ISSUE TITLE
Play button not perfect round in Firefox

### ISSUE THREAD

**Issue by Jeffwhen** [Selz/plyr#347]
I use plyr to build my video demo, here's my .html file
```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Video Demo</title>
    <link rel="stylesheet" 
          href="http://192.168.1.229/resource/bower_components/plyr/dist/plyr.css">
  </head>
  <body>
    <main style="box-sizing: border-box">
    <section style="max-width: 1200px">
    <video controls crossorigin>
      <source src="Suit.N.Tie.mp4" type="video/mp4">
    </video>
    </section>
    </main>
    <script src="http://192.168.1.229/resource/bower_components/plyr/dist/plyr.js"></script>
    <script>plyr.setup()</script>
  </body>
</html>
```
Everything goes pretty well, except the play button. It's a oval in Firefox, but works fine in Chrome. Here's how it looks like.
![screen shot](http://i1.buimg.com/4851/01c759f87dd4bfa8.png)
BTW, the [plyr.io](http://plyr.io) demo looks okay in my exact same Firefox browser.

**Comment by SamPotts** [comment]
Firefox seems to be causing all sorts of issues recently. I'll take a look. Strangely it's fine on Chrome, etc.

**Comment by SamPotts** [comment]
This seems to be fine now - perhaps it was a Firefox bug before.
