### ISSUE TITLE
IE10- fails for Vimeo embed

### ISSUE THREAD

**Issue by danicholls** [Selz/plyr#348]
It seems that in IE10 the script does not actually set up the `iframe`, but does set up controls. It also seems to bump down the player for whatever reason (maybe resolved if it finishes loading).

IE9- doesn't get that far, just two `div`s deep (visually a black box).

## Vanilla setup
```html
<!doctype html>
<html>
    <title>Preview</title>
    <link rel="stylesheet" href="plyr/plyr.css" />
</head>
<body>

<div data-type="vimeo" data-video-id="143418951"></div>

<script src="plyr/plyr.js"></script>
<script>

    plyr.setup();

</script>

</body>
</html>
```

*Note: results below are real IE9/10, via Browserstack.*

## Result - IE10
![ie10](https://cloud.githubusercontent.com/assets/5094893/17970062/d14387f0-6a89-11e6-8e93-d53ed10a0560.png)

## Result - IE9
![ie9](https://cloud.githubusercontent.com/assets/5094893/17970152/2a593416-6a8a-11e6-871a-f8759c156ea5.png)

**Comment by danicholls** [comment]
Should say: I didn't really expect IE9 to work, at least like the others. The docs say it'll use the native player, but I'm not sure what that'd mean in this case.

**Comment by danicholls** [comment]
Oh, and I tried using 1.8.12, but it was still there.

**Comment by danicholls** [comment]
I tested, and `plyr.supported("video")` returns true for both basic and full for IE10, and true for basic and false for full for IE9.

**Comment by SamPotts** [comment]
This should be fixed now 👍 

Instead of passing an ID to the Vimeo constructor, I passed the HTMLElement instead which seemed to fix it in IE10. Let me know how you go.
