### ISSUE TITLE
HTML5 instance ready event does not fire

### ISSUE THREAD

**Issue by lastmjs** [Selz/plyr#349]
It took me a little while to figure out why my HTML5 video was not firing a ready event. I finally found the answer in the README, where it says that it is ready instantly. It would be nice though for consistency to still fire the event. I was getting pretty confused as to why the YouTube and Vimeo players' ready events were firing and not the HTML5 players'.

**Comment by SamPotts** [comment]
It should fire now - I worked out a way to get it to fire 👍
