### ISSUE TITLE
requires docs.js

### ISSUE THREAD

**Issue by chrismccoy** [Selz/plyr#35]
player doesnt work without the javascript docs.js, anyway around this?

**Comment by SamPotts** [comment]
Hey there,

`docs.js` just contains the demo code to setup the player. If you don't call the `setup` method then it won't work- this is where you pass any custom options to plyr. The section below in `docs.js` which calls the setup method. The only required parameter is `html` but if you read the docs you can find out more about how it all works. 

```javascript
plyr.setup({
	debug: 	true,
	title: 	        "Video demo",
	html: 	templates.controls.render({}),
	captions: {
		defaultActive: true
	}
});
```

**Comment by chrismccoy** [comment]
says templates is undefined, i think its looking for hogan?

**Comment by SamPotts** [comment]
Might be worth having a read of [controls.md](controls.md) and the general docs [readme.md](readme.md). You don't have to use Hogan.
