### ISSUE TITLE
SubRip Text (srt) support

### ISSUE THREAD

**Issue by kaatt** [Selz/plyr#355]
Can you add support for `.srt` files? As an optional plugin perhaps?

I tried to use http://captionatorjs.com but it didn't work, dunno why.

**Comment by calvintam236** [comment]
You are trying to use `.srt` file in `<track src="">`? HTML5 specification does not support subtitle format other than webvtt, so you need a webvtt format subtitle for the `src`. You can convert it on server or use a data URI with Javascript in `src`.

My solution to convert `.srt`, `.ass`, `.ass` to webvtt format by JS: https://github.com/calvintam236/webvtt-subtitler

**Comment by SamPotts** [comment]
VTT is the web standard for captions. As above you might be best off converting them before hand.

**Comment by glowinthedark** [comment]
yet another way to convert `.srt` to `.vtt`:

```bash
ffmpeg -i subs.srt subs.vtt
```
