### ISSUE TITLE
chainable .on() method ?

### ISSUE THREAD

**Issue by frumbert** [Selz/plyr#357]
I'd like to chain my _on_ methods.

    var player = plyr.setup()[0];
    player.on("ready", function(event) {
       console.log(event.detail.plyr.getDuration());
    }).on("timeupdate", function (event) {
       console.log(event.detail.plyr.getCurrentTime();
    }).on("pause"), function (etc) {
     ...
     });

Is that a thing?

**Comment by SamPotts** [comment]
Good idea - I'll add this to my ToDo. 

For now you could do this which I know is not ideal...

```javascript
player.on('ready timeupdate pause', function(event) { 
    switch(event.type) {
        case 'ready':
            console.log(event.detail.plyr.getDuration());
            break;
        case 'timeupdate':
            console.log(event.detail.plyr.getCurrentTime();
            break;
        case 'pause'
            something();
            break;
    }
});
```
