### ISSUE TITLE
EDGE: YouTube not emiting pause events properly (2.0.6)

### ISSUE THREAD

**Issue by frumbert** [Selz/plyr#358]
https://jsfiddle.net/6dnc964g/

I'm finding that the `pause` event is buggy under Edge (20.10240.16385.0). You can start playback and you get the `play` event. You can then press pause _once_ and you get the `pause` event. Hitting `play` again gives you the play event - so far so good. But from this point on you do not get any more `pause` events emitted, even after the video has ended and played again. Once paused, Youtube now shows its spinner all the time, even with the video playing.

On another test locally I was occasionally getting a huge queue of `pause` events as the video ended; that is, I could play/pause and see the `play` event only being emitted, but as the `ended` event occurred, immediately prior to that would be all of the `pause` events.

Seems to affect YouTube only.

**Comment by SamPotts** [comment]
Could you give this another go on the latest version? I'm not seeing it on https://plyr.io? Feel free to re-open if still an issue.

**Comment by SamPotts** [comment]
I was testing on Microsoft Edge 38.14393.0.0
