### ISSUE TITLE
YouTube duration is sometimes displayed incorrectly

### ISSUE THREAD

**Issue by dineshb-qa** [Selz/plyr#362]
**Steps to Reproduce**
1. Hit the URL : https://plyr.io/#youtube
2. Click on the 'Play' button and wait for video playback to complete
3. Observe that : The progress bar for YouTube player does not spans/fill entire bar when video ends as compare to 'Video Player' and 'Vimeo Player'

**Expected Results** : 
The progress bar for YouTube player should spans/fill entire bar when video ends like 'Video Player' and 'Vimeo Player'

**Actual Results** :
The progress bar for YouTube player does not spans/fill entire bar when video ends

**Content Manifesting** : https://plyr.io/#youtube

**Configuration Manifesting** 
- OS X 10.11, Chrome 52

**Notes** :
See the attached screen shot : 
![progress_bar_does_not_spans_entire_space](https://cloud.githubusercontent.com/assets/6957604/18226087/40bcfa56-7220-11e6-8ec7-48f8ae980add.png)

**Comment by mavo11** [comment]
That's because the duration of plyr's progress bar is one second above the real duration.

**plyr.js - line 2036**
`if (plyr.media.duration !== null && !isNaN(plyr.media.duration)) {
    mediaDuration = plyr.media.duration;
}`

**has to be**
`if (plyr.media.duration !== null && !isNaN(plyr.media.duration)) {
    mediaDuration = plyr.media.duration - 1;
}`

after that fix everything works.

**Comment by SamPotts** [comment]
What's the logic behind that? It'd also break HTML5. If the duration is reported to be 10 seconds then how should be 9 seconds?

**Comment by mavo11** [comment]
You are the project owner. I just tell the guys how to fix the problem with youtube embeded videos.

If you embed a Youtube-Video with an duration of 20 seconds, your player 's progress bar shows us 21 seconds. 
Because of that issue the progress bar never moves to end. (see Screenshot)

Now it's your turn.

**Comment by SamPotts** [comment]
It's not a robust solution is my point though. It might work for this scenario but it's more likely a rounding issue. Plyr just uses the value that is provided through the YouTube API:
https://github.com/Selz/plyr/blob/master/src/js/plyr.js#L1658
 
It's an open source repository, anyone can contribute with working, tested code. I don't have any problems with that. I don't have time to look at and fix every issue with the plugin. I have a full time job also 👍

**Comment by SamPotts** [comment]
OK, so I had a quick dig into this and I suspect the API is at fault here. Here's the demo video on YouTube's main site (showing 3:03 duration):
https://www.youtube.com/watch?v=bTqVqk7FSmY

And here's it in the iframe mode:
https://www.youtube.com/embed/bTqVqk7FSmY
Notice it initially shows 3:04 (as reported by the API) and then flicks to 3:03. 

I'll see if the API changes the duration after play too and update the calcs then. I'll raise this as a bug to Google/YouTube.

**Comment by SamPotts** [comment]
I've raised this as a bug with YouTube:
https://code.google.com/p/gdata-issues/issues/detail?id=8690

I've also found a fix. I will re-check the duration after play has begun. Not ideal but all we can do with the bug in their API.

**Comment by SamPotts** [comment]
Pushed a temporary fix (until YouTube fixes the API) in v2.0.9

**Comment by SamPotts** [comment]
Fixed in v2.0.10:
https://github.com/Selz/plyr/releases/tag/v2.0.10
