### ISSUE TITLE
Can someone make a tutorial on how to customize the look?

### ISSUE THREAD

**Issue by bigdaddy1457** [Selz/plyr#363]
please ...can someone make a tutorial on customizing the look of the player, it is hard for us, the bigginers...

**Comment by SamPotts** [comment]
It doesn't use anything other than standard HTML and CSS (or LESS). If you need any more info one how LESS and SASS work, see their docs:

- [LESS](http://lesscss.org/)
- [SASS](http://sass-lang.com/)

And if you need more basic help, try [Treehouse](https://teamtreehouse.com/)
