### ISSUE TITLE
Autoplay Certain Videos

### ISSUE THREAD

**Issue by dacheezypuffs** [Selz/plyr#367]
Hey,

Is there currently a way to autoplay certain YouTube videos from initializing them? Currently I have two JavaScript setups and it's causing neither of them to work.

**Comment by frumbert** [comment]
can you not seek then play, to put the player into a playable state?

	_instance.on("ready", function (event) {
			event.detail.plyr.seek(0);
			event.detail.plyr.play();
	});

**Comment by dacheezypuffs** [comment]
I figured out the problem. It was a syntax error on my behalf. My bad, should've looked more carefully.  I had to remove something from argument 0 even though I saw it somewhere in the docs I believe. It's been a long day.
