### ISSUE TITLE
CORS in Youtube error

### ISSUE THREAD

**Issue by SaadeMotion** [Selz/plyr#369]
Hi!

I'm getting console error:

`www-widgetapi.js:100 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://localhost:8000').
`

any idea how to fix?

**Comment by SamPotts** [comment]
This one can be ignored. Or perhaps raise the bug with the YouTube team. We're using their API as-is.

**Comment by SaadeMotion** [comment]
OH! Thanks! I hate console errors, i think i have "TOC" hahaha,

**Comment by SamPotts** [comment]
It's understandable and I'm the same really. It's just not in my control. I'll have another look but as I say, we just use the API as per their examples :(

**Comment by SaadeMotion** [comment]
Nevermind :) Thanks for this wonderful plugin, soon you'll see it on a GIANT Project 👅!
