### ISSUE TITLE
For YouTube player the video length shown as '03:04' on start screen and actual video length is '03:03'

### ISSUE THREAD

**Issue by dineshb-qa** [Selz/plyr#374]
**Steps to Reproduce**

1. Hit the URL : https://plyr.io/#youtube
2. Observe that :  For YouTube player the video length shown as '03:04' on start screen and actual video length is '03:03' as compare to 'Video Player' and 'Vimeo Player'
3. When video playback completes then YouTube player shows video length as '03:03' on end screen same like 'Video Player' and 'Vimeo Player'

**Expected Results** : 
For YouTube player the video length should be shown as '03:03' on start screen same like 'Video Player' and 'Vimeo Player'

**Actual Results** :
For YouTube player the video length shown as '03:04' on start screen and actual video length is '03:03'

**Content Manifesting** : https://plyr.io/#youtube

**Configuration Manifesting** 
- Win 8, Chrome 53

**Notes** :
See the attached screen shot : 
![incorrect_video_length_for_youtube](https://cloud.githubusercontent.com/assets/6957604/18712625/f0364356-802c-11e6-9c03-01c4a4f5e45e.png)

**Comment by SamPotts** [comment]
Thanks for this - I'll take a look. I suspect it's a rounding issue.

**Comment by SamPotts** [comment]
This is related to #362 so will manage both there
