### ISSUE TITLE
Support WebVTT with CRLF or LF Line separator with firefox

### ISSUE THREAD

**Issue by magourex** [Selz/plyr#378]
My webVTT file contain CRLF line terminator.
Captions display in Chromium but not in firefox 48.

According to the webvtt spec line terminator consists of one of the following CRLF (U+000D U+000A), LF (U+000A) or CR (U+000D)
Plyr.js is compatible with only LF (\n) line terminator

I will make pull request for this issue
[test-vtt2.txt](https://github.com/Selz/plyr/files/494989/test-vtt2.txt)

**Comment by SamPotts** [comment]
Thanks - will take a look at the PR
