### ISSUE TITLE
Fullscreen doesn't work on firefox 35

### ISSUE THREAD

**Issue by Psycojoker** [Selz/plyr#38]
Hello,

I'm not able to make plyr go fullscreen on firefox 35 (even on the demo page). The web debugging console doesn't show any error. I've tested it on a firefox with a totally new clean profile so extensions can't get in the way.

Cheers,

**Comment by SamPotts** [comment]
Thanks for reporting. I'll look at this now.

**Comment by SamPotts** [comment]
This should be fixed now. Thanks for reporting. Let me know if you find anything else! :+1:

**Comment by Psycojoker** [comment]
Works like a charm, thanks for your very fast fix :)

**Comment by terraconnect** [comment]
I am afraid it is still not working on Firefox 38 on PC.

**Comment by SamPotts** [comment]
Hey @terraconnect , sorry about that. Of course, each browser has their own and generally inconsistent implementation of the fullscreen API, some using `FullScreen` and some `Fullscreen` and then of course there's good old Microsoft who feel sometimes they should prefix with `ms` and sometimes `MS`. Sterling work.  

Thanks for reporting it :+1:

**Comment by terraconnect** [comment]
Hi Sam!
And thank you very much for fixing the issue so quickly.
Works perfectly now.

I fully understand the issues of compatibility as well.
Indeed, I experienced that Safari seems to be the new Internet Explorer...  ;)

Have a nice weekend.

**Comment by SamPotts** [comment]
Safari certainly has it's quirks. A recent one that's been frustrating is `(1000).toLocaleString()` which should return `1,000` in most browsers when set to English language and `1.000` or `1 000` in some other languages. Of course Safari just returns `1000` so it's hard to get the thousand group separator for the users locale in Safari.

**Comment by terraconnect** [comment]
Ahahah!

Another example is the fullscreen video in Safari that was letting site's header above it. Don't know if it is coming from plyr but I tried every possible value of z-index with no luck. Finally, I had to hide elements during fullscreen playback.
