### ISSUE TITLE
e.Vimeo.Player is not a constructor

### ISSUE THREAD

**Issue by sepson** [Selz/plyr#380]
I got this error in the console:
plyr.js:1 Uncaught TypeError: e.Vimeo.Player is not a constructor

`<div data-type="vimeo" data-video-id="183364240"></div>`

**Comment by SamPotts** [comment]
Do you see this on https://plyr.io too? 

What browser?

**Comment by sepson** [comment]
Thanks for the fast answer!
Sorry, I got it.. my server changed the encoding.

And thanks for that nice player!
