### ISSUE TITLE
vimeo is kinda broken

### ISSUE THREAD

**Issue by okeniiawak** [Selz/plyr#381]
I get this when I simply adding:

<div data-type="vimeo" data-video-id="143418951"></div>

it loads vimeo at half the height and also plyr making it look like this: (see attached)

![45b8a944cdd34b431171a317b5638f63](https://cloud.githubusercontent.com/assets/18264973/18909505/bee7b098-856b-11e6-95b9-18737c40fe40.png)

**Comment by SamPotts** [comment]
Weird. Is it the same for you here? https://plyr.io/#vimeo

**Comment by okeniiawak** [comment]
no, in the demo it works fine. the thing is youtube works fine and i use same code except i change the div data attributes from youtube to vimeo. It doesn't seem I do anything different. For some reason it loads both players and halves it. Might be something stupid to be honest. Not the highest priority, I'll post a reply if I find out anything.

**Comment by okeniiawak** [comment]
I found the problem:

css below causing issue for vimeo only:

.plyr, .plyr .plyr__video-embed iframe {
    max-height: 100vh;
}

i looked at issue #372 which solved a problem with iframe ratio but this messes up vimeo only.

**Comment by SamPotts** [comment]
Closing this for now. If you're still having issues, let me know and re-open. I suspect this is other CSS effecting it.
