### ISSUE TITLE
Youtube: double icon player

### ISSUE THREAD

**Issue by tanvan81** [Selz/plyr#386]
At this time, I use youtube, the player show double icon
![img](https://cloud.githubusercontent.com/assets/16954677/18978477/b699661a-86ed-11e6-9f8f-00b0886d0deb.png)

on https://plyr.io/#youtube

still error

**Comment by SamPotts** [comment]
Yep - contact Google/YouTube if you'd like this removed (there's no flag to hide it with the API) or write some custom LESS/SASS/CSS to make the play button bigger. Up to you. 

This won't be fixed.

**Comment by tanvan81** [comment]
tks

**Comment by sparkktv** [comment]
Put this in your Custom CSS...

.plyr__play-large{padding:15px;}
.plyr__play-large svg{width:40px;height:40px;}

Fixes the issue and just covers the black icon...
