### ISSUE TITLE
fullscreen / captions size /Android 6

### ISSUE THREAD

**Issue by ericleroy01** [Selz/plyr#390]
in css styles, you set captions size to 32px in fullscreen display
.plyr--fullscreen-active .plyr__captions{font-size:32px}

Rendering is awfull on android 6

**Comment by SamPotts** [comment]
Glad you like the plugin. Thanks 👍 

I'll take a look at the "awful" rendering. Have you heard of a pull request? This is open source, feel free to contribute.
