### ISSUE TITLE
play buttons not hiding/changing on Firefox

### ISSUE THREAD

**Issue by bouks** [Selz/plyr#394]
On Firefox, when start playing youtube video:

- centered play button don't hide
- play control button not changing to pause button

This bug is visible on the demo.
Working well on Chrome and Edge.

**Comment by SamPotts** [comment]
Looks ok to me on Firefox 49 on OS X. Which version and platform are you on. This issue is likely due to something interfering with `window.postMessage` that the YouTube API depends on for communication.

**Comment by bouks** [comment]
Thank you for explanation.

I de-activate "youtube high definition" firefox plugin and all is right, now.

But i never had this problem with youtube videos anywhere...

**Comment by SamPotts** [comment]
Maybe contact the plugin author. It will break other embeds. Plyr doesn't do anything different in terms of YouTube embeds. It uses the YouTube API which uses `window.postMessage` - if your plugin breaks that, it will break other embeds that use the API.
