### ISSUE TITLE
Vimeo video not playing

### ISSUE THREAD

**Issue by KhubaibQaiser** [Selz/plyr#396]
I am using vimeo video like this: 
`<div data-type="vimeo" data-video-id="187175030"></div>`
The console shows this error and when i try to press the play button nothing happens.

> 187175030:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

Youtube video is working fine.

**Comment by SamPotts** [comment]
Does the video play? Or are you just worried about the console message? That's a Chrome bug and nothing to worry about.

**Comment by KhubaibQaiser** [comment]
I wrote that in my post that when i press play button nothing happens. The controls are still visible and video doesnt start.

**Comment by SamPotts** [comment]
Ah, you edited 👍 I saw the message below. Anyway, does the demo at http://plyr.io work for you? If so check the video you're embedding can actually be embedded?

> I am using vimeo video like this: 
> <div data-type="vimeo" data-video-id="187175030"></div>
> The problem is that the console shows this error:
> 
> 187175030:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
> 
> Youtube video is working fine.

**Comment by KhubaibQaiser** [comment]
Nope. Example video is not working either.

**Comment by SamPotts** [comment]
What browser?

**Comment by KhubaibQaiser** [comment]
Chrome Version 53.0.2785.143 m

**Comment by KhubaibQaiser** [comment]
I am using this video: https://vimeo.com/187175030
I hope it can be embedded.

**Comment by KhubaibQaiser** [comment]
One more issue, the vimeo player is not working on mobile. May be its not receiving touch events.

**Comment by fablife** [comment]
I have this issue as well. Doesn't play con chromium and chrome, same error message. But it DOES play on a firefox.

**Comment by SamPotts** [comment]
Chrome version 53, which OS? I'm struggling to replicate this.

**Comment by dineshb-qa** [comment]
Hi @SamPotts ,

Today i observed that the Vimeo video is not playing on demo link : https://plyr.io/#vimeo

Able to see following errors in console (see the attached screen shot)

*Configuration Tested*
* Win 8, Chrome 58
* Win 8, Firefox 53
![video_playback_error_28apr](https://cloud.githubusercontent.com/assets/6957604/25534078/5f612834-2c50-11e7-8bf7-1ac4cdd87c97.png)

**Comment by SamPotts** [comment]
Yep - will fix that. Cheers @dineshb-qa
