### ISSUE TITLE
SASS Support

### ISSUE THREAD

**Issue by brunowego** [Selz/plyr#4]
I really like this player, what you think add support for sass? Will be nicer for developers like me who loves SASS. :+1:

**Comment by SamPotts** [comment]
For sure. It's not my native CSS preprocessor but I will take a look. It's something I want to learn.

**Comment by brunobatista** [comment]
Thanks for your attention @SamPotts.

**Comment by tomByrer** [comment]
Is the LESS rendered in-browser?

**Comment by SamPotts** [comment]
Hey Bruno, I'll take a look at your pull request in a little bit. I'm sure it'll be fine. My only worry is supporting both LESS and SASS. 

Hey Tom, nope. I've got a gulpfile that I use to render it for local testing along with the generation of the SVG sprite etc. It doesn't do anything too fancy. I'll add the SASS build into it too.

**Comment by tomByrer** [comment]
Someone should make a pre-pre-parser, so it can be re-compiled into LESS, SASS, Stylus, Styl...

**Comment by SamPotts** [comment]
Hey Bruno, just pushed 1.0.17 with your SASS file in (with slight amend for #6 ). I've not included the SASS files for docs since they will just add extra maintenance there and be less useful for users. I've also separated the core Plyr files from docs to clean things up. I think it makes sense?
