### ISSUE TITLE
Seeking in the video

### ISSUE THREAD

**Issue by jocelynthode** [Selz/plyr#40]
Hey, nice video player :)

I think stopping the video while seeking in it would be a good thing to have. Having the seconds displaying where the seek will be when released would be a goo thing too.

For example I'm at 0:16 I start seeking and want to go to 0:30. When my cursor is on 0:30 while seeking the counter should show "0:30"

**Comment by SamPotts** [comment]
Thanks @jocelynthode , I'll take a look at this. Should be pretty straight forward.

**Comment by jocelynthode** [comment]
@SamPotts : Thanks or maybe try something like the youtube player does (it just make a small popup on the cursor with the precise time in the seek)

**Comment by SamPotts** [comment]
Hey @jocelynthode , I've just pushed a fix with some changes to seeking. There's no popup (it's on my list) but when you seek you get an instant update of the play time and it's just generally a bit nicer now. Let me know if that's better for you.

**Comment by jocelynthode** [comment]
Yeah much nicer ! Thanks for the quick fix. I hope this player will be adopted by a lot of sites :)
