### ISSUE TITLE
How to get playing status?

### ISSUE THREAD

**Issue by samuelcarreira** [Selz/plyr#401]
Hi, I can't find a way to get if Plyr player is currently playing audio, On HTML5 standard audio I can use ``player.paused (boolean result) and player.duration > 0``

What is the correct method for Plyr?

Thanks for your work

**Comment by samuelcarreira** [comment]
Should I use a state var to trigger when `playing` event is set, and set that var to false on the following events: `end and pause` ?

**Comment by SamPotts** [comment]
Hey @samuelcarreira , v2.0.8 includes a new API method called `.isPaused()` which should be useful? 👍  Otherwise you can listen for events, yep!

**Comment by samuelcarreira** [comment]
Thank you for the update!
