### ISSUE TITLE
Add missing Vimeo and YouTube events

### ISSUE THREAD

**Issue by suryaiiit** [Selz/plyr#409]
Hi,

Thanks for the great Player!!

I noticed few issues, please correct me if I'm wrong anywhere.

1. Vimeo: Not firing 'ended' event. (YouTube is working fine).
2. Seeked/Seeking events are not firing, when I'm dragging the progress bar - not working on both YouTube & Vimeo.
3. In YouTube when I click on the progress bar (forward/backward) a play event is being fired, it is good. But the same is not happening with Vimeo.
4. When I click on the progress bar to move (forward/backward) how can we know the previous timeline in seconds? just to know from where it was dragged .
5. Anyway we can get the posters of YouTube/Vimeo videos??

Sample Code: http://codepen.io/suryaiiit/pen/ozrrWz

Best,
Surya

**Comment by SamPotts** [comment]
Cheers 👍 

1) Vimeo added a note about `ended` with the `loop` option. Are you using that? https://github.com/vimeo/player.js#ended
2) These were not supported in YouTube or Vimeo as documented but I am about to add support
3) I will also add the `play` and `playing` events for Vimeo after `seeked`
4) This is currently not supported
5) This is currently not supported but has been asked for a few times and I'll take a look at potential options for this

**Comment by SamPotts** [comment]
Fixed 1,2,3 in v2.0.10:
https://github.com/Selz/plyr/releases/tag/v2.0.10
