### ISSUE TITLE
Set video to mute on initialization

### ISSUE THREAD

**Issue by silviaaimone** [Selz/plyr#411]
Hi, how can I set all my video instances (youtube) to muted when I initialize them with plyr.setup() ?
thanks

**Comment by SamPotts** [comment]
In your config options, pass the `volume` option as 0. 

https://github.com/Selz/plyr/blob/master/readme.md#options

**Comment by snstar2006** [comment]
I don't think it is working. You have volume option minimum set at 1. I entered volume:0, but it seems to only take it as 1, not muted.

**Comment by maimairel** [comment]
Yes, you can only set it muted using `setVolume(0)`. I think this need to be fixed.

**Comment by nanastya** [comment]
Hi @sampotts 
I have set `muted: true`, I also tried all the hacks with `volume: 0` - video (Vimeo) still plays with sound. Muted parameter doesn't appear in iframe _src_ attribute. If I insert _&muted=true_ parameter in dev tools - video is muted. Please, comment on this

**Comment by sampotts** [comment]
@nanastya I'm about to push a fix for Vimeo

**Comment by nanastya** [comment]
@sampotts Thanks for your answer. I've updated Plyr, but there's the same issue with muted parameter for me. Can you, please, double check it?

**Comment by sampotts** [comment]
Remember that users volume settings are stored in local storage so try clearing that first. 

Sam
