### ISSUE TITLE
This is only a suggestion, i want to help but you just want to prove your point. it's your player script you do want you want.

### ISSUE THREAD

**Issue by onigetoc** [Selz/plyr#415]
This is only a suggestion, i want to help but you just want to prove your point. it's your player script you do want you want.

**Comment by SamPotts** [comment]
Help? You need to check the definition. You were moaning about something so minor that no one out of the 8,000+ watchers has complained about. The whole point of providing the CSS and the ability to customise the HTML is so you can make it how you want. You have your opinion and that's fine but your opinion is no more important than anyone else's. Please understand that.
