### ISSUE TITLE
Plyr + React error on destroy(): Cannot read property 'replaceChild' of null

### ISSUE THREAD

**Issue by sebastiancarlsson** [Selz/plyr#416]
- [x] Issue does not already exist
- [ ] Issue observed on https://plyr.io

I've built a video player react component using plyr. When I destroy it I get an error in the console. I've created a pen to illustrate the problem, please find the link below.

### Expected behaviour 
Video player is initiated/destroyed without any problems.

### Actual behaviour
Video player is working as expected, however on calling destroy() this error is thrown:
````
Uncaught TypeError: Cannot read property 'replaceChild' of null(…)cleanUp @ plyr.js:3295
````
The line that fails in plyr.js is:
````
// Replace the container with the original element provided
plyr.container.parentNode.replaceChild(original, plyr.container);
````
I suspect that the error has something to do with React updating the DOM and the reference to `parentNode` gets lost, however it actually works i.e. _the video player gets replaced with the original element_ so I'm a bit confused as to what is actually happening here. I tried to add a shouldComponentUpdate() method that always returns false to prevent re-rendering of the element, and then use componentWillReceiveProps() to create/destroy the player instead but I get the same error so I'm not sure the theory about React updating the DOM is correct.

Since it's actually working except for that error I lazily tried to wrap the destroy() call in a try/catch but that didn't help.

### Environment

- Browser: Google Chrome
- Version:  54.0.2840.71
- Operating System: MacOS
- Version: 10.10.5

### Steps to reproduce 
- See codepen link below
- Press the "toggle" button to create and then destroy the video player.
- See error in console

### Relevant links
Example: http://codepen.io/sebastiancarlsson/pen/6501eadfea7011231b24f0925713c774/

**Comment by sebastiancarlsson** [comment]
I investigated this a bit and it turns out that it's because of the cleanUp() method getting executed twice. I have submitted a pull request with a fix for this bug.

**Comment by SamPotts** [comment]
Thanks for that. Will push a new version shortly.

**Comment by julmot** [comment]
I am still experiencing a similar issue. Any follow-up information in this regard?

**Comment by friday** [comment]
@julmot Please create a new issue with details how to replicate the issue (optimally with an online code example on jsfiddle or something) and the stack trace, unless it's the same as #1001

**Comment by julmot** [comment]
@friday I have commented over there.
