### ISSUE TITLE
req: how to configure always-visible control below video?

### ISSUE THREAD

**Issue by FredThompsonII** [Selz/plyr#417]
- [X ] Issue does not already exist

With a call like this:

        <link rel="stylesheet" href="Quick Access Popup_files\plyr.css">

                <video width="640" height="380" controls>
                    <source src="Quick Access Popup_files\video.mp4" type="video/mp4">
                    <a href="Quick Access Popup_files\video.mp4" download>Download</a>
                </video>

How to do these?:

1) move controls below video
2) enable controls always visible
3) configure styling as in the screenshot at https://github.com/Selz/plyr

**Comment by SamPotts** [comment]
1. This is a custom implementation - I don't have time to write you the CSS for it. 
2. This is a config option but if you're doing 1) then you can ignore the class name that's added to hide the controls. 
3. If you use the default stylesheet, you'll get the default styling
