### ISSUE TITLE
Seek on drag

### ISSUE THREAD

**Issue by riaan53** [Selz/plyr#42]
Hi,

I like the player a lot specially the smooth responsive part! One thing, I see that the seekbar is set on mouse up and would like it to be draggable, this is important for mobile/cordova as well.

Can it be easily done or not?

Thank you!

Regards,
Riaan

**Comment by SamPotts** [comment]
Hey Riaan,

Good suggestion. It should be possible. I'd have to overlay an `<input type="range">` over the top of the progress I think but let me have a think and get back to you. There might be a better way. Definitely do-able though.

**Comment by SamPotts** [comment]
Hey Riian, 

Just pushed a fix for this. Take a look and let me know! 

Cheers

**Comment by riaan53** [comment]
Awesome! Works great!

Two smaller improvement suggestions:

1. I cant remember if it was like this before but the seek and buffer bar jumps in increments and looks a bit laggy. A smooth transition on both will be very nice.
2. When dragging the seekbar a bit faster on http://plyr.io/ the bar lags the mouse pointer.

Thanks again for this awesome player and quick responses!

**Comment by SamPotts** [comment]
Both good points. The problem is the native `<progress>` element is pretty janky (I tried everything). IE is actually pretty smooth oddly but Webkit and Mozilla aren't the best. I tried adding transitioning but of course that means 2) happens. I think I'll remove the transition for now.

**Comment by tomByrer** [comment]
Sounds more like a client problem, not a spec failure.  Bugs probably should be submitted to Chrome & Fx.
