### ISSUE TITLE
sprites?

### ISSUE THREAD

**Issue by brontosaurusrex** [Selz/plyr#424]
### Expected behaviour 
firefox demo/index.html # will show button sprites (like play)

### Actual behaviour
firefox demo/index.html # will NOT show button sprites (like play)

### Environment
- Browser: firefox
- Version:  45
- Operating System: Debian
- Version: Jessie

p.s. Also https://cdn.plyr.io/2.0.10/plyr.svg looks kinda white

**Comment by SamPotts** [comment]
Did you observe this on https://plyr.io? They work fine in Firefox. Double check your implementation and check the console. 

Yes, the SVG sprite will not render all icons and will be blank if you view it directly. That's normal.
