### ISSUE TITLE
Safari downloads video source in it's entirety before player is engaged

### ISSUE THREAD

**Issue by intelligence** [Selz/plyr#431]
- [x] Issue does not already exist
- [x] Issue observed on https://plyr.io

### Expected behaviour 
Wait to load video source until Plyr player is engaged

### Actual behaviour
Safari will start to download video source immediately on load

### Environment
Mac

- Browser: Safari
- Version: 10.0.1
- Operating System: OSX
- Version: 10.12.1 (16B2555)

### Steps to reproduce 
- Just visit plyr.io bring up the network tab and reload page. Safari will load source immediately whereas Chrome and Firefox will wait until the player is engaged with play button. Causes severe sluggish behaviour on my site with multiple Plyr players present (~150MB worth of video that starts to load).

![skarmavbild 2016-11-25 kl 02 29 38](https://cloud.githubusercontent.com/assets/756582/20612141/0bf41b74-b2b7-11e6-84e2-e195683016a0.png)

### Relevant links

**Comment by SamPotts** [comment]
This is due to how you specify preload. Look at the preload attribute for HTML5 media elements. 

Sam

**Comment by intelligence** [comment]
Boy do I feel silly. I was convince that none was the default state. Thanks for such a quick reply. I do think it's weird that Safari download a bunch, whereas Firefox and Chrome will just load a couple of KBs, but I guess that's browser vendors for ya.

**Comment by SamPotts** [comment]
Yeah they all do what they think is best, not always what the spec outlines unfortunately :( No worries 👍
