### ISSUE TITLE
Progressive download audio on IOS 

### ISSUE THREAD

**Issue by peerfischer** [Selz/plyr#434]
- [ X] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
MP3 stream starts after a short preload

### Actual behaviour
whole mp3 is downloaded before start playing the audiofile

### Environment

- Browser:
mobile Safari
- Version:  
- Operating System:
IOS 10
- Version: 

### Steps to reproduce 
- 

### Relevant links

**Comment by SamPotts** [comment]
This can be achieved using the `preload` attribute on the `<audio>` element. Not a feature of Plyr but the underlying HTML5 media elements. 

This link is for `<video>` but the same applies:
https://www.stevesouders.com/blog/2013/04/12/html5-video-preload/

**Comment by peerfischer** [comment]
As far as I know "preload" is ignored on mobile Safari. 
What can I do to play the audio file instantly instead of downloading the whole file before playing it?

**Comment by SamPotts** [comment]
I'm not sure I can help out there given Plyr doesn't effect the underlying HTML5 implementation. Maybe raise it with Apple or WebKit themselves.

**Comment by SamPotts** [comment]
I think from looking at [the docs](https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/AudioandVideoTagBasics/AudioandVideoTagBasics.html) , it's saying it never preloads, so it shouldn't download the whole file and should play whatever it has buffered.
