### ISSUE TITLE
[question] how to fit plyer to outer div size

### ISSUE THREAD

**Issue by guykatz** [Selz/plyr#438]
Hi
this is more of a question (either css ot plyr related). please see my example pen: http://codepen.io/guykatz/pen/LbOrgE
my container div has a "strange ratio" and an overflow hidden. playr overflows and I cant see the controls and the lower part of the movie is clipped.
adding the css:
.container .plyr{
  height:100%;
}
will make the controls to come back byt the movie is still overflowing.
any suggestions?
thanks.

**Comment by SamPotts** [comment]
You don't need to set the height. If you want responsiveness, you should also just use max-width. Not sure you need `overflow: hidden` either. 

If you need to set the height and width then you need to do the 16:9 trick:
https://css-tricks.com/NetMag/FluidWidthVideo/Article-FluidWidthVideo.php

**Comment by guykatz** [comment]
thanks.
I have a flexbox layout with tiles like items. there are flex items with 25% width and overlow hidden.
the overflow is so that the layout is not interupted - this is very common.
inside one of the tiles I want to put plyer. I do not control the tile width as it changes from one screen resolution to the other. also, I do not know the ratio of the movie I am going to load.
I want to keep my such that it fits inside my tile. 
my example was simplifying the situation. i'll gladly write a new pen with the whole layout.
is your answer still the same? I mean, it would be nice if plyer 'new' the parent's dims and fit itself such that the movie is not cropped.
if there is no plyer feature for this maybe there should be?
thanks!

**Comment by SamPotts** [comment]
I'd try that first or perhaps try using flexbox if you need to set the height.

**Comment by guykatz** [comment]
wow that was fast - thanks!
I will play around with it and worse case scenario if I still am in trouble I will write a new pen and write another reply here.
thanks again.
