### ISSUE TITLE
API For Changing Sources

### ISSUE THREAD

**Issue by martindale** [Selz/plyr#44]
It'd be nice if something like `player.source('some new url')` could be called to stop and remove whatever is currently playing, then replace it with a new source without re-instantiating the player.  Fullscreen would be preserved if it was turned on, as would audio levels.

**Comment by dvdheiden** [comment]
+1 for this. Might be related to: https://github.com/Selz/plyr/issues/3. A playlist would require the player to switch sources anyway.

**Comment by SamPotts** [comment]
Great idea. I'll look into it. It would need to accept an array I'd think for multiple formats as well. Easily done though. 

Cheers!

**Comment by espellcaste** [comment]
+1

**Comment by taug** [comment]
+1

**Comment by SamPotts** [comment]
Looking into this next as it fits well with playlists as @dvdheiden mentioned. Give me a day or two.

**Comment by espellcaste** [comment]
o/

**Comment by SamPotts** [comment]
Almost done with this. It'll go out later today. 

Basically I've written the method so it'll take either:
- A single string source 
- An object of attributes (src, type, etc)
- An array of attribute objects 

Depending on what's been passed will effect how it's rendered (`src` attribute on the element vs child `<source>` elements)

Does this sound about right? Currently working through some quirky Webkit behaviour and I'll merge it to master and push v1.0.22.

Cheers for the support :+1:

**Comment by espellcaste** [comment]
It sounds ok for me.

**Comment by SamPotts** [comment]
This should be fixed in v1.0.22 - let me know. 

I ended up just accepting a string source which sets the `src` attribute on the video or audio element and also an array of objects which will output `<source>` elements with the provided keys as attributes. 

Check out https://github.com/Selz/plyr#api for more info and let me know if you find anything wrong!
