### ISSUE TITLE
Hide volumn control

### ISSUE THREAD

**Issue by dungphanxuan** [Selz/plyr#441]
Hello, how to hide volumn control
![image](https://cloud.githubusercontent.com/assets/10725732/20790055/440dd450-b7e9-11e6-84b0-9f1f9f643efe.png)

**Comment by SamPotts** [comment]
Read the docs. It's an option called `controls`.

**Comment by dungphanxuan** [comment]
i don't know how to set
![image](https://cloud.githubusercontent.com/assets/10725732/20790413/c753d052-b7ea-11e6-8682-f205e1246f51.png)

 var instances = plyr.setup({
        debug:              false,
        title:              'Video demo',
        captions: {
            defaultActive:  true
        }, 
        controls: {
            volume: false
        },
    });

**Comment by SamPotts** [comment]
It's an array as shown, and noted. Include the controls you want.

**Comment by dungphanxuan** [comment]
It work. thank you
