### ISSUE TITLE
Video Thumbnail issue on Apple Devices

### ISSUE THREAD

**Issue by sohrabzia** [Selz/plyr#445]
- [X ] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
It should show play button on video thumbnail. 
### Actual behaviour
It is not showing play button and increase the thumbnail image size to over flow.
It is only happening on iphone devices. 

### Environment
this is the code i am using to call plyr.js
```
plyr.setup();
```
maybe I am missing setup(); 
I cant figure out.
i dont/cant add css resize styles for each device.

- Browser: Chrome
- Version:  54.
- Operating System: Windows
- Version: 8.1

### Relevant links

**Comment by SamPotts** [comment]
Is the issue with iPhone or Chrome 54 on Windows 8.1 as you've filled out? 

Plyr is not supported on iPhone:
https://github.com/Selz/plyr#browser-support

See point 1. The native player is used. If you have an issue with the native player, I'd suggest raising a bug with WebKit directly.

**Comment by sohrabzia** [comment]
I dont have issue with native app, it is just that plyr thumbnail size is overflowing and its parent div is (overflow hidden) so bevause of that native controls are not visible. i just want it to show native player controls and not to increase thumbnail size. Thanks a lot :)

**Comment by SamPotts** [comment]
If your bug is with the native player, I'd suggest maybe raising it with WebKit. Plyr doesn't change anything with the native player.
