### ISSUE TITLE
Controls Defaults

### ISSUE THREAD

**Issue by martindale** [Selz/plyr#45]
It seems like one has to write their own controls to get this working at all.  Some sane defaults should be provided.

**Comment by SamPotts** [comment]
Hey @martindale , my aim was to avoid including them to keep the size down but I can't see the size increasing too much thinking about it. I'll add them now though.

**Comment by SamPotts** [comment]
Added them into v1.0.20. Cheers

**Comment by martindale** [comment]
Awesome.  Thanks!
