### ISSUE TITLE
Playing Vimeo videos opens Vimeo fullscreen mode

### ISSUE THREAD

**Issue by fablife** [Selz/plyr#452]
### Expected behaviour 
When loading a Vimeo video, and clicking play, I would expect the video to load inside its player frame, and not go to fullscreen.

### Actual behaviour
When clicked on the video to play, the video goes to fullscreen, and the Vimeo UI appears.

### Workaround:
Using the ready event, remove the vimeo fullscreen attributes from the embed. But it does not seem to work always....

```
   function removeVimeoFullscreenAttributes() {
        var embed = $scope.player.getEmbed();
        if (!embed || !embed.element.attributes.webkitallowfullscreen) return;
        embed.element.allowFullscreen = false;
        embed.element.attributes.removeNamedItem("webkitallowfullscreen");
        embed.element.attributes.removeNamedItem("mozallowfullscreen");
    } 
     function setUpVideoPlayer(media) {
      $scope.player.on("ready", removeVimeoFullscreenAttributes);
      $scope.videoSetup = true;
    }


var video_id = media.stream_url.substr("https://vimeo.com/".length);
      $scope.player.source({
        type:       'video',
        title:      media.title,
        sources: [{
            src:    video_id,
            type:   'vimeo'
        }]
      });
  if (!$scope.videoSetup) {
        setUpVideoPlayer(media);
      }

```

**Comment by SamPotts** [comment]
What browser? Please use the template I provided in future as it helps me fix the issue quicker. If it's on an iPhone then that's the native behaviour and can't be changed unfortunately.

**Comment by fablife** [comment]
Thanks for responding so quickly, and sorry for not abiding to your template.

This happens in the context of a generated app for android via ionic framework. In fact, when developing on the desktop with firefox, it rarely happens if at all. But on the mobile browser, it happens almost always.

**Comment by SamPotts** [comment]
Hmm Android should play in-situ as far as I'm aware. I'll take another look. I can't test ionic easily of course but will check out other options. With regards to Vimeo though, we just use their API to control playback etc: https://github.com/vimeo/player.js. It may be a current issue over there.

**Comment by fablife** [comment]
mind you, ionic generates code...it's not native Android as far as I understand....

**Comment by ruurtjan** [comment]
I'm having the same issue on Chrome for android version 55.0.2883.91 (Android 5.1.0).

**Comment by SamPotts** [comment]
Feel free to raise the bug with the Vimeo API: 
https://github.com/vimeo/player.js

**Comment by Valdrinium** [comment]
I am having the same issue on Android 7.0, Chrome 61.

**Comment by TychaK** [comment]
Have you tried adding `**?playsinline=1**` at the end of the vimeo iframe url?

`<iframe src="https://player.vimeo.com/video/29746470435616**?playsinline=1** autoplay=1&amp;title=0&amp;byline=0&amp;portrait=0"
                        width="100%" height="360" frameborder="0" webkitallowfullscreen="" mozallowfullscreen=""
                        allowfullscreen=""></iframe>`
