### ISSUE TITLE
Mobile Safari - problem when I stopping move

### ISSUE THREAD

**Issue by kriss145** [Selz/plyr#469]
Hi,

I have big problem.

I using methods "exitfullscreen" and "enterfullscreen" but it don't work in mobile Safari.
When I clicking "Done". Movie is still "fullscreen". Ex. class "plyr--fullscreen-active" still exist.

Could help me?

Thanks

**Comment by SamPotts** [comment]
Plyr doesn't support iPhone at present as no custom UI is possible as videos must play in fullscreen.
