### ISSUE TITLE
Add option to hide controls in fullscreen

### ISSUE THREAD

**Issue by master-lincoln** [Selz/plyr#47]
Would be awesome to hide the controls in fullscreen if mouse wasn't moved a certain time and re-show them on mouse move.

**Comment by SamPotts** [comment]
Hey @master-lincoln ,

Good suggestion and relatively easy to add. My only concern was keyboard users but some clever focus event detection should solve that. I'll look into it. We actually do it on selz.com (check the homepage vid) so I've already written the CSS but an option would be good.

**Comment by master-lincoln** [comment]
I didn't have that effect on selz.com. Checked with Chromium 40 and Firefox 36 on Linux.

**Comment by SamPotts** [comment]
Sorry you're right. Because it's a purely CSS solution I put in there it's based on :hover so if you can hover out (you'd need multiple screens) it'd slide down. I'll work on a JS based solution (with class hook) for this to monitor mouse move.

**Comment by SamPotts** [comment]
Hey @master-lincoln , sorry for the delay but this is now in v1.0.29. I've made it so it hides after 1s (CSS transition) and if you mouseover over the progress bar (the only visible control), the controls re-appear. If you focus a child control they should also appear. On a touch device you need to tap the video which will play or pause it if you have the `click` option set to `true` (default).

The option is within the `fullscreen` option object and the property name is `hideControls`. It's defaulted to `true`.

Check it out on plyr.io :+1:
