### ISSUE TITLE
Vimeo videos are broken because of mime type

### ISSUE THREAD

**Issue by alexcarpenter** [Selz/plyr#471]
- [ x ] Issue does not already exist
- [ x ] Issue observed on https://plyr.io

### Expected behaviour 
Vimeo videos play

### Actual behaviour
Vimeo videos are broken

### Environment

- Browser: All
- Version:  All
- Operating System: Mac
- Version: 

### Steps to reproduce 
- Visit homepage and click vimeo

### Relevant links
![screen shot 2016-12-30 at 8 45 24 am](https://cloud.githubusercontent.com/assets/825855/21565987/590b0c80-ce6c-11e6-9736-254f81aaa957.png)

**Comment by SamPotts** [comment]
I can't replicate this now - presumably they've fixed it but next time any issues with vimeo's API can be raised with vimeo's repo:
https://github.com/vimeo/player.js
