### ISSUE TITLE
HLS embed video does not display in fullscreen

### ISSUE THREAD

**Issue by gurupras** [Selz/plyr#476]
- [x] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
Expect video to show in fullscreen

### Actual behaviour
Audio plays, but no video.

### Environment

- Browser: Chrome
- Version:  55.0.2883.87 m
- Operating System: Windows
- Version: 10

### Steps to reproduce 
- [fiddle](https://jsfiddle.net/gurupras/99420bsv/)

### Relevant links

**Comment by SamPotts** [comment]
Is that the right fiddle? Can't see any HLS on there and the video seems to play ok...

**Comment by SamPotts** [comment]
HLS Demo is here:
http://codepen.io/sampotts/pen/JKEMqB

**Comment by gurupras** [comment]
Sorry, try this..
https://jsfiddle.net/gurupras/99420bsv/

**Comment by SamPotts** [comment]
Video seems to work fine for me in Chrome 55 on OS X and Windows. There's some weird styling issues going on in that demo though. Try removing the 16:9 hack as you don't need that for HTML5 video anyway.
