### ISSUE TITLE
Improve playback progress

### ISSUE THREAD

**Issue by SamPotts** [Selz/plyr#48]
Raised on hacker news:
https://news.ycombinator.com/item?id=9139633

**Comment by 0xsven** [comment]
Any solution to this? It looks very laggy with a 12 seconds video.

Can you update the progress bar more often somehow?

**Comment by SamPotts** [comment]
HTML5 and Vimeo players progress elements are updated based on the 'progress' event from the media element - the rate of which can't be sped up. Were you referring to a YouTube player?
