### ISSUE TITLE
Playback problem

### ISSUE THREAD

**Issue by tspmelo** [Selz/plyr#480]
- [x] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
Video should play
### Actual behaviour
Video doesn't start playing
### Environment

- Browser: Chrome 
- Version:  55
- Operating System: Windows 10
- Version: 10

Players affected:
- [x] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
- Open [Plyr Video test](http://codepen.io/anon/pen/xgVWEz) (it's a fork from the original plyr demo with the video src changed)
- Try to play the video
- Nothing happens

### Relevant links

1. [HTML5 video test](http://codepen.io/anon/pen/RKaMWd)
2. [Plyr Video test](http://codepen.io/anon/pen/xgVWEz)

### Comments 

- If I use the video used in the plyr demos it works fine, but I found a couple of mp4 videos that don't work.
- As you can see on [HTML5 video test](http://codepen.io/anon/pen/RKaMWd) using only the html5 video tag the same videos works fine.
- Tried in IE 11 and it works fine, so must be a problem specific to Chrome

**Comment by randomboygh** [comment]
Video doesn't load without plyr too. So I think it's not plyr bug.
https://codepen.io/anon/pen/OWNBEd

**Comment by tspmelo** [comment]
After looking at your example I notice that my examples had 1 diference, the **crossorigin** attribute. 
If you remove the attribute everything seems to work. 

Thanks for the reply and sorry about the false issue.
