### ISSUE TITLE
H.265 Encoded Videos

### ISSUE THREAD

**Issue by Tortschi** [Selz/plyr#483]
- [X ] Issue does not already exist
- [X] Issue observed on https://plyr.io

### Environment

- Browser: Firefox, Chrome
- Version:  
- Operating System: Windows, Mac
- Version: 10, 7

Players affected:
- [X ] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
- When we encode with FFMPEG a MP4 Video to H.265 Video not playback. When we encode it to H.264 it work

**Comment by SamPotts** [comment]
Please remember Plyr is just an extension of the native HTML5 video and audio players. For support of the HTML5 players, please check MDN: 
https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats
