### ISSUE TITLE
iconUrl doesn't work

### ISSUE THREAD

**Issue by culbrique** [Selz/plyr#494]
Hi !
It seems that iconUrl does'nt work for me. That is my code 
```
plyr.setup({ 
        controls: ['play-large', 'play', 'progress', 'current-time'],
        iconUrl: '/icons/plyr.svg'
});
```
And I placed the "plyr.svg" (from the dist folder) to root/icons/, just to try this option, but no images are displayed.
This is what I see with Firebug 
```
<button type="button" data-plyr="play" aria-label="Play">
<svg>
<use xlink:href="/icons/plyr.svg#plyr-play">
</svg>
<span class="plyr__sr-only">Play</span>
</button>
```
What I did wrong ?

**Comment by sirx** [comment]
Try to pass the full URL, I also had something similar with the plyr.svg I tried out a bit and I found out that I have to use the full url in the js file in order to get it working.

plyr.setup({ 
        controls: ['play-large', 'play', 'progress', 'current-time'],
        iconUrl: 'http://yourdomain.com/icons/plyr.svg'
});

That's how I did it.

**Comment by culbrique** [comment]
Thank you for your reply. It works fine now. I can now replace the <path> attribute inside the plyr.svg file. 👍
