### ISSUE TITLE
Audio (.mp3) not playing in IE11 - Invalid source error

### ISSUE THREAD

**Issue by jackbarham** [Selz/plyr#498]
I've got the audio player working in all browsers (FF, Chrome, Safari but I get an "invalid source" error when playing in IE11 and edge.

I have checked and the .mp3 is formatted correctly. I also went to http://plyr.io in the same browser and the audio player just kept loading and never plays (although I didn't get an error) but the video player works.

This is my code:

```
<audio controls="controls">
    <source src="file.mp3" type="audio/mp3">
</audio>
```

**Comment by SamPotts** [comment]
Remember that Plyr is just an abstraction of the native HTML5 media elements so if an MP3 doesn't play then it's more than likely an issue with the encoding. I'd double check that:
https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats
