### ISSUE TITLE
How to change the width and height of the video manually?

### ISSUE THREAD

**Issue by rodrigobg** [Selz/plyr#499]
Hi, I did not find any documentation teaching how to set width and height of a video using Plyr, does not this functionality exist yet? And if there is, how to implement?

- [ ] Issue does not already exist
- [x] Issue observed on https://plyr.io

### Environment

- Browser:
- Version:  
- Operating System:
- Version: 

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
-

**Comment by SamPotts** [comment]
It's a responsive (as everything should be these days) so if you want to fix height and width. You'll need to look at doing that with CSS.
