### ISSUE TITLE
Minified CSS and JS

### ISSUE THREAD

**Issue by brunobatista** [Selz/plyr#5]
For debug purpose I think will better add in bower the non-minified files.

**Comment by SamPotts** [comment]
Good idea. I've updated bower.json to include the source files. Let me know if there's any problems. 

Cheers!

**Comment by brunobatista** [comment]
Thanks again @SamPotts, think this small details will help us to build better with debug on!

**Comment by SamPotts** [comment]
No problem at all. Let me know if you find anything else or ideas you have :+1:
