### ISSUE TITLE
Option for tooltips for buttons

### ISSUE THREAD

**Issue by SamPotts** [Selz/plyr#50]
Another one from hacker news. An option to render the sr-only labels as tooltips instead.

**Comment by AndersonReyes** [comment]
I would like to try and implement this feature and contribute!

**Comment by SamPotts** [comment]
Hey @AndersonReyes , that'd be awesome. My thoughts on it would be to try and re-use the current `sr-only` labels/spans as the tooltips (by switching class based on the option). This would keep the markup clean. Also they shouldn't be "display: none" as this would mean they'd not get read out by screen readers. If you use Mac you can test using Voiceover , and NVDA on Windows. 

If you need any help with anything, give me a yell on Twitter. :+1:

**Comment by AndersonReyes** [comment]
@SamPotts I don't have a twitter but give me your email, because yeah im studying the code now so everything you just said I have no idea lol

**Comment by fclaussen** [comment]
Just sent a pull request. Sorry, this is my first time collaborating on github and I got a little lost but the code works. Thanks :)
