### ISSUE TITLE
Draggable video options don't de-select when clicking desired volume/location

### ISSUE THREAD

**Issue by JayBox325** [Selz/plyr#500]
### Expected behaviour 

The default behaviour of clicking the circle on the progress or volume bars and click again in the position I want to set the video position or volume.

### Actual behaviour

The circle is always dragging from the moment I click & drag it until I refresh the page. It is acting like it is always selected regardless of where I move the mouse on my screen. And it never de-selects. Ever.

### Environment

- Browser: Chrome
- Version: 56
- Operating System: OSX
- Version: 10.11.13

Players affected:
- [x] HTML5 Video
- [ ] HTML5 Audio (untested)
- [x] YouTube
- [x] Vimeo

### Steps to reproduce 
- Just try to use the default progress/volume bars

**Comment by magicspon** [comment]
I am also experiencing this issue.

any thoughts?

**Comment by JayBox325** [comment]
I noticed that there was an error in the console that was from Vimeo itself at the time, but this error is no longer there and this issue appears to have solved itself once Vimeo fixed their error.

Thanks.
