### ISSUE TITLE
Vimeo throws an error (player.js)

### ISSUE THREAD

**Issue by magicspon** [Selz/plyr#513]
- [ ] Issue does not already exist **Not that I can see**
- [ ] Issue observed on https://plyr.io: **YES**

### Expected behaviour 

Video should play without throwing any errors

### Actual behaviour

As soon as the video starts to play the following error is thrown
```
Uncaught TypeError: navigator.mediaSession.setActionHandler is not a function
    at t.value (player.js:13)
    at t.<anonymous> (player.js:13)
    at t.Te.e.fire (player.js:3)
    at player.js:15
    at i (player.js:9)
value @ player.js:13
(anonymous) @ player.js:13
Te.e.fire @ player.js:3
(anonymous) @ player.js:15
i @ player.js:9
```

So it looks like the error is coming from player.js 

### Environment

- Browser: Chrome
- Version:  Latest
- Operating System: OS
- Version:  2.0.11

Players affected:
- [ ] Vimeo

### Steps to reproduce 
Press play... look in the console!

**Comment by SamPotts** [comment]
Head on over to the Vimeo API for this one then:
https://github.com/vimeo/player.js/issues
