### ISSUE TITLE
Vimeo show only black layer

### ISSUE THREAD

**Issue by qustnvikas** [Selz/plyr#518]
- [ ] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
Vimeo player shwoing only black layer no play icon etc
### Actual behaviour
only showing black overlay for player
### Environment
android 
- Browser:
- Version:  
- Operating System:
- Version: 

Players affected:
- [ ] Vimeo

### Steps to reproduce 
-

**Comment by SamPotts** [comment]
Could you be more vague, perhaps include less information for me to reproduce?

**Comment by qustnvikas** [comment]
Hello SamPotts,

Video player is working for mp4 video and youtube also but for vimeo its no loading iframe (it load for youtube ) please check my screenshot for this 
![2017-02-23](https://cloud.githubusercontent.com/assets/15994915/23258235/453d8b54-f9ed-11e6-90d2-35f7cf1798ca.png)
![screenshot_2017-02-23-17-26-42](https://cloud.githubusercontent.com/assets/15994915/23258284/8aa79162-f9ed-11e6-8a25-dfec0a228d3a.png)
