### ISSUE TITLE
Video doesn't appear

### ISSUE THREAD

**Issue by atilkan** [Selz/plyr#530]
- [x] Issue observed on https://plyr.io

The issue is on the website. Video doesn't appear on Chrome 56 and Opera 43. 
Tested on safari and works.

- Browser: Chrome
- Version:  56.0.2924.87
- Browser: Opera
- Version:  43.0.2442.1165
- Operating System: OSX 
- Version: El Capitan

Players affected:
- [x] HTML5 Video **Yes, Video doesn't appear, cover photo stays**
- [x] YouTube **Video doesn't appear, black screen appear** 
- [x] Vimeo  **Video doesn't appear, black screen appear** 

**Edit:**
Just updated Chrome to 57.0.2987.98. It works on Chrome now but very slow. Safari is fine.

**Comment by SamPotts** [comment]
Not able to replicate this on Chrome 56 or 57 on OS X El Capitan.

**Comment by atilkan** [comment]
@SamPotts  Can you try it on Opera? It is not updated yet.

**Comment by SamPotts** [comment]
Just tested Opera 43.0.2442.1165 - works as expected (video plays). Perhaps check your extensions?

**Comment by atilkan** [comment]
I don't have any on Opera.

**Comment by bogdanfer** [comment]
any console errors?

**Comment by SamPotts** [comment]
Still not able to replicate this on 2 Mac OS machines and a windows box.

**Comment by atilkan** [comment]
After updating Opera and Chrome. They give the same screen. Safari is still ok. My mac is old btw. It may be about GPU.

**This is Chrome.**
![screen shot 2017-03-29 at 14 33 14](https://cloud.githubusercontent.com/assets/1254613/24452523/59bf7b96-148c-11e7-9872-ed52766bb539.png)
**This is Opera.**
![screen shot 2017-03-29 at 14 33 21](https://cloud.githubusercontent.com/assets/1254613/24452527/5e2a41f2-148c-11e7-9e12-d7d712ddf66e.png)

**Comment by SamPotts** [comment]
The screenshots would suggest to me you have other issues causing this...

**Comment by atilkan** [comment]
I agree. But it is interesting that video works on safari which is my cause of doubt.

**Comment by davtay** [comment]
Just want to add that this seems to be an issue related to crossorigin.  I was seeing the same issue(ish) where neither the poster nor video would show and as soon as I removed the crossorigin property, it all worked again.  This is for Chrome 57, not sure about older version.  The issue was not present when using Safari.

**Comment by SamPotts** [comment]
Not something I have control over unfortunately. It's worth raising a bug with Chrome though. They're quick to fix *usually*.

**Comment by davtay** [comment]
Wanted to add that it actually appears to be a combination issue between crossorigin and http.  As long as the content is from an https source, including the poster, then it appears with the crossorigin property added.  Remove that and http content appears.  Still a browser issue though.
