### ISSUE TITLE
Can not swap Soundcloud sources

### ISSUE THREAD

**Issue by davidrol6** [Selz/plyr#535]
Hi.

I have an app where users can load videos and audios and save them into their own library, so they can have videos and audios from any platform in a single place. However this happens:
 
1.- User loads audio from Soundcloud -> OK
2.- User loads another audio or video from Soundcloud or Vimeo -> App stuck. It seems that the new source is not loading and when inspecting the elements you see the playing having the previous source. Destroying and setting it up again does not seem to work.

Thanks.

**Comment by SamPotts** [comment]
SoundCloud is undocumented and unsupported at present. 

Sam
