### ISSUE TITLE
Cannot play dash videos on mobile

### ISSUE THREAD

**Issue by bauerjon** [Selz/plyr#536]
- [x ] Issue does not already exist
- [does not apply because is mp4 on home page] Issue observed on https://plyr.io

### Expected behaviour 
Should be able to stream http://codepen.io/sampotts/pen/BzpJXN on mobile safari on ios

### Actual behaviour
Could not stream on ios

### Environment

- Browser: safari
- Version:  
- Operating System: ios10
- Version: 

Players affected:
- [x] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 

Open the dash js example from the readme  http://codepen.io/sampotts/pen/BzpJXN on ios safari and you can see that it does not play.

**Comment by SamPotts** [comment]
Dash.js is not supported on mobile safari. I have no control over the streaming setups support. 

https://github.com/Dash-Industry-Forum/dash.js
http://caniuse.com/#feat=mediasource
