### ISSUE TITLE
Vimeo Player doesn't work on Mobile

### ISSUE THREAD

**Issue by seanthepottingshed** [Selz/plyr#546]
- [x] Issue does not already exist
- [x] Issue observed on https://plyr.io

### Expected behaviour 

Using controls will play Vimeo video on mobile

### Actual behaviour

Using controls will NOT play Vimeo video on mobile

### Environment

- Browser: Chrome
- Version:   56.0.2924.87 (64-bit)
- Operating System: Mac OS X
- Version: 10.10.5 (14F1605)

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [x] Vimeo

### Steps to reproduce 

* Visit: https://plyr.io/#vimeo
* Ctrl+C to open console
* Enable mobile simulation
* Refresh page

**Comment by SamPotts** [comment]
Try it on a real device. The simulator is exactly that. Not the real thing. 

Sam

**Comment by seanthepottingshed** [comment]
Right you are. I will close this issue now!
