### ISSUE TITLE
C'ant Play Youtube VEVO content 

### ISSUE THREAD

**Issue by k-cgomezh** [Selz/plyr#551]
- [x] Issue does not already exist
- [x] Issue observed on https://plyr.io

### Expected behaviour 
Should be able to play this video https://www.youtube.com/watch?v=PJniSb91tvo.
### Actual behaviour
Could not play the video because has VEVO content. 
### Environment

- Browser: Chrome
- Version: 56.0.2924.87
- Operating System:  Windows 
- Version: 8.1

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [X] YouTube
- [ ] Vimeo

### Steps to reproduce 
- on demo.js set the youtube id video on "src" field:
                    case n.youtube:
                        s.source({
                            type: "video",
                            title: "View From A Blue Moon",
                            sources: [{
                                src: "PJniSb91tvo",
                                type: "youtube"
                            }]
                        });
                        break;
- save and reload
### Relevant links
![image](https://cloud.githubusercontent.com/assets/6986028/24511833/15d83648-156d-11e7-8ec5-b953b867b16e.png)

**Comment by SamPotts** [comment]
That's a copyright issue not an issue with Plyr. Not much I can do about that. 

If you try and play the video in an iframe you get the same response: 
https://www.youtube.com/embed/PJniSb91tvo

![image](https://cloud.githubusercontent.com/assets/719092/24532773/a12cafac-160e-11e7-8dc6-bb1aadc9c258.png)

**Comment by k-cgomezh** [comment]
Thanks!

**Comment by k-cgomezh** [comment]
I found this:  http://stackoverflow.com/a/30990575/2415822    
Maybe can help to solve the issue of restriction
