### ISSUE TITLE
Disabling Click on Progress Bar or Removing It

### ISSUE THREAD

**Issue by Plinpod** [Selz/plyr#554]
Hello,

I was wondering if it was possible to disable the click on the progress bar so it doesn't seek forward or back when a user clicks on it.

Also what would the procedure be to remove the bar and leave the rest of the UI intact if necessary?

Thank You!

**Comment by demsey2** [comment]
@Plinpod I know you close that issue, but I am trying to fix a similar problem. Did you find any solution?

**Comment by Plinpod** [comment]
@demsey2 Actually my solution for this was to use CSS. I added this 

`
.plyr__progress{
  pointer-events: none;
}
`
and it worked for what I needed. Showed the progress bar but didn't allow it to be clicked. Hope that helps!
