### ISSUE TITLE
Plyr add class in my website menu

### ISSUE THREAD

**Issue by onigetoc** [Selz/plyr#555]
Plyr add class in my Wordpress website menu.
Even if i'm good with CSS i can not overwrite the css modification Plyr do to my menu

I do not understand why Plyr add CSS to my website menu. it add plyr plyr ---a

my menu contain tabindex, do not know if it have to do with that.

**Comment by SamPotts** [comment]
Is there a link I can look at? Plyr only adds classed to the element you pass to the `setup` method

**Comment by onigetoc** [comment]
Hi, this was for a client and i was in hurry, i did have to remove Plyr player.
But if you find the solution i will be happy to update and add again the Plyr player.

I Know it's hard to find out without seein the website.

but it add plyr and plyr---- a class (something like that)
to the menu containing a tabindex.

**Comment by SamPotts** [comment]
Well I can't really help then. As I say, Plyr only adds classes to the element you pass to setup. Without any code to look at, I'm working in the dark.
