### ISSUE TITLE
How could I hide my mouse when hiding controls?

### ISSUE THREAD

**Issue by shuang6** [Selz/plyr#579]
### Expected behaviour 
When plyr hides controls, I wish it could also hide my cursor if the mouse is in a div with a  "plyr--video" class.
### Actual behaviour
My cursor is always the pointer.
### Environment

- Browser: Chrome
- Version:  45.0
- Operating System: Windows
- Version: 10

Players affected:
- [x] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
-  
`<div class="plyr__video-wrapper" style="cursor: pointer;">`
If I modify "pointer" to "none", the cursor will always disappear.

**Comment by shuang6** [comment]
I have sloved this question with jquery, but I think it would be better if plyr could expose an api.
// After plyr.setup();
`var timer;  
var hidding = false;
$(function () {
	$('.plyr').mousemove(function () {
		if(hidding){  
          hidding = false;  
          return;  
        }
        if (timer) {  
            clearTimeout(timer);  
            timer = 0;  
        }
        $('.plyr__video-wrapper').css({  
            cursor: 'pointer'  
        });
        timer = setTimeout(function () {
	        hidding = true;  
            $('.plyr__video-wrapper').css({  
                cursor: 'none'  
            });  
	    }, 2000)
	});
});`

**Comment by SamPotts** [comment]
I'm adding two new events: `controlshidden` and `controlsshown` which would help with this
