### ISSUE TITLE
Add loop support

### ISSUE THREAD

**Issue by jofrysutanto** [Selz/plyr#58]
I know that it can be easily added by using 

```
var player = document.querySelectorAll(".player")[0].plyr;

player.media.addEventListener('ended', function() {
  player.play();
});
```
but a shortcut as part of the configuration would be handy?

**Comment by SamPotts** [comment]
Hey @jofrysutanto ,

Did you try the loop attribute? I tested that today and it seemed to work ok? 
http://www.w3.org/TR/html-markup/video.html

Cheers

**Comment by jofrysutanto** [comment]
@SamPotts , blimey, how did I missed that. 
Though adding up on this, as this is what i end up doing:
```
plyr.setup({
    click: false
});
player = document.querySelectorAll(".player")[0].plyr;
player.media.loop = true;
```
It'll be awesome to do this as part of setup:
```
plyr.setup({
    click: false,
    media: {
        loop: true
    }
});
```
Unless i'm missing something here.
Awesome library!
Cheers.

**Comment by SamPotts** [comment]
I meant you can add it to the `<video>` or `<audio>` element. e.g....

```html
<video src="path/to/video.mp4" controls autoplay loop>
</video>
```

**Comment by jofrysutanto** [comment]
Ahh silly me. Oh well, you learn something new everyday!

**Comment by SamPotts** [comment]
No worries :+1:

**Comment by magicspon** [comment]
Hello,

Is it possible to loop videos from vimeo? 

cheers

**Comment by benbonnet** [comment]
@magicspon word for me by setting the loop functionality within vimeo, in the embed section of the video

**Comment by tomhudders** [comment]
@benbonnet you mean the embed settings of the individual videos? Because I can't seem to find a loop option. 

![image](https://user-images.githubusercontent.com/5244216/34357749-f85c3184-ea49-11e7-9492-5a1db49c2ff3.png)

**Comment by tomhudders** [comment]
To answer my own question: in the embed section you have "After video" options. When you have a business account you got a lot of options, one of them being "loop".
https://help.vimeo.com/hc/en-us/articles/115007893267

**Comment by benbonnet** [comment]
@tomhudders sorry for not replying, no options by yep via endscreen
