### ISSUE TITLE
Is the speed-up function enabled now?

### ISSUE THREAD

**Issue by YLaido** [Selz/plyr#581]
I've searched several issues and I found that the `speed-up` function seems to be finished? Then I try to include it in my  `options` but it doesn't work like other options such as `fast-forward` and `caption` ... Then I searched the repository only to find nothing regarding `speed-up` except the Readme.
I am a newbie to coding,would you like to tell me how can I implement the `speed-up` if it's finished? Thanks in advance.

**Comment by SamPotts** [comment]
Not yet no - still in `develop`

**Comment by Belax8** [comment]
I would love to see this published soon!

**Comment by sampotts** [comment]
Me too - I'm working on it
