### ISSUE TITLE
The poster image should appear after the video is finished.

### ISSUE THREAD

**Issue by wjpdesigner** [Selz/plyr#59]
Hi Plyer,

I think after the video is finished the player should bring back the poster image.

Right now I just see the last frame of the video. (In your example it's just an empty white screen.)

Warm regards,
Jack

**Comment by SamPotts** [comment]
I did look into this but I've not found a suitable solution yet. The "native" way seems to be to seek to 0 and then call `.load()` but the problem with that is `.load()` will basically make another request for the video. Not ideal. I will keep looking. It looks like video.js and the like load the poster image into a div, which I'd like to avoid that if possible.

**Comment by adriengibrat** [comment]
``` video.src = ''; ``` unload the video on chrome... got the tip fromp [MDN](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML5_audio_and_video#Stopping_the_download_of_media).

**Comment by SamPotts** [comment]
Hey, there's a bug fix for this in [v1.6.2](https://github.com/Selz/plyr/releases/tag/v1.6.2)
