### ISSUE TITLE
:active vs :focus pseudo-classes for controls

### ISSUE THREAD

**Issue by Svenskunganka** [Selz/plyr#61]
Currently, the controls highlights based on `:focus`, but this is an issue as the element does not leave the `focus` state unless you focus another element on both phones and desktops.

We could work around this issue by replacing `:focus` with `:active` - however, this brings forth another issue for keyboard users as the element does not enter the `active` state, only the `focus` state when you use `TAB` to select elements.

It is a small issue, but mildly irritating - especially when there's a "popover" showing up and not going away until you focus another element.

**Comment by SamPotts** [comment]
Yeah I acknowledge this is a problem. It annoys me too. I'm really not sure what the best way to do it would be unless the tooltips "expired" after a couple of seconds. The fact the buttons are highlighted is also not ideal. We need a `:tabbed` pseudo class selector :+1:

**Comment by calvintam236** [comment]
@SamPotts I notice that the background color when hover sometimes does not go away (stuck) unless you move the pointer/ activate the button in order to restore. How about using both :active and :hover? :hover only fires when the pointer is over the element (perfect for touch screen).

**Comment by SamPotts** [comment]
Yeah the styles are based on `:focus` which for a keyboard user is the only way to see which control is the current selected one. `:active` and `:hover` have different meanings, `:active` is the pressed state and obviously I don't need to explain `:hover`. There is a way of detecting a tab vs a click which I will implement at some stage but there's more important features (playlists and youtube/vimeo etc) to work on right now.

**Comment by calvintam236** [comment]
Good to know that. :+1:

**Comment by SamPotts** [comment]
Couple of useful links for when I get around to this:
- http://stackoverflow.com/questions/5653332/differentiate-between-focus-event-triggered-by-keyboard-mouse
- http://stackoverflow.com/questions/16144611/detect-focus-initiated-by-tab-key

**Comment by calvintam236** [comment]
@SamPotts Since this issue is not fixed, the tooltip does not disappear after you press the icon without clicking anywhere else. For example, press the fullscreen. It won't disappear unless you click on the control/ screen.

**Comment by SamPotts** [comment]
Yep. Aware it's not fixed. I'm getting to it.

**Comment by SamPotts** [comment]
This should be fixed (at long last!) :+1:

**Comment by calvintam236** [comment]
@SamPotts One little issue. When you use the mouse to click a button on the control, the button stays in active status after the pointer moved away.
