### ISSUE TITLE
could i put an advertisement video before main video ?

### ISSUE THREAD

**Issue by adrianmak** [Selz/plyr#64]
as title

**Comment by SamPotts** [comment]
Hey @adrianmak,

I'm sure you can although I've not tried it personally. You'd need to set the advertisement video as the original source for the video and then bind an event to the "ended" event that then calls source() to set the source as the "main" video. e.g.:

```javascript
// Either reselect the player instance or use the return value from plyr.setup();
var player = document.querySelector(".player").plyr;

// Listen for end and call source();
player.media.addEventListener("ended", function() { player.source(...); }, false);
```
You would need to remove this event binding after the switch though or the video source will keep getting reset (not ideal). 

Check https://github.com/Selz/plyr#api what arguments source() accepts.

**Comment by SamPotts** [comment]
How did you go with this? I'm just going to close the issue. Let me know if there were problems.
