### ISSUE TITLE
keyboard accessibility

### ISSUE THREAD

**Issue by Veyfeyken** [Selz/plyr#66]
The player's controls are made with button elements. A keyboard user can hit enter to activate them. 
Mute and captions are toggles made with input type="checkbox". A checkbox can only be used with the spacebar by default. Not with enter. Mute and captions don't look like checkboxes. They look like buttons. A keyboard user might think that mute and captions don't work because they don't react to the enter-key while the other controls do. Please add support for enter on the checkboxes to solve this. That's keycode 13 in JavaScript if I'm not mistaken.

**Comment by SamPotts** [comment]
Excellent suggestion. I have a few other tweaks that I can bundle this with. I'll do this shortly.

**Comment by SamPotts** [comment]
Should be all good now. Check it out and let me know. Cheers :+1:

**Comment by Veyfeyken** [comment]
Thanks, works fine now.
