### ISSUE TITLE
Docker or Vagrant?

### ISSUE THREAD

**Issue by julesbravo** [Selz/plyr#67]
I was going to start working on this project a bit, but the first thing that came to mind was setting up an environment to work on. I don't even have a web server installed on my local machine, I use VMs for everything. I was going to build out a quick Docker or Vagrant for this project. Do you have a preference on which one? Is this overkill on a purely client side project?

**Comment by SamPotts** [comment]
Hey mate,

I've not really had a play with either but like you say it might be a bit overkill? Could you not use apache or the like in one of your VMs? I just use the built in apache in OS X. 

Cheers

**Comment by tomByrer** [comment]
Maybe make your own independent repo?
I agree that it could be overkill, but I could see it would be helpful in testing.  Perhaps in time you could add test cases (malformed MP4, play lists, etc) in time.

But too much to expect a someone else to handle.  I bet a link in this README to your Deocker image would suffice.
