### ISSUE TITLE
time higher 60 minutes starts at 0 min

### ISSUE THREAD

**Issue by ejb1123** [Selz/plyr#69]
When seeking or playing media and it passes the 60 min mark it lapses back to 0

**Comment by hakanw** [comment]
we have this problem too in our project

**Comment by SamPotts** [comment]
Very strange. I'll take a look.

**Comment by SamPotts** [comment]
Thanks for the feedback fellas :+1: This should be fixed now.

**Comment by hakanw** [comment]
Thanks for such an extremely quick turnaround @SamPotts !! :pray:
