### ISSUE TITLE
Some errors with the documentation?

### ISSUE THREAD

**Issue by SubZane** [Selz/plyr#72]
I've been looking for something like this, but I cannot get it to work the way it's described.

First. The script will auto-run without any initialization, not by using the plyr.setup method. 

The following will not disable the script as the docs tell me. It ignores all options I pass to it.
```
plyr.setup({
  enabled: false
});
```

**Comment by SubZane** [comment]
Never mind! I just looked in the wrong file for too long :(

**Comment by SamPotts** [comment]
No worries :+1:
