### ISSUE TITLE
Request: Youtube/Vimeo/Dailymotion support

### ISSUE THREAD

**Issue by AxelBriche** [Selz/plyr#73]
Youtube/Vimeo/Dailymotion support :)

**Comment by ejb1123** [comment]
similar request to #8

**Comment by SamPotts** [comment]
Duplicate of #8 - I will get to it asap but need to build some sort of plugin framework first. :+1:

**Comment by Jufik** [comment]
Is there any support/example to support a Dailymotion video?

**Comment by ssuunaian** [comment]
@sampotts still looking for it.
