### ISSUE TITLE
is there a fullscreen api i can use ?

### ISSUE THREAD

**Issue by wanghao8080** [Selz/plyr#74]
Thank you for the awesome work，is there a fullscreen api i can use ?

**Comment by SamPotts** [comment]
I'll write something for this now. Good idea :+1:

**Comment by wanghao8080** [comment]
Thank you Sam ：）

**Comment by SamPotts** [comment]
I've added a couple of methods that should be useful for you? Let me know. 

Bear in mind that due to browser security restrictions toggleFullscreen needs to be user initiated. e.g. 

```javascript
onSetup: function() {
	var player 	= this,
		type 	= player.media.tagName.toLowerCase(),
		toggle 	= document.querySelector("[data-toggle='fullscreen']");

	console.log("✓ Setup done for <" + type + ">");

	if(type === "video" && toggle) {
		toggle.addEventListener("click", player.toggleFullscreen, false);
	}
}
```

**Comment by wanghao8080** [comment]
Thank you ：）

**Comment by SamPotts** [comment]
Grab v1.1.3, there's a couple of other small fixes in it :+1:
