### ISSUE TITLE
Destroy Method

### ISSUE THREAD

**Issue by maimairel** [Selz/plyr#77]
I'm planning to use Plyr in an AJAX environment where pages are dynamically loaded. Currently there's no convenient way to destroy a Plyr instance to prevent memory leaks.

Is it possible to add a `.destroy()` method where all events are unbind, all markup removed, everything restored to the initial state.

Thanks!

**Comment by SamPotts** [comment]
Yep should be straightforward. I'll take a look. 

Cheers :+1:

**Comment by maimairel** [comment]
Thanks for considering this!

**Comment by nikolowry** [comment]
I was just about to request this.  I got around this by adding a removeMedia to my Backbone app's VideoPlayerView.  I'll attach a little standalone jQuery snippet of it. 

```javascript
var removeMedia = function () {
    var $player = $('.player')[0];
    $player.plyr.pause();
    $player.plyr.media.src = '';
    $player.find('source').props('src', '');
   //Now it's safe to unbind/undelegate all other events and destroy;
}
```

I hadn't done an ajax video implementation in a while so I don't know what might be overkill or not.  I always had memory leakage problems if I didn't remove the media before destroying the player element.

**Comment by SamPotts** [comment]
Sorry for the delay, this is now in the latest version. I created `destroy()` and `restore()` API methods. `destroy()` will basically restore the player to the original untouched state and `restore()` basically creates new instance. Let me know if that's what you were after. 

Remember if you're using AJAX, you can set the source using the `source(...)` API method:
https://github.com/Selz/plyr#api

**Comment by mukeshsan** [comment]
I've downloaded the latest version but still not I'm not getting the destroy & restore functions

"Uncaught TypeError: plyr.destroy is not a function"

**Comment by casjonker** [comment]
We might want to use PLYR, but we're still facing problems with memory leaks. After calling the `players[0].destroy()` method, the instance still exists... And the entire plyr DOM elements are still to be found in the applications memory as detached elements.

**Comment by kemalatila** [comment]
Another destroy method 

$('#player_container').html('');
$('#player_container').append('<video id="player"></video>');
const plyr = document.getElementById('player');
