### ISSUE TITLE
Captions not working in Firefox

### ISSUE THREAD

**Issue by arcadio813** [Selz/plyr#79]
Tried to display captions successfully with <code>captions:{defaultActive:!0}</code>. Unfortunately in FF 37 the div player-caption stays empty. Firebug reports 'Caption track found' and 'Successfully loaded the caption file via AJAX' as well as 'TextTracks not supported so rendering captions manually'. Am I doing something wrong or are there known issues with FF?

Thanks

**Comment by SamPotts** [comment]
Hey @arcadio813, Sorry to hear that. I've tested on Firefox and it seems ok for me. Have you tried http://plyr.io? Failing that, could you show me your VTT file?

**Comment by arcadio813** [comment]
Hi Sam, thank you for your quick reply. I downloaded plyr.js from GitHub, the VTT for testing was yours (I re-encoded it after copying to UTF-8 without BOM). In the meanwhile I played around with MIME-type settings in Apache, but still the same result :-(

**Comment by SamPotts** [comment]
What mime type were you using? It should be `text/vtt`. Maybe try using the demo file as mime type is already set. It can be found at `http://cdn.selz.com/plyr/1.0/en.vtt`. I'm not sure what else can be the problem to be honest.

**Comment by arcadio813** [comment]
Hi Sam, the problem was in my .htaccess file, now it works, thanks a bunch!

**Comment by SamPotts** [comment]
Glad to hear you got it sorted... :+1:
