### ISSUE TITLE
API should allow to set track (subtitle file)

### ISSUE THREAD

**Issue by calvintam236** [Selz/plyr#80]

**Comment by SamPotts** [comment]
:+1:

**Comment by calvintam236** [comment]
Thank you for considering this. One of my projects require switching subtitle using ajax.. I cannot do anything now until this is being added.. (Or I need to destroy and restore the whole player but need more code to restore the last point..)

**Comment by SamPotts** [comment]
This will be included in v1.5. Sorry it's taken so long.

**Comment by SamPotts** [comment]
Fixed in [v1.5.0](https://github.com/Selz/plyr/releases/tag/v1.5.0) as part of the new `source` API changes.

**Comment by calvintam236** [comment]
Is it possible to allow adding/ changing track without changing source file? Currently, the ```_updateSource``` check do not allow to change track only...
