### ISSUE TITLE
Video plays but caption does not show (Android)

### ISSUE THREAD

**Issue by calvintam236** [Selz/plyr#84]
Device: Nexus 5
OS: Android 5.1.0
Browser: Chrome Beta, Chrome Dev (Chrome runs normally)

**Comment by SamPotts** [comment]
Sorry I need to buy another Android device for testing to fix this one. Will get one asap.

**Comment by calvintam236** [comment]
@SamPotts I just checked the website on latest Chrome Beta & Dev. The issue is no longer exist. Maybe Google fixed it?
