### ISSUE TITLE
API doc wrote method name as "support", should be "supported"

### ISSUE THREAD

**Issue by calvintam236** [Selz/plyr#85]

**Comment by SamPotts** [comment]
Blimey. You're busy today. 

They do two different jobs. 

- `.support("video/mp4")` will check a plyr instance can support a certain mime type. e.g. "video/mp4"
- `.supported()` returns if plyr is supported by the users browser (https://github.com/Selz/plyr#checking-for-support). e.g. IE8 would return false. 

Might be worth having another quick read through the docs?

**Comment by calvintam236** [comment]
For me I got these two methods confused because of the name. I would suggest changing support to supportMIME or other name that clearer. Maybe you can also write "supported" method in the API list as well, @SamPotts?

**Comment by SamPotts** [comment]
`.supports()` might be a better name since you're basically asking `instance.supports(x)`. I'll move the position of the `.supported` docs but it doesn't work on a plyr instance, you can just call `plyr.supported()` so it works a little differently.

**Comment by calvintam236** [comment]
Maybe supportFormat()? Because "support" and "supported" is the same word
in different tenses. The meanings of two words are nearly the same. In
summary, supported is a global method for the plyr, not part of the
instance plyr.
