### ISSUE TITLE
Alternative method: togglePlayPause

### ISSUE THREAD

**Issue by calvintam236** [Selz/plyr#86]
Old methods can remain. Since you have toggle for fullscreen, captions. How about adding toggle method for play and pause? Although I have already wrote a conditional to decide play and pause on media status of paused, having toggle method of play/pause makes life easier. Simple implement.

**Comment by SamPotts** [comment]
Sure - I'll do this at lunch time, won't take long. :+1:

**Comment by SamPotts** [comment]
Added this in as `.togglePlay()` :+1:
