### ISSUE TITLE
Volume control gets a mysterious white border around it.

### ISSUE THREAD

**Issue by calvintam236** [Selz/plyr#87]
Device: Nexus 5
OS: Android 5.1.0
Browser: Firefox, Firefox Beta

![screenshot_2015-05-19-16-02-08](https://cloud.githubusercontent.com/assets/6436149/7715827/b0a843de-fe40-11e4-88fa-f256b327b732.png)

**Comment by SamPotts** [comment]
Will check this out. :+1:
