### ISSUE TITLE
Data URI source does not load only on Firefox

### ISSUE THREAD

**Issue by calvintam236** [Selz/plyr#89]
According to W3C, data URI is allowed for video source. However, data URI video source cannot load in Firefox (no such issue in Chrome, Opera). It becomes a loading loop. Video loads when source is a data url and page runs without the plugin (native player). This is a bug.

![loadingloop](https://cloud.githubusercontent.com/assets/6436149/7790596/aeb03c02-0242-11e5-88b3-d0717caeb69a.png)
.

**Comment by calvintam236** [comment]
After a few tests, I see it gives out error code 4 via console.log(plyr_object.media.error).
Error code 4 is MEDIA_ERR_SRC_NOT_SUPPORTED.
I do not know why it fires this error. Weird because the video I tested can play with native player, just not plyr...

**Comment by liuronghuan** [comment]
can i have a look at your player please?

**Comment by calvintam236** [comment]
I haven't tried on the latest version yet. You can paste the string in src to test on the new version. Old verson here: http://calvintam236.github.io/media-plyr/

[src.txt](https://github.com/Selz/plyr/files/94855/src.txt)

**Comment by SamPotts** [comment]
Closing this as it's a dupe of #157
