### ISSUE TITLE
Sprite sheet?

### ISSUE THREAD

**Issue by tomByrer** [Selz/plyr#9]
Could all the SVG be concocted & minified as 1 file ("sheet")?  Fewer HTTP requests, better for compression, etc

**Comment by SamPotts** [comment]
Hey Tom, yes we already do this. If you check the `dist` directory, there's a file `sprite.svg`. This contains all the SVG defs and then the default controls icons call the defs using `<use>`.

**Comment by SamPotts** [comment]
Checkout the `gulpfile.js` to see how the build works. The LESS to CSS and JS compression all happens there. Gulp is awesome (if you've not used it!).

**Comment by tomByrer** [comment]
Note to self; don't post bug reports after Midnight; might confuse `/src` with `/dist`  :fearful:

**Comment by SamPotts** [comment]
Haha no worries! :+1:
