### ISSUE TITLE
Subtitle positioning in full screen

### ISSUE THREAD

**Issue by calvintam236** [Selz/plyr#92]
Should the subtitle position depends on screen edge when the navigation of the player is hidden? It looks weird to position it in the middle of the screen at this case.

![screenshot_20150607-221341](https://cloud.githubusercontent.com/assets/6436149/8028493/d2c72372-0d63-11e5-8e4d-94daf09948f1.png)
![screenshot_20150607-221350](https://cloud.githubusercontent.com/assets/6436149/8028494/d2e96b12-0d63-11e5-9e95-39fb73599d0a.png)

**Comment by SamPotts** [comment]
Good point! :+1:

**Comment by SamPotts** [comment]
Is this still an issue? I think I pushed a tweak for this...

**Comment by calvintam236** [comment]
Yes, it is. Just tested on Chrome (Android).

**Comment by calvintam236** [comment]
Added screenshot.
![screenshot_2015-07-24-17-57-30](https://cloud.githubusercontent.com/assets/6436149/8887223/a69db4de-322d-11e5-9d69-3f3256eaeff5.png)
![screenshot_2015-07-24-17-57-19](https://cloud.githubusercontent.com/assets/6436149/8887226/b525104c-322d-11e5-910b-9d32d4837cbc.png)
