### ISSUE TITLE
Demo crossorigin error

### ISSUE THREAD

**Issue by calvintam236** [Selz/plyr#95]
I guess it is caused by the poster.

```Image from origin 'https://cdn.plyr.io' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://plyr.io' is therefore not allowed access.```

**Comment by SamPotts** [comment]
This is a browser bug, not a problem with Plyr. You'll notice if you refresh, 9 times out of 10 you won't get it. You don't need the cross origin attribute unless your tracks are being hosted on a different domain (like a CDN in the demo). Unfortunately the `crossorigin` attribute is not support on the `<track>` element itself. If you remove it on the `<video>` element you'll get another message:

```
Text track from origin 'http://cdn.selz.com' has been blocked from loading: Not at same origin as the document, and parent of track element does not have a 'crossorigin' attribute. Origin 'http://localhost' is therefore not allowed access.
```

I'd suggest you raise it with Chrome or Safari if it's an issue for you.

**Comment by SamPotts** [comment]
The most annoying part is that header *is* present on the image response. 

![screen shot 2015-06-11 at 5 02 02 pm](https://cloud.githubusercontent.com/assets/719092/8119520/a550a9c2-105b-11e5-95de-1243aacebec0.png)

**Comment by dungphanxuan** [comment]
i set crossorigin on video tag, so it not work

**Comment by mlearncore2018** [comment]
I see a similar error for a image and video resource. I also checked the request error and I do not see the request header for the image.
