### ISSUE TITLE
safari full screen

### ISSUE THREAD

**Issue by jayss** [Selz/plyr#96]
there's a bug after full screen in safari browser, the page can't scroll at all

**Comment by SamPotts** [comment]
Hey @jayss, could you give me some more information on this? Safari on iOS or Desktop? What version? Looks ok here.

**Comment by calvintam236** [comment]
@SamPotts Actually when I click full screen in Safari, the full screen is not a full screen. It is a full window.. I believe this is what he mentioned.

Attached screenshot when it is toggled to full screen.
![safari_fullscreen](https://cloud.githubusercontent.com/assets/6436149/8888734/eee79aac-326e-11e5-8707-0679d26ff20d.png)

**Comment by SamPotts** [comment]
That's intended as Safari doesn't allow keyboard input in full screen mode... 
https://github.com/Selz/plyr/blob/master/src/js/plyr.js#L556

**Comment by calvintam236** [comment]
Is it necessary to have "ALLOW_KEYBOARD_INPUT" flag in Safari? If it does not support the tag, it should able to request a full screen without keyboard.

I just googled and see a demo that has no issue to request full screen in Safari. http://www.sitepoint.com/html5-full-screen-api/
Don't know if there is any help.

**Comment by SamPotts** [comment]
Did you read the code in the link? I tested it and found it to be an issue, hence disabling it. Things may have changed since then. I'll take another look.

**Comment by SamPotts** [comment]
Looks like it's ok now.

**Comment by calvintam236** [comment]
Thank you, @SamPotts. Works now! :+1:

**Comment by SamPotts** [comment]
:+1:
